-- Reparación comun: tipo_teleco → id_tipo_teleco en public/resto/restov (publicador + réplica).
DO $$
DECLARE
    r RECORD;
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'xd_tipo_teleco'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE public.xd_tipo_teleco
            ADD COLUMN id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    FOR r IN
        SELECT c.table_schema, c.table_name
        FROM information_schema.columns c
        WHERE c.column_name = 'tipo_teleco'
          AND c.table_schema IN ('public', 'resto', 'restov')
    LOOP
        EXECUTE format('ALTER TABLE %I.%I REPLICA IDENTITY FULL', r.table_schema, r.table_name);

        EXECUTE format(
            'UPDATE %I.%I d SET tipo_teleco = t.id::text
             FROM public.xd_tipo_teleco t
             WHERE d.tipo_teleco = t.tipo_teleco',
            r.table_schema,
            r.table_name
        );

        EXECUTE format(
            'ALTER TABLE %I.%I RENAME COLUMN tipo_teleco TO id_tipo_teleco',
            r.table_schema,
            r.table_name
        );

        EXECUTE format(
            'ALTER TABLE %I.%I ALTER COLUMN id_tipo_teleco TYPE int USING id_tipo_teleco::integer',
            r.table_schema,
            r.table_name
        );

        EXECUTE format(
            'ALTER TABLE %I.%I ALTER COLUMN id_tipo_teleco SET NOT NULL',
            r.table_schema,
            r.table_name
        );

        RAISE NOTICE 'tipo_teleco migrado en %.%.', r.table_schema, r.table_name;
    END LOOP;
END $$;
