-- Renombres status/active, PK/NOT NULL/IDENTITY y migración tipo_teleco → id_tipo_teleco.
ALTER TABLE public.u_cdc RENAME COLUMN status TO active;
ALTER TABLE public.u_cdc RENAME COLUMN f_status TO f_active;

ALTER TABLE public.xu_region RENAME COLUMN status TO active;
ALTER TABLE public.xa_asignaturas RENAME COLUMN status TO active;

ALTER TABLE public.db_idschema ALTER COLUMN id SET NOT NULL;

ALTER TABLE resto.map_id ADD PRIMARY KEY (objeto, id_resto);

ALTER TABLE public.xe_sectores ADD PRIMARY KEY (id_sector);

ALTER TABLE public.xd_tipo_teleco
    ADD COLUMN id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.xd_desc_teleco ALTER COLUMN id_item ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.e_notas_situacion ALTER COLUMN id_situacion ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.d_teleco_cdc ALTER COLUMN id_item ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.xu_dl RENAME COLUMN status TO active;
ALTER TABLE public.xu_dl ALTER COLUMN id_dl SET NOT NULL;
ALTER TABLE public.xu_dl ALTER COLUMN id_dl ADD GENERATED BY DEFAULT AS IDENTITY;
-- Secuencia: public.xu_dl_id_dl_seq (pg_get_serial_sequence('xu_dl', 'id_dl'))
SELECT setval('public.xu_dl_id_dl_seq', (SELECT max(id_dl) FROM public.xu_dl), true);

-- xd_desc_teleco: tipo_teleco texto → id_tipo_teleco entero
UPDATE public.xd_desc_teleco d
SET tipo_teleco = t.id
FROM public.xd_tipo_teleco t
WHERE d.tipo_teleco = t.tipo_teleco;
ALTER TABLE public.xd_desc_teleco RENAME COLUMN tipo_teleco TO id_tipo_teleco;
ALTER TABLE public.xd_desc_teleco ALTER COLUMN id_tipo_teleco TYPE int USING id_tipo_teleco::integer;
ALTER TABLE public.xd_desc_teleco ALTER COLUMN id_tipo_teleco SET NOT NULL;

-- d_teleco_cdc: tipo_teleco texto → id_tipo_teleco entero
UPDATE public.d_teleco_cdc d
SET tipo_teleco = t.id
FROM public.xd_tipo_teleco t
WHERE d.tipo_teleco = t.tipo_teleco;
ALTER TABLE public.d_teleco_cdc RENAME COLUMN tipo_teleco TO id_tipo_teleco;
ALTER TABLE public.d_teleco_cdc ALTER COLUMN id_tipo_teleco TYPE int USING id_tipo_teleco::integer;
ALTER TABLE public.d_teleco_cdc ALTER COLUMN id_tipo_teleco SET NOT NULL;
