-- Renombres status/active, PK/NOT NULL/IDENTITY y migración tipo_teleco → id_tipo_teleco (idempotente).
SELECT migracion_rename_columna('public', 'u_cdc', 'status', 'active');
SELECT migracion_rename_columna('public', 'u_cdc', 'f_status', 'f_active');
SELECT migracion_rename_columna('public', 'xu_region', 'status', 'active');
SELECT migracion_rename_columna('public', 'xa_asignaturas', 'status', 'active');
SELECT migracion_rename_columna('public', 'xu_dl', 'status', 'active');

DO $$
BEGIN
    BEGIN
        ALTER TABLE public.db_idschema ALTER COLUMN id SET NOT NULL;
    EXCEPTION
        WHEN others THEN
            PERFORM migracion_aviso('public.db_idschema.id NOT NULL: ' || SQLERRM);
    END;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'map_id_pkey' AND conrelid = 'resto.map_id'::regclass
    ) THEN
        BEGIN
            ALTER TABLE resto.map_id ADD PRIMARY KEY (objeto, id_resto);
        EXCEPTION
            WHEN duplicate_table THEN
                PERFORM migracion_aviso('resto.map_id PK ya existe (omitido)');
        END;
    ELSE
        PERFORM migracion_aviso('resto.map_id PK ya existe (omitido)');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'xe_sectores_pkey' AND conrelid = 'public.xe_sectores'::regclass
    ) THEN
        BEGIN
            ALTER TABLE public.xe_sectores ADD PRIMARY KEY (id_sector);
        EXCEPTION
            WHEN duplicate_table THEN
                PERFORM migracion_aviso('public.xe_sectores PK ya existe (omitido)');
        END;
    ELSE
        PERFORM migracion_aviso('public.xe_sectores PK ya existe (omitido)');
    END IF;

    IF NOT migracion_columna_existe('public', 'xd_tipo_teleco', 'id') THEN
        ALTER TABLE public.xd_tipo_teleco
            ADD COLUMN id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;
    ELSE
        PERFORM migracion_aviso('public.xd_tipo_teleco.id ya existe (omitido)');
    END IF;

    BEGIN
        ALTER TABLE public.xd_desc_teleco ALTER COLUMN id_item ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
        WHEN others THEN
            PERFORM migracion_aviso('public.xd_desc_teleco.id_item identity: ' || SQLERRM);
    END;

    BEGIN
        ALTER TABLE public.e_notas_situacion ALTER COLUMN id_situacion ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
        WHEN others THEN
            PERFORM migracion_aviso('public.e_notas_situacion.id_situacion identity: ' || SQLERRM);
    END;

    BEGIN
        ALTER TABLE public.d_teleco_cdc ALTER COLUMN id_item ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
        WHEN others THEN
            PERFORM migracion_aviso('public.d_teleco_cdc.id_item identity: ' || SQLERRM);
    END;

    BEGIN
        ALTER TABLE public.xu_dl ALTER COLUMN id_dl SET NOT NULL;
        ALTER TABLE public.xu_dl ALTER COLUMN id_dl ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
        WHEN others THEN
            PERFORM migracion_aviso('public.xu_dl.id_dl identity: ' || SQLERRM);
    END;
END $$;

DO $$
BEGIN
    IF to_regclass('public.xu_dl_id_dl_seq') IS NOT NULL THEN
        PERFORM setval('public.xu_dl_id_dl_seq', (SELECT max(id_dl) FROM public.xu_dl), true);
    ELSE
        PERFORM migracion_aviso('public.xu_dl_id_dl_seq no existe (omitido setval)');
    END IF;
END $$;

SELECT migracion_migrar_tipo_teleco_public('public', 'xd_desc_teleco');
SELECT migracion_migrar_tipo_teleco_public('public', 'd_teleco_cdc');
