-- Reparación 202604040000: tipo_teleco → id_tipo_teleco en xd_desc_teleco y d_teleco_cdc (comun + comun_select).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'xd_tipo_teleco'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE public.xd_tipo_teleco
            ADD COLUMN id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'xd_desc_teleco'
          AND column_name = 'tipo_teleco'
    ) THEN
        ALTER TABLE public.xd_desc_teleco REPLICA IDENTITY FULL;

        UPDATE public.xd_desc_teleco d
        SET tipo_teleco = t.id::text
        FROM public.xd_tipo_teleco t
        WHERE d.tipo_teleco = t.tipo_teleco;

        ALTER TABLE public.xd_desc_teleco RENAME COLUMN tipo_teleco TO id_tipo_teleco;
        ALTER TABLE public.xd_desc_teleco ALTER COLUMN id_tipo_teleco TYPE int USING id_tipo_teleco::integer;
        ALTER TABLE public.xd_desc_teleco ALTER COLUMN id_tipo_teleco SET NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'd_teleco_cdc'
          AND column_name = 'tipo_teleco'
    ) THEN
        ALTER TABLE public.d_teleco_cdc REPLICA IDENTITY FULL;

        UPDATE public.d_teleco_cdc d
        SET tipo_teleco = t.id::text
        FROM public.xd_tipo_teleco t
        WHERE d.tipo_teleco = t.tipo_teleco;

        ALTER TABLE public.d_teleco_cdc RENAME COLUMN tipo_teleco TO id_tipo_teleco;
        ALTER TABLE public.d_teleco_cdc ALTER COLUMN id_tipo_teleco TYPE int USING id_tipo_teleco::integer;
        ALTER TABLE public.d_teleco_cdc ALTER COLUMN id_tipo_teleco SET NOT NULL;
    END IF;
END $$;
