<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= _("Leyenda") ?></title>
    <link rel="stylesheet" href="css/calendario.css">
    <style>
        td.comment {
            border: none;
            text-align: left;
            padding-left: 10px;
        }

        p {
            font-size: 8pt;
            text-align: center;
            text-decoration: none;
            color: black;
            font-family: arial, helvetica, sans-serif;
        }
    </style>
</head>
<body>
<h3><?= _("Leyenda") ?></h3>

<table style="border: none">
    <tr>
        <td class="actsv_nomod"><?= _("actividad sv") ?></td>
        <td class="comment"><?= _("para actividades de sv") ?></td>
    </tr>
    <tr>
        <td class="actsf_nomod"><?= _("actividad sf") ?></td>
        <td class="comment"><?= _("para actividades de sf") ?></td>
    </tr>
    <tr>
        <td class="actotras_nomod"><?= _("actividad otras") ?></td>
        <td class="comment"><?= _("para otras actividades") ?></td>
    </tr>
    <tr>
        <td class="actpropio_nomod"><?= _("actividad propia") ?></td>
        <td class="comment"><?= _("para actividades propias") ?></td>
    </tr>
    <tr>
        <td class="actpersonal_nomod"><?= _("actividad personal") ?></td>
        <td class="comment"><?= _("para actividades personales") ?></td>
    </tr>
    <tr>
        <td class="provisional"><?= _("actividad provisional") ?></td>
        <td class="comment"><?= _("si plaza es: Pedida, En espera o Denegada") ?></td>
    </tr>
    <tr>
        <td class="proyecto"><?= _("actividad en proyecto") ?></td>
        <td class="comment"><?= _("para actividades en proyecto") ?></td>
    </tr>
</table>
</body>
</html>
