<?php

use frontend\shared\config\AppUrlConfig;

?>
<script>
    fnjs_nueva_activ = function (id_ubi) {
        $('#div_modificar').addClass('ventana');
        $('#div_modificar').width('auto');
        $('#div_modificar').height('auto');
        document.getElementById("overlay").style.display = "block";

        var url = '<?= AppUrlConfig::getPublicAppBaseUrl() ?>/frontend/actividades/controller/planning_casa_nueva.php';
        var parametros = 'id_ubi=' + id_ubi + "&<?= $param_new ?>";

        fnjs_update_div('#div_modificar', url + '?' + parametros, 1);
    }
    fnjs_cambiar_activ = function (id_activ) {
        $('#div_modificar').addClass('ventana');
        $('#div_modificar').width('auto');
        $('#div_modificar').height('auto');
        document.getElementById("overlay").style.display = "block";

        var url = '<?= AppUrlConfig::getPublicAppBaseUrl() ?>/frontend/actividades/controller/planning_casa_modificar.php';
        var parametros = 'id_activ=' + id_activ + "&<?= $param_mod ?>";

        fnjs_update_div('#div_modificar', url + '?' + parametros, 1);
    }
    fnjs_cerrar = function () {
        $('#div_modificar').html('');
        $('#div_modificar').width('0');
        $('#div_modificar').height('0');
        $('#div_modificar').removeClass('ventana');
        document.getElementById("overlay").style.display = "none";
    }

    fnjs_ver = function () {
        var url = '<?= AppUrlConfig::getPublicAppBaseUrl() ?>/frontend/planning/controller/planning_casa_ver.php';
        var parametros = "<?= $param_ver ?>";

        $('#ficha').html('');
        fnjs_ajax_json_html({
            url: url,
            data: parametros,
            target: '#ficha',
            onDone: function () {
                document.getElementById("overlay").style.display = "none";
            }
        });
    }

    $(document).ready(fnjs_ver());
</script>
<?= $oPosicion->mostrar_left_slide(1) ?>

<div id='ficha'></div>
<div id='div_modificar'></div>
<div id='overlay'></div>
