<!DOCTYPE html>
<?php

?>
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
<style>
    html {
        height: 100%
    }

    ::-moz-selection {
        background: #fe57a1;
        color: #fff;
        text-shadow: none;
    }

    ::selection {
        background: #fe57a1;
        color: #fff;
        text-shadow: none;
    }

    /*
    body {
        background-image: radial-gradient(cover, rgba(92, 100, 111, 1) 0%, rgba(31, 35, 40, 1) 100%), url('http://i.minus.com/io97fW9I0NqJq.png')
    }
    */

    .login {
    <?php
    if ($ubicacion == 'sv') {
      echo "background: #eceeee;";
    } else {
      echo "background: #fadfd5;";
    }
    ?> border: 1px solid #42464b;
        border-radius: 6px;
        height: auto;
        margin: 20px auto 0;
        width: 298px;
    }

    div.esquema {
        display: inline-block;
        position: relative;
        text-align: right;
        margin-right: 10px;
        margin-top: 8px;
        width: 85%;
        font-family: Arial, serif;
        font-size: 15px;
    }

    div.ubicacion {
        display: inline-block;
        position: relative;
        font-family: Arial, serif;
        font-size: 15px;
        text-align: right;
        margin-left: 10px;
        margin-top: 8px;
    }

    #version {
        position: relative;
        font: 9px/1 sans-serif;
        text-align: right;
        margin-right: 10px;
        margin-bottom: 10px;
    }

    .login h2 {
        text-align: center;
    }

    .login h1 {
        /* background-image: linear-gradient(top, #f1f3f3, #d4dae0); */
        border-bottom: 1px solid #a6abaf;
        border-radius: 6px 6px 0 0;
        box-sizing: border-box;
        color: #727678;
        display: block;
        height: 43px;
        font: 600 14px/1 'Open Sans', sans-serif;
        padding-top: 9px;
        margin: 0;
        text-align: center;
        text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2), 0 1px 0 #fff;
    }

    input[type="password"], input[type="text"] {
        /* background: url('http://i.minus.com/ibhqW9Buanohx2.png') center left no-repeat, linear-gradient(top, #d6d7d7, #dee0e0); */
        border: 1px solid #a1a3a3;
        border-radius: 4px;
        box-shadow: 0 1px #fff;
        box-sizing: border-box;
        color: #696969;
        height: 39px;
        margin: 31px 0 0 29px;
        padding-left: 37px;
        transition: box-shadow 0.3s;
        width: 240px;
    }

    input[type="password"]:focus, input[type="text"]:focus {
        box-shadow: 0 0 4px 1px rgba(55, 166, 155, 0.3);
        outline: 0;
    }

    .show-password {
        display: block;
        height: 16px;
        margin: 26px 0 0 28px;
        width: 87px;
    }

    input[type="checkbox"] {
        cursor: pointer;
        height: 16px;
        opacity: 0;
        position: relative;
        width: 64px;
    }

    input[type="checkbox"]:checked {
        left: 29px;
        width: 58px;
    }

    .toggle {
        background: url(http://i.minus.com/ibitS19pe8PVX6.png) no-repeat;
        display: block;
        height: 16px;
        margin-top: -20px;
        width: 87px;
        z-index: -1;
    }

    input[type="checkbox"]:checked + .toggle {
        background-position: 0 -16px
    }

    .forgot {
        color: #7f7f7f;
        display: inline-block;
        float: right;
        font: 12px/1 sans-serif;
        left: -19px;
        position: relative;
        text-decoration: none;
        top: 5px;
        transition: color .4s;
    }

    .forgot:hover {
        color: #3b3b3b
    }

    input[type="submit"] {
        width: 240px;
        height: 35px;
        display: block;
        font-family: Arial, "Helvetica", sans-serif;
        font-size: 16px;
        font-weight: bold;
        color: #fff;
        text-decoration: none;
        text-transform: uppercase;
        text-align: center;
        text-shadow: 1px 1px 0px #37a69b;
        padding-top: 2px;
        margin: 29px 0 0 29px;
        position: relative;
        cursor: pointer;
        border: none;
        background-color: #37a69b;
        /* background-image: linear-gradient(top, #3db0a6, #3111); */
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
        box-shadow: inset 0px 1px 0px #2ab7ec, 0px 5px 0px 0px #497a78, 0px 10px 5px #999;
    }

    .shadow {
        background: #000;
        border-radius: 12px 12px 4px 4px;
        box-shadow: 0 0 20px 10px #000;
        height: 12px;
        margin: 30px auto;
        opacity: 0.2;
        width: 270px;
    }

    input[type="submit"]:active {
        top: 3px;
        box-shadow: inset 0px 1px 0px #2ab7ec, 0px 2px 0px 0px #31524d, 0px 5px 3px #999;
    }

</style>
<script type="text/javascript">
    fnjs_goHelp = async function () {
        const form = document.getElementById('frm_login');
        const formData = new FormData(form); // Captura todos los campos del formulario
        const url = 'frontend/usuarios/controller/ayuda_acceso.php'; // La URL a la que se enviará la petición

        try {
            const response = await fetch(url, {
                method: 'POST',
                body: formData // fetch maneja FormData automáticamente para multipart/form-data
            });

            if (!response.ok) { // `response.ok` es true para códigos de estado 200-299
                const errorText = await response.text(); // O .json() si esperas JSON de error
                throw new Error(`HTTP error! status: ${response.status} - ${errorText}`);
            }

            const responseData = await response.text(); // O .json() si esperas JSON
            //console.log('Respuesta del servidor (éxito):', responseData);
            document.body.innerHTML = responseData;
            /*
            alert('Formulario enviado con éxito: ' + responseData);
            // Aquí puedes actualizar la UI, limpiar el formulario, etc.
            form.reset();

             */

        } catch (error) {
            console.error('Error al enviar el formulario con Fetch:', error);
            alert('Error al enviar el formulario: ' + error.message);
        }
    }

    fnjs_hideErrors = function () {
        let alerta = document.getElementById('div_error_login');
        if (alerta) {
            alerta.style.display = 'none';
        }
    }

    fnjs_goTop = function () {
        menu = document.getElementById("menu");
        if (menu) {
            window.location.href = "<?= $url ?>";
        }
    }
    document.onload = fnjs_goTop();
</script>
<div class="login" onClick="fnjs_hideErrors();">
    <div class="ubicacion"><?= $ubicacion ?></div>
    <div class="esquema"><?= $esquema_web ?></div>
    <?php
    $PHP_SELF = $_SERVER['PHP_SELF'];
    ?>
    <form id="frm_login" class="form-signin" action="<?= $PHP_SELF ?>" method=post>
        <input type="hidden" name="idioma" value="<?= $idioma ?>"/>
        <h2>Aquinate</h2>
        <h1>(orbix)</h1>
        <h1><?= _("stgr y actividades") ?></h1>
        <?php if (empty($esquema_web)) { ?>
            <h1><?= ucfirst(_("ubicación")) ?>: <?= $DesplRegiones ?></h1>
        <?php } else { ?>
            <input type="hidden" name="esquema" value="<?= $esquema_web ?>"/>
        <?php } ?>
        <input type="text" name="username" placeholder="<?= _("nombre de usuario") ?>" required="" autofocus=""
               value="<?= $username ?>"/>
        <input type="password" name="password" placeholder="Password" required=""/>
        <input type="text" name="verification_code" placeholder="<?= _("código de verificación (2FA)") ?>"
               autocomplete="off"/>
        <br>
        <input type="submit" value="<?= ucfirst(_("iniciar sesión")) ?>"/>
        <br>
    </form>
    <div id="version">v 1.2</div>
<?php
if (!empty($error)) { ?>
    <div id="div_error_login" style="position: fixed; top: 10%; margin-left: -50px;
        border-style: solid; border-color: gray; border-radius: 10px; padding: 10px;
        background-color: #fadbaf; ">
        <div style="color: red; " >
            <?php
            if ($error == 1) {
                echo _("El nombre de usuario, o el password no son válidos");
                echo "<br>";
                echo _("Por favor, vuelva a intentarlo");
            }
            if ($error == 2) {
                echo _("Este usuario no puede entrar desde esta instalación");
            }
            if ($error == 3) {
                echo _("Se requiere código de verificación 2FA");
            }
            if ($error == 4) {
                echo _("Código de verificación 2FA inválido");
            }
            ?>
        </div>
        <div style="text-align: center; margin-top: 10px;">
            <a href="#" onclick="fnjs_goHelp()"
               style="color: #37a69b; text-decoration: none; font-size: small;">
                <?= _("¿Tiene problemas para acceder?") ?>
            </a>
        </div>
    </div>
<?php } ?>
</div>
