<html>
 <head>
  <script type="text/javascript">
	/* Asegurarme que ya existe algo en la pagina, para empezar de cero
	 * No puedo usar jquery porque al inicio no hay nada cargado.
	 */
	var x = document.getElementById("cargando");
	if ( x != null) {
	  window.location.replace("http://<?= core\ConfigGlobal::getWeb() ?>");
	}  
  </script>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Test for Login</title>
  <style type="text/css">
  <!--
    body { font-family: Arial, Helvetica, sans-serif }
    td   { font-family: Arial, Helvetica, sans-serif }
  -->
  </style>
 </head>

<body bgcolor="#ffffff">
<h1>Test de entrada</h1>

Benvingut! <br>

Si us plau, identifica't amb un nom i un password:<br>
<?php
$PHP_SELF = $_SERVER['PHP_SELF'];
?>
<form action="<?= $PHP_SELF ?>" method=post>
<table border=0 bgcolor="#eeeeee" align="center" cellspacing=0 cellpadding=4>
 <tr valign=top align=left>
  <td>Ubicació:</td>
  <td><?= $DesplRegiones ?></td>
 </tr>
 <tr valign=top align=left>
  <td>Nom d'usuari:</td>
  <td><input type="text" name="username"
  size=32 maxlength=32></td>
 </tr>
 <tr valign=top align=left>
  <td>Password:</td>
  <td><input type="password" name="password" size=32 maxlength=32></td>
 </tr>
 
 <tr>
  <td>&nbsp;</td>
  <td align=right><input type="submit" name="submit" value="Entrar ara"></td>
 </tr>
</table>
<?php if ( isset($error) && $error==1 ) { ?>
 <!-- failed login code -->
 <p>
 <table>
  <tr>
   <td colspan=2><font color=red><b>Bé el nom d'usuari, o bé el password són invàlids.<br>
       Si us plau, torna a provar-ho!</b></font></td>
  </tr>
 </table>
<?php } ?>
</form>
</body>
<script type="JavaScript">
  if (document.forms[0][0].value != '') {
      document.forms[0][1].focus();
  } else {
      document.forms[0][0].focus();
  }
</script>
</html>
