<div style="border: 2px; border-style: solid; padding: 15px; } ">
    <?php if (!empty($aviso_txt)) { ?>
        <p><?= $aviso_txt ?></p>
        <br>
        <input type='button' value="<?= _("cancelar") ?>" onclick='fnjs_mover_cerrar();'>
    <?php } else { ?>
        <form id="frm_mover" name="frm_mover" action="apps/asistentes/controller/update_3101.php" method="POST">
            <?= $oHashNuevo->getCamposHtml(); ?>
            <table style="width: 400px">
                <tr>
                    <td class=etiqueta><?= ucfirst(_("mover a")) ?>:</td>
                    <td><?= $oDesplActividades->desplegable(); ?></td>
                </tr>
                <tr>
                    <td class=etiqueta><?= ucfirst(_("observaciones")); ?></td>
                    <td class=contenido>
                        <textarea id="observ" name="observ" cols="40"
                                  rows="5"><?= htmlspecialchars($observ ?? '' ?? '') ?></textarea></td>
                </tr>
            </table>
            <br>
            <input type="button" id="guardar" name="guardar" onclick="fnjs_mover_guardar('#frm_mover');"
                   value="<?= ucfirst(_("guardar")); ?>" align="MIDDLE">
            <input type='button' value="<?= _("cancelar") ?>" onclick='fnjs_mover_cerrar();'>
        </form>
    <?php } ?>
</div>