<script>
    fnjs_ver_planning = function (formulario, n) {
        var err = 0;
        var f = $('#periodo').val();
        if (!f) {
            err = 1;
        }
        if (f == 'otro') {
            if (!fnjs_comprobar_fecha('#empiezamin',<?= $locale_us ?>)) {
                err = 1;
            }
            if (!fnjs_comprobar_fecha('#empiezamax',<?= $locale_us ?>)) {
                err = 1;
            }
        }

        if (err == 1) {
            if (!f) {
                alert("<?= _("falta definir un periodo") ?>");
            } else {
                alert("<?= _("debe introducir las fechas inicio-fin del periodo") ?>");
            }
        } else {
            $('#modelo').val(n);
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_left_side_hide();
</script>
<form id="que" name="que" action="apps/asistentes/controller/planning_select.php" method="post"
      onkeypress="fnjs_enviar(event,this);">
    <input type="hidden" id="modelo" name="modelo" value="">
    <?= $oHashNuevo->getCamposHtml(); ?>
    <table>
        <tr>
            <th class=titulo_inv colspan="2">
                <?= core\strtoupper_dlb(sprintf(_("búsqueda de personas %s"), $personas_txt)); ?></th>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("nombre")); ?></td>
            <td><input class=contenido id="nombre" name="nombre" size="30"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("primer apellido")); ?></td>
            <td><input class=contenido id="apellido1" name="apellido1" size="40"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("segundo apellido")); ?></td>
            <td><input class=contenido id="apellido2" name="apellido2" size="40"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("centro")); ?></td>
            <td><input class=contenido id="centro" name="centro"></td>
        </tr>
    </table>
    <?= $oFormP->getHtml(); ?>
    <table>
        <tfoot>
        <tr class=botones>
            <td><input TYPE="button" onclick="fnjs_ver_planning(this.form,0)" id="btn_ok" name="btn_ok"
                       value="<?= ucfirst(_("buscar")); ?>" class="btn_ok"></td>
        </tr>
        </tfoot>
</form>