<script>
fnjs_ver_planning = function(formulario,n) {
	periodo = $('#periodo').val();
	if (!periodo) {
		alert('<?= _("Falta definir un periodo") ?>');
	} else {
		$('#modelo').val(n);
		fnjs_enviar_formulario(formulario);
	}
}
fnjs_left_side_hide();
</script>
<form name="que" id="que" action="apps/asistentes/controller/planning_crida_calendari.php" method="post">
<input type="hidden" id="modelo" name="modelo" value="">
<?= $oHash2->getCamposHtml(); ?>
<?= $oForm->getHtmlTabla(); ?>
<?= _('incluir casas sin actividad:') ?>
<input type="Radio" id="sin_activ" name="sin_activ" value=0 checked> <?= _("no") ?>
<input type="Radio" name="sin_activ" value=1> <?= _("si") ?>
<?= $oFormP->getHtml(); ?>
<table>
<tfoot>
<tr class=botones>
<td><input TYPE="button" onclick="fnjs_ver_planning(this.form,1)" value="<?= ucfirst(_('planning vista tabla')); ?>" ></td>
<td><input TYPE="button" onclick="fnjs_ver_planning(this.form,3)" value="<?= ucfirst(_('planning vista grid')); ?>" ></td>
<td colspan=2><input TYPE="button" onclick="fnjs_ver_planning(this.form,2)" value="<?= _('Vista para imprimir'); ?>"></td>
</tr></tfoot>
</table>
</form>