<script>

    fnjs_ver_planning = function (formulario, n) {
        $('#modelo').val(n);
        $(formulario).attr('action', "apps/asistentes/controller/planning_crida_calendari.php");
        fnjs_enviar_formulario(formulario);
    }
    fnjs_planning_print = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#modelo').val('2');
            $(formulario).attr('target', 'print');
            $(formulario).attr('action', "apps/asistentes/controller/planning_crida_calendari.php");
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_actividades = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#que').val("activ");
            $('#id_dossier').val("1301y1302");
            $(formulario).attr('action', "apps/dossiers/controller/dossiers_ver.php");
            fnjs_enviar_formulario(formulario);
        }
    }
</script>
<h3><?= sprintf(_("%s personas encontradas"), $num_personas); ?></h3>
<form id='seleccionados' name='seleccionados' action='' method='post'>
    <?= $oHashNuevo->getCamposHtml(); ?>
    <input type="hidden" id="modelo" name="modelo" value="">
    <input type='hidden' id='que' name='que' value=''>
    <input type='hidden' id='id_dossier' name='id_dossier' value=''>
    <?= $oTabla->mostrar_tabla(); ?>
</form>
