<script>
fnjs_buscar=function(form){
	var err=0;
	// Hay opciones que no muestran el periodo.
	if ($(form).periodo) {
		// comprobar que tiene el periodo.
		var periodo = $(form).periodo.value;
		if (!periodo) { err=1; }
		if (periodo == 'otro') {
			var min = $(form).empiezamin.value;
			var max = $(form).empiezamax.value;
			if (min && max) {
				err=0;
			} else {
				err=1;
			}
		}
	}
	if (err==1) {
		alert ("<?= _("debe introducir un periodo") ?>");
	} else {
		fnjs_enviar_formulario(form);
	}
}

fnjs_otro=function(v){
	if (v==1) {
		$('#oro').show();
		$('#n_agd_4').checked="true";
	} else {
		$('#oro').hide();	
	}
 }
// por defecto escondido.
<?php if (empty($c)) { ?>
$('#oro').hide();
<?php } ?>
</script>
<div>
<h2 class="subtitulo"><?= $tituloGros ?></h2>
<form id="modifica" name="modifica" action="<?= $action ?>" method="POST">
<?= $oHash->getCamposHtml(); ?>
<table>
<thead><th class="titulo_inv" colspan=6><?= $titulo ?></th></thead>
<tbody>
<tr><td class="etiqueta" onclick="fnjs_otro(0);">
	<input type="radio" id="n_agd_1" name="n_agd" value="n" <?= $n ?> ><?= ucfirst(_("todos los numerarios"))?></td>
	<td class="etiqueta"><input type="radio" id="n_agd_11" name="n_agd" value="nj" <?= $nj ?> ><?= ucfirst(_("todos ctr numerarios jóvenes"))?></td>
	<td class="etiqueta"><input type="radio" id="n_agd_12" name="n_agd" value="nm" <?= $nm ?> ><?= ucfirst(_("todos ctr numerarios mayores"))?></td>
</tr>
<tr><td class="etiqueta" onclick="fnjs_otro(0);">
<input type="radio" id="n_agd_2" name="n_agd" value="a" <?= $a ?> ><?= ucfirst(_("todos los agregados"))?></td></tr>
<?php 
if (core\ConfigGlobal::mi_sfsv() == 1) { ?>
<tr><td class="etiqueta" onclick="fnjs_otro(0);">
<input type="radio" id="n_agd_3" name="n_agd" value="sss" <?= $sss ?> ><?= ucfirst(_("todos los de sss+"))?></td></tr>
<?php } else { ?>
<tr><td class="etiqueta" onclick="fnjs_otro(0);">
<input type="radio" id="n_agd_3" name="n_agd" value="nax" <?= $nax ?> ><?= ucfirst(_("todos los de nax"))?></td></tr>
<?php } ?>

<tr><td class="etiqueta">
<input type="radio" id="n_agd_4" name="n_agd" value="c" onclick="fnjs_otro(1);" <?= $c ?> ><?= ucfirst(_("otro..."))?></td>
<td><span id="oro" class=etiqueta " ><?= $oDesplCentros->desplegable(); ?></span></td>

</tbody>
</table>
<?= $oFormP->getHtml(); ?>
<table>
<tfoot>
<tr>
	<th colspan=6><input type="button" id="ok" name="ok" onclick="fnjs_buscar('#modifica');" value="<?= ucfirst(_("buscar")) ?>">
	<input TYPE="reset" value="<?= ucfirst(_("borrar")) ?>"></th>
</tr>
</tfoot>
</table>
