<script>
<?php
if (core\configGlobal::is_app_installed('actividadplazas')) {
?>
fnjs_cmb_plaza=function(formulario,plaza){
	var form=$(formulario).attr('id');
	//var lista_json=$('#'+form+' input.sel:checked');
	var lista_json=JSON.stringify($('#'+form+' input.sel:checked').serializeArray());
	var url='apps/asistentes/controller/update_3101.php';
	var parametros='mod=plaza&plaza='+plaza+'&lista_json='+lista_json+'&id_activ=<?= $id_pau ?><?= $h4 ?>';
	$(formulario).one("submit", function() {
		$.ajax({
			url: url,
			type: 'post',
			data: parametros
		})
		.done(function (rta_txt) {
			if (rta_txt != '' && rta_txt != '\n') {
				alert (rta_txt);
			} else {
				fnjs_actualizar(formulario);
			}
		});
		return false;
	});
	$(formulario).trigger("submit");
	$(formulario).off();
}
<?php	
}
?>
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$(formulario).attr('action',"apps/dossiers/controller/dossiers_ver.php");
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}
fnjs_mover_guardar=function(formulario){
	var err=0;
	//$(formulario+' input[name="que"]').val(que);
	//$(formulario).attr('action','programas/casa_ajax.php');
	$(formulario).one("submit", function() {
		$.ajax({
			url: $(this).attr('action'),
			type: 'post',
			data: $(this).serialize()
		})
		.done(function (rta_txt) {
			if (rta_txt != '' && rta_txt != '\n') {
				alert (rta_txt);
			} else {
				$('#div_modificar').html('');
				$('#div_modificar').width('0');
				$('#div_modificar').height('0');
				$('#div_modificar').removeClass('ventana');
			}
			// OJO hay que actualizar el formulario de la lista, no el de mover.
			fnjs_actualizar("#frm_3101");
		});
		return false;
	});
	$(formulario).trigger("submit");
	$(formulario).off();
}
fnjs_mover=function(formulario,id_activ){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		$('#div_modificar').addClass('ventana');
		$('#div_modificar').width('800');
		$('#div_modificar').height('220');
 		document.getElementById("overlay").style.display = "block";
 
		var form=$(formulario).attr('id');
		/* selecciono los elementos con class="sel" de las tablas del id=formulario */
		var sel=$('#'+form+' input.sel:checked');
		id_pau = sel.val();
		var url='apps/asistentes/controller/form_mover.php';
		var parametros='id_pau='+id_pau+'&id_activ='+id_activ+"<?= $h3 ?>";
		fnjs_update_div('#div_modificar',url+'?'+parametros);
	}
}
fnjs_mover_cerrar=function(){
	$('#div_modificar').html('');
	$('#div_modificar').width('0');
	$('#div_modificar').height('0');
	$('#div_modificar').removeClass('ventana');
	document.getElementById("overlay").style.display = "none";
}

fnjs_e43=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
  		$(formulario).attr('action',"apps/actividadestudios/controller/e43.php");
  		fnjs_enviar_formulario(formulario,'<?= $bloque ?>');
  	}
}
fnjs_matriculas=function(frm_sel,frm_enviar){
	rta=fnjs_solo_uno(frm_sel);
	if (rta==1) {
		var form=$(frm_sel).attr('id');
		/* selecciono los elementos con class="sel" de las tablas del id=formulario */
		var sel=$('#'+form+' input.sel:checked');
		var id = sel.val();
		$('#sel2').val(id);
        $('#mod2').val("sel_es_asistente");
  		$(frm_enviar).attr('action',"apps/dossiers/controller/dossiers_ver.php");
  		fnjs_enviar_formulario(frm_enviar,'#main');
  	}
}
fnjs_modificar=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		$('#mod').val("editar");
  		$(formulario).attr('action',"apps/asistentes/controller/form_3101.php");
  		fnjs_enviar_formulario(formulario,'<?= $bloque ?>');
  	}
}

fnjs_mod_cargo=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		$('#mod').val("editar");
  		$(formulario).attr('action',"apps/actividadcargos/controller/form_3102.php");
  		fnjs_enviar_formulario(formulario,'<?= $bloque ?>');
  	}
}
fnjs_add_cargo=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		$('#mod').val("nuevo");
  		$(formulario).attr('action',"apps/actividadcargos/controller/form_3102.php");
  		fnjs_enviar_formulario(formulario,'<?= $bloque ?>');
  	}
}
fnjs_borrar=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= $txt_eliminar ?>") ) {
			$('#mod').val("eliminar");
			$(formulario).attr('action',"apps/asistentes/controller/update_3101.php");
			$(formulario).one("submit", function() {
				$.ajax({
					url: $(this).attr('action'),
					type: 'post',
					data: $(this).serialize()
				})
				.done(function (rta_txt) {
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					} else {
						fnjs_actualizar(formulario);
					}
				});
				return false;
			});
			$(formulario).trigger("submit");
			$(formulario).off();
		}
	}
}
fnjs_borrar_cargo=function(formulario){
	var asis="test";
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= _("¿Está seguro que desea quitar este cargo a esta persona?");?>") ) {
			$('#mod').val("eliminar");
			$(formulario).attr('action',"apps/actividadcargos/controller/update_3102.php");
			$(formulario).one("submit", function() {
				$.ajax({
					url: $(this).attr('action'),
					type: 'post',
					data: $(this).serialize()
				})
				.done(function (rta_txt) {
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					} else { 
						fnjs_actualizar(formulario);
					}
				});
				return false;
			});
			$(formulario).trigger("submit");
			$(formulario).off();
		}
	}
}
fnjs_transferir=function(formulario){
	if (confirm("<?= _("¿Está seguro que desea transferir todas las personas seleccionadas a históricos?");?>") ) {
			$(formulario).attr('action',"apps/dossiers/historics_insert.php?");
	  		fnjs_enviar_formulario(formulario,'<?= $bloque ?>');
	}
}

</script>
<!--div_mofificar para mostrar un popup para realizar cambios-->
<div id='div_modificar'></div>
<div id='overlay'></div>
<?= $msg_err ?>
<h2 class=titulo><?= ucfirst(_("relación de asistentes")); ?></h2>
<form id="frm_3101" name="frm_3101" action="" method="post">
<?= $oHash->getCamposHtml(); ?>
<input type='hidden' id='mod' name='mod' value=''>
<?= $oTabla->mostrar_tabla(); ?>
<?= $plazas_txt ?>
<br><br>
<?= $resumen_plazas ?>
<br>
<?= $resumen_plazas2 ?>
<br>
<?= $leyenda_html ?>
</form>
<!-- formulario extra para enviar datos para el plan de estudios -->
<form id="frm_matriculas" name="frm_matriculas" action="" method="post">
<?= $oHash1->getCamposHtml(); ?>
<input type='hidden' id='mod2' name='mod' value=''>
<input type='hidden' id='sel2' name='sel[]' value=''>
</form>
<?php
// --------------  boton insert ----------------------
if (!empty($aLinks_dl)) { ?>
	<br><table cellspacing=3  class="botones"><tr class="botones"><th width=25 align=RIGHT><?= _("dl") ?>:</th>
	<?php foreach ($aLinks_dl as $nom => $pagina) { ?>
	<td class="botones"><span class=link_inv onclick="fnjs_update_div('<?= $bloque ?>','<?= $pagina ?>');"><?= $nom ?></span></td>
	<?php } ?>
	</tr></table>
<?php } ?>
