<script>
    fnjs_cerrar = function () {
        $('#div_modificar').html('');
        $('#div_modificar').width('0');
        $('#div_modificar').height('0');
        $('#div_modificar').removeClass('ventana');
        document.getElementById("overlay").style.display = "none";
    }

    fnjs_guardar = function (formulario, que) {
        var err = 0;
        if (que == "eliminar") {
            seguro = confirm(<?= json_encode(_("¿Está seguro de borrar este periodo?")) ?>);
            if (seguro) {
                err = 0;
            } else {
                err = 1;
            }
        }
        if (err != 1) {
            var url = (que === 'eliminar') ? '<?= $url_eliminar ?>' : '<?= $url_guardar ?>';
            $.ajax({
                url: url,
                type: 'post',
                data: $(formulario).serialize(),
                dataType: 'json'
            })
                .done(function (rta) {
                    if (rta.success !== true) {
                        alert(rta.mensaje || '');
                    } else {
                        $('#div_modificar').html('');
                        $('#div_modificar').width('0');
                        $('#div_modificar').height('0');
                        $('#div_modificar').removeClass('ventana');
                    }
                    fnjs_ver();
                });
        }
    }

    fnjs_modificar = function (id_item) {
        $('#div_modificar').addClass('ventana');
        $('#div_modificar').width('auto');
        $('#div_modificar').height('auto');
        document.getElementById("overlay").style.display = "block";

        var url = id_item ? '<?= $url_form_periodo ?>' : '<?= $url_nuevo ?>';
        if (id_item) {
            var parametros = 'id_item=' + id_item + '<?= $h_modificar ?>';
        } else {
            id_ubi = $('#id_cdc').val();
            year = $('#year').val();
            var parametros = 'id_ubi=' + id_ubi + '&year=' + year + '<?= $h_nuevo ?>';
        }
        fnjs_update_div('#div_modificar', url + '?' + parametros);
    }

    fnjs_ver = function () {
        id_ubi = $('#id_cdc').val();
        year = $('#year').val();
        // obtener el listado de periodos
        var url = '<?= $url_get2 ?>';
        var parametros = 'id_ubi=' + id_ubi + '&year=' + year + '<?= $h_ver ?>';

        fnjs_ajax_json_html({
            url: url,
            data: parametros,
            target: '#ficha',
            onDone: function () {
                document.getElementById("overlay").style.display = "none";
            }
        });
    }

    $(document).ready(fnjs_ver);
</script>
<form name=seleccion action="">
    <?= $oForm->getDesplCasas()->desplegable(); ?>
    <?= $oFormAny->getDesplAnys()->desplegable(); ?>
    <input type=button name="buscar" value="<?= _("buscar") ?>" onclick="fnjs_ver()">
</form>
<div id='ficha'></div>
<div id='div_modificar'></div>
<div id='overlay'></div>
