<script>
    fnjs_guardar = function (formulario) {
        $('#que').val('ubi');
        $(formulario).attr('action', "frontend/ubis/controller/ubis_update.php");
        $(formulario).one("submit", function () {
            $.ajax({
                url: $(this).attr('action'),
                type: 'post',
                data: $(this).serialize()
            })
                .done(function (rta_txt) {
                    if (rta_txt !== '' && rta_txt !== '\n') {
                        alert(<?= json_encode(_("respuesta") . ": ") ?> + rta_txt);
                    } else {
                        <?= $oPosicion->js_atras(1); ?>
                    }
                });
            return false;
        });
        $(formulario).trigger("submit");
        $(formulario).off();
    }
    fnjs_eliminar = function (formulario) {
        if (confirm(<?= json_encode(_("¿Está seguro que desea borrar este centro?")) ?>)) {
            $('#que').val('eliminar_ubi');
            $(formulario).attr('action', 'frontend/ubis/controller/ubis_eliminar.php');
            $(formulario).one("submit", function () {
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'post',
                    data: $(this).serialize()
                })
                    .done(function (rta_txt) {
                        if (rta_txt !== '' && rta_txt !== '\n') {
                            alert(<?= json_encode(_("respuesta") . ": ") ?> + rta_txt);
                        } else {
                            <?= $oPosicion->js_atras(2); ?>
                        }
                    });
                return false;
            });
            $(formulario).trigger("submit");
            $(formulario).off();
        }
    }
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<form id='frm2'>
    <?= $oHash->getCamposHtml(); ?>
    <input type="Hidden" id="que" name="que" value="">
    <table>
        <tr>
            <td class="etiqueta">
                <!-- <?= ucfirst(_("tipo de ubi")) ?> -->
                <input type="hidden" class="contenido" id="tipo_ubi" name="tipo_ubi" value="<?= $tipo_ubi ?>" size="5">
                <?= ucfirst(_("región o delegación")) ?>
                <?php $_d = \web\Desplegable::desdeOpciones($opciones_dl, 'dl'); $_d->setOpcion_sel($dl); echo $_d->desplegable(); ?>
                <?= ucfirst(_("en uso")) ?><input class="contenido" type="Checkbox" name="status" <?= $chk ?>>
                <?= ucfirst(_("región")) ?>
                <?php $_d = \web\Desplegable::desdeOpciones($opciones_region, 'region'); $_d->setOpcion_sel($region); echo $_d->desplegable(); ?>
            </td>
        </tr>
        <tr>
            <td class="etiqueta">
                <?= ucfirst(_("nombre del centro")) ?><input class="contenido" name="nombre_ubi" size="35"
                                                             value="<?= $nombre_ubi ?>">
                <?= ucfirst(_("¿puede ser cdc?")) ?><input class="contenido" type="Checkbox" name="cdc" <?= $chk_cdc ?>>
            </td>
        </TR>
        <tr>
            <td>
                <?= ucfirst(_("tipo de centro")) ?>
                <?php $_d = \web\Desplegable::desdeOpciones($opciones_tipo_ctr, 'tipo_ctr'); $_d->setOpcion_sel($tipo_ctr); echo $_d->desplegable(); ?>
            </td>
        </tr>
        <tr>
            <td class="etiqueta">
                <?= ucfirst(_("tipo de labor")) ?></td>
        </tr>
        <tr>
            <td>
                <?= $oPermActiv->cuadros_check("tipo_labor", $tipo_labor); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?= ucfirst(_("centro padre")) ?>
                <?php $_d = \web\Desplegable::desdeOpciones($opciones_id_ctr_padre, 'id_ctr_padre'); $_d->setOpcion_sel($id_ctr_padre); echo $_d->desplegable(); ?>
            </td>
        </tr>
    </table>
    <?php
    // -----------------------------------  Botones  ----------------------
    if (!empty($botones)) {
        echo "<table><tr class=botones>";
        $b = strtok($botones, ",");
        while ($b) {
            if ($b == 1) {
                $txt_g = ucwords(_("guardar cambios"));
                echo "<th class='link_inv' onclick=\"fnjs_guardar('#frm2');\">$txt_g</th>";
            }
            if ($b == 2) {
                $txt_e = ucwords(_("eliminar"));
                echo "<th class='link_inv' onclick=\"fnjs_eliminar('#frm2');\">$txt_e</th>";
            }
            $b = strtok(",");
        }
        echo "</tr></table><br>";
    }
    // fin ----------------------------  Botones  ----------------------
    ?>
</form>
