<h3><?= _("Traladar a") ?>:</h3>
<?= $oDesplDelegaciones->desplegable() ?>
<br><br>
<input type="button" onclick="fnjs_cerrar()" value="<?= _("Cancelar") ?>" />
<input type="button" onclick="fnjs_trasladar()" value="<?= _("Trasladar") ?>" />

<script>
/* pone el id de la dl en el campo hidden del formulario */
fnjs_cmb_id_dl=function(){
    var dl = $('#dl_destino').val();
    $('#dl_dst').val(dl)
}
</script>
