<?php
use frontend\shared\web\Desplegable;
?>
<h3><?= _("Traladar a") ?>:</h3>
<?php $_d = Desplegable::desdeOpciones($opciones_dl_destino, 'dl_destino'); $_d->setAction("fnjs_cmb_id_dl()"); echo $_d->desplegable(); ?>
<br><br>
<input type="button" onclick="fnjs_cerrar()" value="<?= _("Cancelar") ?>" />
<input type="button" onclick="fnjs_trasladar()" value="<?= _("Trasladar") ?>" />

<script>
/* pone el id de la dl en el campo hidden del formulario */
fnjs_cmb_id_dl=function(){
    var dl = $('#dl_destino').val();
    $('#dl_dst').val(dl)
}
</script>
