<script>
    fnjs_guardar = function (formulario) {
        fnjs_ajax_json({
            url: '<?= $url_guardar ?>',
            data: $(formulario).serialize(),
            onSuccess: function () {
                <?= $oPosicion->jsNavAtras(1) ?>
            }
        });
    }
    fnjs_actualizar_descripcion = function () {
        var id_tipo_teleco = $('#id_tipo_teleco').val();
        var parametros = 'id_tipo_teleco=' + id_tipo_teleco;
        fnjs_ajax_json_html({ url: '<?= $url_actualizar ?>', data: parametros, target: '#span_descripcion' });
    }
</script>
<?= $oPosicion->mostrarNavAtras(1); ?>
<form id='frm2'>
    <?= $oHash->getCamposHtml(); ?>
    <input type="Hidden" id="mod" name="mod" value="">
    <table>
        <tr><td class="etiqueta"><?= ucfirst(_("tipo teleco")) ?><?= $oDesplegableTiposTeleco->desplegable(); ?></td></tr>
        <tr><td class="etiqueta"><?= ucfirst(_("descripción")) ?><span id='span_descripcion'><?= $oDesplegableDescTeleco->desplegable(); ?></span></td></tr>
        <tr><td class="etiqueta"><?= ucfirst(_("número")) ?><input class="contenido" id="num_teleco" name="num_teleco" value="<?= $num_teleco ?>" size="30"></td></tr>
        <tr><td class="etiqueta"><?= ucfirst(_("observaciones")) ?><input class="contenido" id="observ" name="observ" value="<?= $observ ?>" size="50"></td></tr>
    </table>
    <?php if (!empty($botones)) { ?>
        <table><tr class=botones><th class='link_inv' onclick='fnjs_guardar("#frm2")'><?= ucwords(_("guardar cambios")) ?></th></tr></table><br>
    <?php } ?>
</form>
