<script>
    fnjs_nuevo = function (formulario) {
        $('#mod').val("nuevo");
        $(formulario).attr('action', "<?= $url_editar ?>");
        fnjs_enviar_formulario(formulario, '#<?= $ficha ?>');
    }
    fnjs_modificar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#mod').val("editar");
            $(formulario).attr('action', "<?= $url_editar ?>");
            fnjs_enviar_formulario(formulario, '#<?= $ficha ?>');
        }
    }
    fnjs_eliminar = function (formulario) {
        var eliminar = <?= json_encode(_("¿Está seguro que desea eliminar este registro?")) ?>;
        rta = fnjs_solo_uno(formulario);
        if (rta == 1 && confirm(eliminar)) {
            let datos = $(formulario).serialize();
            let request = $.ajax({
                url: '<?= $url_eliminar ?>',
                type: 'post',
                data: datos
            });
            request.done(function (json) {
                if (json.success !== true) {
                    alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
                } else {
                    fnjs_actualizar(formulario);
                }
            });
        }
    }
    fnjs_actualizar = function (formulario) {
        var campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "<?= $url_tabla ?>");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#<?= $ficha ?>');
    }
</script>
<?= $oPosicion->mostrarNavAtras(1); ?>
<h3 class=subtitulo><?= ucfirst($tit_txt) ?></h3>
<form id='seleccionados' name='seleccionados' action='' method='post'>
    <?= $oHash->getCamposHtml(); ?>
    <input type="hidden" id="mod" name="mod" value="">
    <?= $oTabla->mostrar_tabla(); ?>
    <?php if ($botones == 1) { ?>
        <br>
        <table cellspacing=3 class=botones><tr class=botones>
            <td class=botones><input name="btn_new" type="button" value="<?= _("nuevo") ?>" onclick="fnjs_nuevo('#seleccionados');"></td>
        </tr></table>
    <?php } ?>
</form>
