<script>
fnjs_comparativa=function(){
	var filtro_dl=$('#dl').val();
	var url='<?= core\ConfigGlobal::getWeb().'/apps/actividadplazas/controller/plazas_balance_dl.php' ?>';
	var parametros='id_tipo_activ=<?= $Qid_tipo_activ ?>&dl='+filtro_dl+'<?= $h ?>';
	$.ajax({
		data: parametros,
		url: url,
		type: 'post',
		dataType: 'html',
		complete: function (rta) {
			rta_txt=rta.responseText;
			$('#comparativa').html(rta_txt);
		}
	});
}
</script>
<div id='select_dl'>
<?= $txt ?>
	<?= $desplDelegaciones->desplegable(); ?>
</div>
<br>
<div id='comparativa'></div>