<script>
fnjs_guardar=function(formulario){
	$('#que').value = 'ceder';
	$(formulario).attr('action',"apps/actividadplazas/controller/resumen_plazas_update.php");
	$(formulario).submit(function() {
		$.ajax({
			data: $(this).serialize(),
			url: $(this).attr('action'),
			type: 'post',
			complete: function (rta) { 
				rta_txt=rta.responseText;
				if (rta_txt != '' && rta_txt != '\n') {
					alert (rta_txt);
				}
			},
			success: function() { fnjs_actualizar('#frm_actualizar') }
		});
		return false;
	});
	$(formulario).submit();
	$(formulario).off();
}
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$('#frm_actualizar').attr('action','apps/actividadplazas/controller/resumen_plazas.php');
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<form id='frm_actualizar'>
	<?= $oHashActualizar->getCamposHtml(); ?>
</form>
<form id="frm_resumen" name="frm_resumen" action="" method="POST">
<?= $oHash->getCamposHtml(); ?>
<?= $nom_activ ?>
<?php if (empty($publicado)) { ?>
	<span class="alert"><?= _("OJO! Esta actividad no está publicada") ?></span>
<?php } ?>
<table border="1">
	<tr><td>dl</td><td colspan="4">plazas</td><td>ocupadas</td><td>libres</td></tr>
	<tr><td></td><td>calendario</td><td>cedidas</td><td>conseguidas</td><td>total</td><td></td><td></td></tr>
	<?php
	//plazas
	$d = 0;
	foreach ($a_plazas as $dl=>$pl) {
		if ($dl == 'total') { continue; }
		// evitar errores si no existe el indice.
		$pl['calendario'] = empty($pl['calendario'])? '-' : $pl['calendario'];
		$pl['total_cedidas'] = empty($pl['total_cedidas'])? '-' : $pl['total_cedidas'];
		$pl['total_conseguidas'] = empty($pl['total_conseguidas'])? '-' : $pl['total_conseguidas'];
		$pl['total_actual'] = empty($pl['total_actual'])? '-' : $pl['total_actual'];
		$pl['ocupadas'] = empty($pl['ocupadas'])? '-' : $pl['ocupadas'];
		
		$d++;
		$clase = "tono$d";
		echo "<tr class='$clase'>";
		echo "<td>".$dl."</td><td>".$pl['calendario']."</td>";
		echo "<td>".$pl['total_cedidas']."</td>";
		echo "<td>".$pl['total_conseguidas']."</td>";
		echo "<td>".$pl['total_actual']."</td>";
		echo "<td>".$pl['ocupadas']."</td>";
		echo "<td></td>";
		echo "</tr>";
		if (!empty($pl['cedidas'])){
			$aCedidas = $pl['cedidas'];
			foreach ($aCedidas as $dl_otra=>$num_plazas){
				echo "<tr class='$clase'><td></td><td></td><td>$num_plazas a $dl_otra</td>";
				if (!array_key_exists($dl_otra,$a_plazas)) {
					echo "<td></td><td>$num_plazas</td>";
					$ocupadas = empty($a_plazas[$dl][$dl_otra]['ocupadas'])? 0 : $a_plazas[$dl][$dl_otra]['ocupadas'];
					echo "<td>$ocupadas</td><td></td></tr>";
				} else {
					echo "<td></td><td></td>";
					echo "<td></td><td></td></tr>";
				}
				echo "</tr>";
			}
		}
		if (!empty($pl['conseguidas'])){
			$aCedidas = $pl['conseguidas'];
			foreach ($aCedidas as $dl_otra=>$num_plazas){
				echo "<tr class='$clase'><td></td><td></td><td></td><td>$num_plazas de $dl_otra</td>";
				echo "<td></td><td></td><td></td></tr>";
			}
		} else {
			echo "<tr class='$clase'><td></td><td></td><td></td><td></td>";
			echo "<td></td><td></td><td></td></tr>";
		}
	}
	// TOTALES
	echo "<tr>";
	echo "<td>"._("totales")."</td><td>$tot_calendario ($plazas_totales)</td>";
	echo "<td>".$tot_cedidas."</td>";
	echo "<td>".$tot_conseguidas."</td>";
	echo "<td>".$tot_actual."</td>";
	echo "<td>".$tot_ocupadas."</td>";
	echo "<td></td>";
	echo "</tr>";

	
	?>
</table>

<br><br>
<form id="ceder">
ceder 
<input name="num_plazas" type="text" size="3" />
plazas a 
<?= $oDesplDelegaciones->desplegable() ?>
<input type="button" id="ok" name="ok" onclick="fnjs_guardar(this.form);" value="<?= ucfirst(_("guardar")); ?>" align="MIDDLE" />
</form>