<script>
fnjs_modificar=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
  		$(formulario).attr('action',"apps/ubis/controller/home_ubis.php");
  		fnjs_enviar_formulario(formulario);
  	}
}
fnjs_borrar=function(formulario){
	var seguro;
	seguro=confirm("<?= _("¿Está seguro que desea borrar este ubi?");?>");
	if (seguro) {
		$(formulario).one("submit", function() {
			$.ajax({
				url: $(this).attr('action'),
				type: 'post',
				data: $(this).serialize()
			})
			.done(function (rta_txt) {
				if (rta_txt != '' && rta_txt != '\n') {
					alert (rta_txt);
				}
			});
			return false;
		});
		$(formulario).trigger("submit");
		$(formulario).off();
	}
}

</script>
<form id="seleccionados" name="seleccionados" action="" method="post">
<?= $oHash->getCamposHtml(); ?>
<h2 class=titulo><?= $titulo; ?></h2>
<?= $oTabla->mostrar_tabla(); ?>
</form>
