<script>
fnjs_buscar=function(formulario){
	var form_name=$(formulario).attr('name');
	var opcion=form_name.substr(-1);
	fnjs_ver_solo(formulario);
	// borro los posibles resultados anteriores
	$('#resultados').html("");
	$(formulario+" opcion").val(opcion);
	<?php if ($tipo=="mail") { ?>
		$(formulario).attr('action','scdl/tabla_mails.php');
	<?php } else { ?>
		$(formulario).attr('action','apps/ubis/controller/ubis_tabla.php');
	<?php } ?>
	fnjs_enviar_formulario(formulario,'#main');
}
fnjs_ver_solo=function(formulario){
	// colección de todos los formularios
	$('#condiciones form').each(function(i,f){
		$(this).hide();
	});
	$(formulario).show();
}

fnjs_actualizar=function(formulario){
	$(formulario).attr('action','apps/ubis/controller/ubis_buscar.php');
	fnjs_enviar_formulario(formulario,'#condiciones');
}
fnjs_left_side_hide();
<?php 
if ($simple==1) {
	?>
	fnjs_ver_solo('#frm_buscar_1');
	<?php
}
if ($simple==2) {
	?>
	fnjs_ver_solo('#frm_buscar_2');
	<?php
}
?>
</script>
<div id="condiciones">
<form id="frm_buscar_1" name="frm_buscar_1" action="" onkeypress="fnjs_enviar(event,this);" >
<?= $oHash->getCamposHtml(); ?>
<input type="hidden" name="opcion" value="">
<input type="hidden" name="simple" value="1">
<!-- Búsqueda simple --------------------------------------------- -->
<table border=1>
<thead><th class=titulo_inv colspan=4><?= ucfirst(_("buscar centro o casa")); ?></th>
</thead>
<tfoot>
<tr>
<td class=etiqueta align="RIGHT"><input type="checkbox" name="cmb"><?= _("buscar ubis fuera de uso"); ?></td>
<td colspan=5 style="text-align:right;">
<input id="ok" name="ok" TYPE="button" VALUE="<?= _("buscar"); ?>" onclick="fnjs_buscar('#frm_buscar_1')"  class="btn_ok" ></td></tr>
</tfoot>
<tbody>
<tr>
	<td class=etiqueta><?= $nomUbi ?></td>
	<td colspan="4"><input class=contenido id=nombre_ubi name=nombre_ubi size="60"></td>
</tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("población")); ?></td>
	<td colspan="4"><input class=contenido id=ciudad name=ciudad size="60"></td>	
</tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("región")); ?></td>
	<td><?= $oDesplRegion->desplegable(); ?></td>
</tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("país")); ?></td>
	<td><?= $oDesplPais->desplegable(); ?></td>
</tr>

<?php
if ($tipo=="mail") { ?>
<table align="justify">
<tr></tr>
<tr>
<td class=subtitulo><?= _("tipo de centro"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="a"><?= _("agd"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="aj"><?= _("agd jóvenes"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="am"><?= _("agd mayores"); ?></td>
<td colspan="3" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="n"><?= _("numerarios"); ?>
<input type="Checkbox" id="select[]" name="select[]" value="nj"><?= _("n jóvenes"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="nm"><?= _("n mayores"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="rs"><?= _("residencia"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="sg"><?= _("san Gabriel"); ?></td>
<td colspan="2" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="ce"><?= _("centro de estudios"); ?></td>
</tr>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="oc"><?= _("obra corporativa"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="igl"><?= _("iglesia"); ?></td>
<td colspan="1" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="cefi"><?= _("ce de formación intensa"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="ss"><?= _("sss+"); ?></td>
</tr>
<tr>
<td colspan="1" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="cipna"><?= _("centro internacional"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="lp"><?= _("labor personal"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="cr"><?= _("comisiones"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="dl"><?= _("delegaciones"); ?></td>
</tr>
<tr>
<td class=subtitulo><?= _("tipo de labor"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="512"><?= _("sr"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="256"><?= _("n"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="128"><?= _("agd"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="64"><?= _("sg"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="32"><?= _("sss+"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="16"><?= _("club"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="8"><?= _("bachilleres"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="4"><?= _("universitarios"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="2"><?= _("jóvenes"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="1"><?= _("mayores"); ?></td>
</tr>
</table>
<?php } ?>
</tbody></table>
</form>

<!-- más opciones --------------------------------------------- -->
<form id="frm_buscar_2" name="frm_buscar_2" action="" onkeypress="fnjs_enviar(event,this);" >
<?= $oHash->getCamposHtml(); ?>
<input type="hidden" name="opcion" value="">
<input type="hidden" name="simple" value="2">
<table border=1>
<thead><th class=titulo_inv colspan=4><?= ucfirst(_("buscar centro o casa")); ?></th></thead>
<tfoot>
<tr><td colspan=5 style="text-align:right;"><input id="b_buscar_2" name="b_buscar" TYPE="button" VALUE="<?= _("buscar"); ?>" onclick="fnjs_buscar('#frm_buscar_2')" class="btn_ok"></td></tr>
</tfoot>
<tbody>
<tr><td class=etiqueta>
<?= ucfirst(_("tipo")); ?>
</td><td>
<select id="tipo" name="tipo" onchange="fnjs_actualizar('#frm_buscar_2')" class=contenido>
<?php 
	if ($tipo=="ctr") { $ctr_selected="selected"; } else { $ctr_selected=""; }
	if ($tipo=="cdc") { $cdc_selected="selected"; } else { $cdc_selected=""; }
	if ($tipo=="tot") { $tot_selected="selected"; } else { $tot_selected=""; }
	echo "<option value='ctr' $ctr_selected>".ucfirst(_("centro"));
	echo "<option value='cdc' $cdc_selected>".ucfirst(_("casa")); 
	echo "<option value='tot' $tot_selected>".ucfirst(_("todos")); ?>
	</select>
</td><td>
<?= ucfirst(_("localización")); ?>
</td><td>
<select id="loc" name="loc" onchange="fnjs_actualizar('#frm_buscar_2')" class=contenido>
	<?php
	if ($loc=="dl") { $dl_selected="selected"; } else { $dl_selected=""; }
	if ($loc=="ex") { $ex_selected="selected"; } else { $ex_selected=""; }
	if ($loc=="tot") { $to_selected="selected"; } else { $to_selected=""; }
	echo "<option value='dl' $dl_selected>"._("de la propia r/dl");
	echo "<option value='ex' $ex_selected>"._("de otra r/dl");
	echo "<option value='tot' $to_selected>"._("todos"); 
	?>
</select>
</td></tr>
<tr>
	<td class=etiqueta><?= $nomUbi ?></td>
	<td colspan="4"><input class=contenido id=nombre_ubi name=nombre_ubi size="60"></td>
</tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("población")); ?></td>
	<td colspan="4"><input class=contenido id=ciudad name=ciudad size="60"></td>	
</tr>

<?php if ($loc=="ex") { ?>
	<tr>
		<td class=etiqueta><?= _("dl"); ?></td>
		<td><input class=contenido id=dl name=dl size=1  style="HEIGHT: 22px; WIDTH: 62px"></td> 
		<td class=etiqueta><?= ucfirst(_("región")); ?></td>
		<td><input class=contenido id=region name=region size=1 style="HEIGHT: 22px; WIDTH: 62px"></td> 
	</tr>
	<tr>
		<td class=etiqueta><?= ucfirst(_("país")); ?></td>
		<td colspan="4"><input class=contenido id=pais name=pais size=1 style="HEIGHT: 22px; WIDTH: 250px"></td>
	</tr>
	<?php

	if ($tipo=="ctr" ) {
	?>
		<tr><td class=etiqueta><?= _("tipo de centro"); ?></td>
		<td><?= $oDesplTipoCentro->desplegable(); ?>
		</td></tr>
	<?php
	}
	if ($tipo=="cdc" ) {
	?>
		<tr><td class=etiqueta><?= _("tipo de casa"); ?></td>
		<td><?= $oDesplTipoCasa->desplegable(); ?>
		</td></tr>
	<?php	
	}
}

if ($tipo=="mail") { ?>
<table align="justify">
<tr></tr>
<tr></tr>
<tr>
<td class=subtitulo><?= _("tipo de centro"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="a"><?= _("agd"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="aj"><?= _("agd jóvenes"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="am"><?= _("agd mayores"); ?></td>
<td colspan="3" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="n"><?= _("numerarios"); ?>
<input type="Checkbox" id="select[]" name="select[]" value="nj"><?= _("n jóvenes"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="nm"><?= _("n mayores"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="rs"><?= _("residencia"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="sg"><?= _("san Gabriel"); ?></td>
<td colspan="2" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="ce"><?= _("centro de estudios"); ?></td>
</tr>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="oc"><?= _("obra corporativa"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="igl"><?= _("iglesia"); ?></td>
<td colspan="1" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="cefi"><?= _("ce de formación intensa"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="ss"><?= _("sss+"); ?></td>
</tr>
<tr>
<td colspan="1" class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="cipna"><?= _("centro internacional"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="lp"><?= _("labor personal"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="cr"><?= _("comisiones"); ?></td>
<td class=etiqueta><input type="Checkbox" id="select[]" name="select[]" value="dl"><?= _("delegaciones"); ?></td>
</tr>
<tr>
<td class=subtitulo><?= _("tipo de labor"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="512"><?= _("sr"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="256"><?= _("n"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="128"><?= _("agd"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="64"><?= _("sg"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="32"><?= _("sss+"); ?></td>
</tr>
<tr>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="16"><?= _("club"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="8"><?= _("bachilleres"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="4"><?= _("universitarios"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="2"><?= _("jóvenes"); ?></td>
<td class=etiqueta><input type="Checkbox" id="labor[]" name="labor[]" value="1"><?= _("mayores"); ?></td>
</tr>
</table>
<?php
}
?>
</tbody></table>
</form>
<td><input id="b_mas" name="b_mas" TYPE="button" VALUE="<?= _("ver otras opciones"); ?>" onclick="fnjs_update_div('#main','<?= $pagina ?>')" ></td>
</table>
</div>
<div id="resultados">
</div>