<script>
    fnjs_guardar = function (formulario) {
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: '<?= $url_guardar ?>',
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->js_atras(1); ?>
            }
        });
    }
</script>
<?= $oPosicion->mostrar_left_slide(1) ?>
<h2><?= $nombreDoc ?></h2>
<form id="seleccionados" name="seleccionados" action="" method="POST">
    <?= $oHash->getCamposHtml() ?>
    <?= $oTabla->mostrar_tabla_html() ?>
    <br>
    <script>
        $(function () {
            $("#f_recibido").datepicker();
        });
        $(function () {
            $("#f_asignado").datepicker();
        });
    </script>
    <?= _("recibido") ?> <input type=text id="f_recibido" name="f_recibido" size="12" value="" class=contenido
                                title="dd/mm/aa">
    <?= _("asignado") ?> <input type=text id="f_asignado" name="f_asignado" size="12" value="" class=contenido
                                title="dd/mm/aa">
    <input type="button" id="okay" name="okay" value="<?= _("guardar") ?>" onclick="fnjs_guardar('#seleccionados')">
</form>