<form id='frm_listado'>
    <?= $oHashForm->getCamposHtml() ?>
    <h3> <?= $titulo ?></h3>
    <textarea name='texto' cols=95 rows=5><?= $texto ?></textarea>
    <p id="frm_listado_error" class="error" style="display:none;color:#c00;font-weight:bold;margin:0.5em 0;"></p>
    <br>
    <input type="button" value="<?= _('guardar') ?>" onclick="fnjs_guardar_listado('#frm_listado');">
    <input type="button" value="<?= _('cancel') ?>" onclick="fnjs_cerrar();">
</form>