<h2 class="titulo"><?= _("copiar la tesera de") ?> <?= $nom ?></h2>
<form id="frm_sin_nombre" name="frm_sin_nombre" action="" method="POST">
    <?= $oHash->getCamposHtml() ?>
    <?= _("a") ?>
    <?= $oDesplPersonas->desplegable() ?>
    <br>
    <br>
    <input type="button" id="copiar" name="copiar" onclick="fnjs_copiar('#frm_sin_nombre');"
           value="<?= _("copiar") ?>">
</form>
<script>
    fnjs_copiar = function (formulario) {
        let request = $.ajax({
            data: $(formulario).serialize(),
            url: '/src/notas/tessera_copiar',
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert(<?= json_encode(_("respuesta")) ?> + json.mensaje);
            } else {
                <?= $oPosicion->js_atras() ?>
            }
        });
    }
</script>
