<?php return array(
    'default' =>
        array(
            'datestyle' => 'ISO,YMD',
            'host' => 'localhost',
            'sslmode' => 'disable',
            'port' => 5444,
            'dbname' => 'comun',
            'sslcert' => '/home/orbix/conf/postgresql.crt',
            'sslkey' => '/home/orbix/conf/postgresql.key',
            'sslrootcert' => '/home/orbix/conf/root.crt',
            'ssh_user' => 'aquinate',
        ),
    'public' =>
        array(
            'user' => 'orbix',
            'password' => 'Q{R2MqVTq:v',
        ),
    'resto' =>
        array(
            'user' => 'orbix',
            'password' => 'Q{R2MqVTq:v',
        ),
    'A-crA' =>
        array(
            'user' => 'A-crA',
            'password' => 'jP/!)Pnn(41',
        ),
    'Acme-crAcme' =>
        array(
            'user' => 'Acme-crAcme',
            'password' => '5B{<oZ[}6:G',
        ),
    'Acse-crAcse' =>
        array(
            'user' => 'Acse-crAcse',
            'password' => 'oH=)VD3pBME',
        ),
    'H-H' =>
        array(
            'user' => 'H-H',
            'password' => 'D>Lf[OeIt*=',
        ),
    'H-crH' =>
        array(
            'user' => 'H-crH',
            'password' => 'qLby+)TF4OS',
        ),
    'H-dlgr' =>
        array(
            'user' => 'H-dlgr',
            'password' => 'nUkB3m5(+SI',
        ),
    'H-dlmE' =>
        array(
            'user' => 'H-dlmE',
            'password' => '%^sl|Z>!20%',
        ),
    'H-dlmO' =>
        array(
            'user' => 'H-dlmO',
            'password' => '?tK/GL9nb:K',
        ),
    'H-dlp' =>
        array(
            'user' => 'H-dlp',
            'password' => 'Q,2mP4QVo|k',
        ),
    'H-dls' =>
        array(
            'user' => 'H-dls',
            'password' => 'A?ML(3YV8C9',
        ),
    'H-dlst' =>
        array(
            'user' => 'H-dlst',
            'password' => ')cGeqTb<.]a',
        ),
    'H-dlv' =>
        array(
            'user' => 'H-dlv',
            'password' => 'fQ@OBpuGNzI',
        ),
    'H-dlz' =>
        array(
            'user' => 'H-dlz',
            'password' => 'i4?Q^}tg52m',
        ),
    'Crsl-crCrsl' =>
        array(
            'user' => 'Crsl-crCrsl',
            'password' => 'a5#}YpChT5W',
        ),
    'Iers-crIers' =>
        array(
            'user' => 'Iers-crIers',
            'password' => 'Mol(wpP!M8:',
        ),
    'Kz-crKz' =>
        array(
            'user' => 'Kz-crKz',
            'password' => 'J=s&{fP_WxV',
        ),
    'C-crC' =>
        array(
            'user' => 'C-crC',
            'password' => 'bPL1(6Dw?cP',
        ),
    'Ch-crCh' =>
        array(
            'user' => 'Ch-crCh',
            'password' => '2W>dU5G&Ag<',
        ),
    'I-crI' =>
        array(
            'user' => 'I-crI',
            'password' => 'a{Tp[hCJDtk',
        ),
    'Aut-crAut' =>
        array(
            'user' => 'Aut-crAut',
            'password' => '328S44vrV,P',
        ),
    'Nig-crNig' =>
        array(
            'user' => 'Nig-crNig',
            'password' => '{v+Gn)rKT46',
        ),
    'Eu-crEu' =>
        array(
            'user' => 'Eu-crEu',
            'password' => 't@haf+&B>Ap',
        ),
    'H-dlb' =>
        array(
            'user' => 'H-dlb',
            'password' => 'Tel7gLEH:yh',
        ),
    'H-dlal' =>
        array(
            'user' => 'H-dlal',
            'password' => 'xvu.Xc_!]S',
        ),
    'P-crP' =>
        array(
            'user' => 'P-crP',
            'password' => 'TmvYmRG=S?k',
        ),
    'M-crM' =>
        array(
            'user' => 'M-crM',
            'password' => 'gViW+Z&8*)f',
        ),
    'GalBel-crGalBel' =>
        array(
            'user' => 'GalBel-crGalBel',
            'password' => '.FPoZ|(V<rO',
        ),
    'L-crL' =>
        array(
            'user' => 'L-crL',
            'password' => ']CT<c4/?Z6V',
        ),
);
