<?php return array(
    'default' =>
        array(
            'datestyle' => 'ISO,YMD',
            'host' => 'localhost',
            'sslmode' => 'disable',
            'port' => 5444,
            'dbname' => 'sf',
            'ssh_user' => 'aquinate',
        ),
    'public' =>
        array(
            'user' => 'orbix',
            'password' => 'Q{R2MqVTq:v',
        ),
    'publicf' =>
        array(
            'user' => 'orbixf',
            'password' => '#7=b3p%vZP7',
        ),
    'restof' =>
        array(
            'user' => 'orbixf',
            'password' => '#7=b3p%vZP7',
        ),
    'H-Hf' =>
        array(
            'user' => 'H-Hf',
            'password' => 'o1MZUOQo[:T',
        ),
    'H-dlgrf' =>
        array(
            'user' => 'H-dlgrf',
            'password' => '*{fV53&u#7H',
        ),
    'H-dlmEf' =>
        array(
            'user' => 'H-dlmEf',
            'password' => '679kMPru.[y',
        ),
    'H-dlmOf' =>
        array(
            'user' => 'H-dlmOf',
            'password' => 'XBUq}u+Pj<e',
        ),
    'H-dlsf' =>
        array(
            'user' => 'H-dlsf',
            'password' => '8=ytuy^_(%W',
        ),
    'H-dlstf' =>
        array(
            'user' => 'H-dlstf',
            'password' => '.OQ:S&Ur.Pp',
        ),
    'H-dlvf' =>
        array(
            'user' => 'H-dlvf',
            'password' => 'kP<Q}D*3ab5',
        ),
    'H-dlvaf' =>
        array(
            'user' => 'H-dlvaf',
            'password' => '{O!b+w,}^i3',
        ),
    'H-dlzf' =>
        array(
            'user' => 'H-dlzf',
            'password' => 'PG#45pfz%C+',
        ),
    'Kz-crKzf' =>
        array(
            'user' => 'Kz-crKzf',
            'password' => 'y4>T34uW7Cm',
        ),
    'A-crAf' =>
        array(
            'user' => 'A-crAf',
            'password' => 'P9]+<hF(U@J',
        ),
    'Cro-crCrof' =>
        array(
            'user' => 'Cro-crCrof',
            'password' => ']=cRlCfdoUN',
        ),
    'H-dlalf' =>
        array(
            'user' => 'H-dlalf',
            'password' => '6!z82=lnD)Z',
        ),
    'H-dlbf' =>
        array(
            'user' => 'H-dlbf',
            'password' => '*{fV53&u#7H',
        ),
    'M-crMf' =>
        array(
            'user' => 'M-crMf',
            'password' => 'n(V*(RDy/?S',
        ),
    'L-crLf' =>
        array(
            'user' => 'L-crLf',
            'password' => '@]PBn|A&7PB',
        ),
);
