<?php return array(
    'default' =>
        array(
            'datestyle' => 'ISO,YMD',
            'host' => 'localhost',
            'sslmode' => 'disable',
            'port' => 5444,
            'dbname' => 'sv-e',
            'ssh_user' => 'aquinate',
        ),
    'public' =>
        array(
            'user' => 'orbix',
            'password' => 'Q{R2MqVTq:v',
        ),
    'publicv' =>
        array(
            'user' => 'orbixv',
            'password' => 'dy>yxuui[W9',
        ),
    'restov' =>
        array(
            'user' => 'orbixv',
            'password' => 'dy>yxuui[W9',
        ),
    'A-crAv' =>
        array(
            'user' => 'A-crAv',
            'password' => 'a,hgEEYY&b=',
        ),
    'Acme-crAcmev' =>
        array(
            'user' => 'Acme-crAcmev',
            'password' => 'tPl7cK3VqV<',
        ),
    'Acse-crAcsev' =>
        array(
            'user' => 'Acse-crAcsev',
            'password' => 'Pe+bR^i:>VL',
        ),
    'H-Hv' =>
        array(
            'user' => 'H-Hv',
            'password' => '&8?4g24=OC%',
        ),
    'H-crHv' =>
        array(
            'user' => 'H-crHv',
            'password' => ':yWhbnrBR2T',
        ),
    'H-dlbv' =>
        array(
            'user' => 'H-dlbv',
            'password' => 'NUxO[SD3G#X',
        ),
    'H-dlgrv' =>
        array(
            'user' => 'H-dlgrv',
            'password' => 'ZB^Ef#ce[M+',
        ),
    'H-dlmEv' =>
        array(
            'user' => 'H-dlmEv',
            'password' => 'fu*:LVn#Vi<',
        ),
    'H-dlmOv' =>
        array(
            'user' => 'H-dlmOv',
            'password' => '>h)+rc)[VdR',
        ),
    'H-dlpv' =>
        array(
            'user' => 'H-dlpv',
            'password' => 'jYfW=bQ#qCP',
        ),
    'H-dlsv' =>
        array(
            'user' => 'H-dlsv',
            'password' => 'dS((>u[mxX!',
        ),
    'H-dlstv' =>
        array(
            'user' => 'H-dlstv',
            'password' => 'd6PILFF<{xX',
        ),
    'H-dlvv' =>
        array(
            'user' => 'H-dlvv',
            'password' => 'gQ5Sl=&vY6V',
        ),
    'H-dlzv' =>
        array(
            'user' => 'H-dlzv',
            'password' => ']/M3)(W5W[*',
        ),
    'Crsl-crCrslv' =>
        array(
            'user' => 'Crsl-crCrslv',
            'password' => '%OI:acqDKZU',
        ),
    'Iers-crIersv' =>
        array(
            'user' => 'Iers-crIersv',
            'password' => 'CR|T,)MFBt6',
        ),
    'Kz-crKzv' =>
        array(
            'user' => 'Kz-crKzv',
            'password' => 'RKk8ce4>r_d',
        ),
    'C-crCv' =>
        array(
            'user' => 'C-crCv',
            'password' => 'IcCp/?+z#p|',
        ),
    'Ch-crChv' =>
        array(
            'user' => 'Ch-crChv',
            'password' => 'z|F]Vxd1lNh',
        ),
    'I-crIv' =>
        array(
            'user' => 'I-crIv',
            'password' => 'is3r(K>oqb5',
        ),
    'Aut-crAutv' =>
        array(
            'user' => 'Aut-crAutv',
            'password' => 'u7&kZQ:Js}|',
        ),
    'Nig-crNigv' =>
        array(
            'user' => 'Nig-crNigv',
            'password' => 'tI<k9|,q&K,',
        ),
    'Eu-crEuv' =>
        array(
            'user' => 'Eu-crEuv',
            'password' => 'LXbAplI[8e]',
        ),
    'H-dlalv' =>
        array(
            'user' => 'H-dlalv',
            'password' => 'N4g#@xUB[99',
        ),
    'P-crPv' =>
        array(
            'user' => 'P-crPv',
            'password' => 'Xb7=JMKE%bR',
        ),
    'M-crMv' =>
        array(
            'user' => 'M-crMv',
            'password' => 'ry.n&gI[r_B',
        ),
    'GalBel-crGalBelv' =>
        array(
            'user' => 'GalBel-crGalBelv',
            'password' => '<hA_#)Eiy7I',
        ),
    'L-crLv' =>
        array(
            'user' => 'L-crLv',
            'password' => ':8+H&[La3ph',
        ),
);
