<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<!-- jQuery -->
    <script type="text/javascript" src='<?= core\ConfigGlobal::getWeb_scripts().'/jquery/jquery-1.12.3.min.js'; ?>'></script>
    <script type="text/javascript" src='<?= core\ConfigGlobal::getWeb_scripts().'/jquery/ui/1.12/jquery-ui.min.js'; ?>'></script>
	<!--estilos-->
	<?php include_once(core\ConfigGlobal::$dir_estilos.'/todo_en_uno.css.php'); ?>
</head>

<h2><?= _("buscar una casa") ?></h2>
<?= ucfirst(_("hay 5 opciones diferentes para buscar una casa")); ?>
<!-- casas usadas anteriormente por esta delegación --------------------------------------------- -->
<form id="frm_buscar_1" name="frm_buscar_1" action="">
<?= $oHash1->getCamposHtml(); ?>
<table border=1 style="width: 95%;">
<tr><th colspan=2 class=titulo_inv><?= ucfirst(_("opción 1: posibles lugares (por historial)")); ?></th></tr>
<tr><td class="etiqueta"><?= _("más frequentes") ?></td>
	<td><?php 
	if (!empty($oDesplFreq) && is_object($oDesplFreq)) {
		echo $oDesplFreq->desplegable();
	} else {
		echo _("falta saber quien organiza");
	}
	?></td>
</tr>
<tr><td colspan=2 style="text-align:right;"><input id="b_buscar_1" name="b_buscar" TYPE="button" VALUE="<?= _("seleccionar"); ?>" onclick="fnjs_buscar('#frm_buscar_1')" ></td></tr>
</table>
</form>
<!-- -------- por la región a la que pertenece --------------------------------------------- -->
<form id="frm_buscar_2" name="frm_buscar_2" action="">
<?= $oHash2->getCamposHtml(); ?>
<table border=1 style="width: 95%;">
<tr><th colspan=2 class=titulo_inv><?= ucfirst(_("opción 2: según a la región a la que pertenece")); ?></th></tr>
<td class=etiqueta><?= _("según dl o r"); ?>:</td>
	<td colspan=2><?= $oDesplRegion->desplegable(); ?></td></tr>
<tr><td class=etiqueta><?= _("lugar"); ?></td>
	<td id='lst_lugar'></td>
</tr>
<tr><td colspan=2 style="text-align:right;"><input id="b_buscar_2" name="b_buscar" TYPE="button" VALUE="<?= _("seleccionar"); ?>" onclick="fnjs_buscar('#frm_buscar_2')" ></td></tr>
</table>
</form>
<!-- Origen, destino  más periodo --------------------------------------------- -->
<form id="frm_buscar_3" name="frm_buscar_3" action="">
<?= $oHash3->getCamposHtml(); ?>
<table border=1 style="width: 95%;">
<tr><th colspan=2 class=titulo_inv><?= ucfirst(_("opción 3: buscar por el nombre")); ?></th></tr>
<tr>
	<td class=etiqueta><?= _("nombre del lugar") ?></td>
	<td colspan="1"><input class=contenido id=nombre_ubi name=nombre_ubi size="30"></td>
</tr>

<tr><td colspan=2 style="text-align:right;"><input id="b_buscar_2" name="b_buscar" TYPE="button" VALUE="<?= _("buscar"); ?>" onclick="fnjs_enviar_form('#frm_buscar_3','#lst_lugares')" ></td></tr>
<tr><td id="lst_lugares" colspan=2></td></tr>

</table>
</form>
<!-- Lugares especiales --------------------------------------------- -->
<form id="frm_buscar_4" name="frm_buscar_4" action="">
<?= $oHash4->getCamposHtml(); ?>
<table border=1 style="width: 95%;">
<tr><th colspan=2 class=titulo_inv><?= ucfirst(_("opción 4: Un lugar especial (sin dirección posible)")); ?></th></tr>
<tr>
	<td class=etiqueta><?= _("nombre del lugar") ?></td>
	<td colspan="1"><input class=contenido id=frm_4_nombre_ubi name=frm_4_nombre_ubi size="30"></td>
</tr>

<tr><td colspan=2 style="text-align:right;"><input id="b_buscar_4" name="b_buscar" TYPE="button" VALUE="<?= _("seleccionar"); ?>" onclick="fnjs_buscar('#frm_buscar_4')" ></td></tr>
</table>
</form>
<!-- Lugares especiales --------------------------------------------- -->
<form id="frm_buscar_5" name="frm_buscar_5" action="">
<table border=1 style="width: 95%;">
<tr><th colspan=2 class=titulo_inv><?= ucfirst(_("opción 5: Por determinar")); ?></th></tr>
<tr><td colspan=5 style="text-align:right;"><input id="b_buscar_5" name="b_buscar" TYPE="button" VALUE="<?= _("seleccionar"); ?>" onclick="fnjs_buscar('#frm_buscar_5')" ></td></tr>
</table>
</form>
<script>
fnjs_enviar_form=function(id_form,bloque){
	if (!bloque) { bloque='#main'; }
	$(id_form).attr('action','<?= core\ConfigGlobal::getWeb().'/apps/ubis/controller/ubis_lista.php' ?>');
	$(id_form).one("submit", function() {
		$.ajax({
			url: $(this).attr('action'),
			type: 'post',
			data: $(this).serialize()
		})
		.done(function (rta_txt) {
			$(bloque).html(rta_txt);
		});
		return false;
	});
	$(id_form).trigger("submit");
	$(id_form).off();
}

fnjs_lugar=function(){
	var isfsv=<?= $isfsv ?>;
	var filtro_lugar=$('#filtro_lugar').val();
	var url='<?= core\ConfigGlobal::getWeb().'/apps/actividades/controller/actividad_tipo_get.php' ?>';
	var parametros='modo=buscar&salida=lugar&entrada='+filtro_lugar+'&isfsv='+isfsv+'<?= $h ?>';
	$.ajax({
		url: url,
		type: 'post',
		data: parametros,
		dataType: 'html'
	})
	.done(function (rta_txt) {
		$('#lst_lugar').html(rta_txt);
	});
}

fnjs_buscar=function(formulario,id){
	var form_name=$(formulario).attr('name');
	var opcion=form_name.substr(-1);
	if (opcion==1) {
		var lista=$('#id_ubi_1').val();
		var txt=$('#id_ubi_1 :selected').text();
		if (!lista) {
			alert ("<?= _("tiene que seleccionar una casa") ?>");
			return;
		}
	  	window.opener.$('#id_ubi').val(lista);
	  	window.opener.$('#nombre_ubi').val(txt);
		window.opener.$('#span_nom_ubi').html(txt);
		alert ("<?= $txt_alert ?>");
	  	window.close();

	}
	if (opcion==2) {
		/* OJO. este id_ubi no puede tener otro nombre, porque viene de una página
		*  "actividad_tipo_get.php" que también da los datos a otros programas.
		*/
		var lista=$('#id_ubi').val();
		var txt=$('#id_ubi :selected').text();
		if (!lista) {
			alert ("<?= _("tiene que seleccionar una casa") ?>");
			return;
		}
	  	window.opener.$('#id_ubi').val(lista);
	  	window.opener.$('#nombre_ubi').val(txt);
		window.opener.$('#span_nom_ubi').html(txt);
		alert ("<?= $txt_alert ?>");
	  	window.close();

	}
	if (opcion==3) {
		var lista=id;
		var txt=$('#'+id).html();;
		if (!lista) {
			alert ("<?= _("tiene que seleccionar una casa") ?>");
			return;
		}
	  	window.opener.$('#id_ubi').val(lista);
	  	window.opener.$('#nombre_ubi').val(txt);
		window.opener.$('#span_nom_ubi').html(txt);
		alert ("<?= $txt_alert ?>");
	  	window.close();
	}
	if (opcion==4) {
		/* OJO. este id_ubi no puede tener otro nombre, porque viene de una página
		*  "actividad_tipo_get.php" que también da los datos a otros programas.
		*/
		var txt=document.frm_buscar_4.frm_4_nombre_ubi.value;
		if (!txt) {
			alert ("<?= _("tiene que escribir un lugar") ?>");
			return;
		}
	  	window.opener.$('#id_ubi').val(1);
		window.opener.$('#span_nom_ubi').html(txt);
		window.opener.$('#lugar_esp').val(txt);
		alert ("<?= $txt_alert ?>");
	  	window.close();
	}
	if (opcion==5) {
		/* OJO. este id_ubi no puede tener otro nombre, porque viene de una página
		*  "actividad_tipo_get.php" que también da los datos a otros programas.
		*/
		var txt="<?= _("sin determinar") ?>";
		if (!txt) {
			alert ("<?= _("tiene que escribir un lugar") ?>");
			return;
		}
	  	window.opener.$('#id_ubi').val("");
		window.opener.$('#span_nom_ubi').html(txt);
		window.opener.$('#lugar_esp').val("");
		alert ("<?= $txt_alert ?>");
	  	window.close();
	}
}
fnjs_lugar();
</script>
