<script>
    fnjs_mas_centros = function (e) {
        var code = (e.keyCode ? e.keyCode : e.which);
        if (e == "x") {
            var valor = 1;
        } else {
            var id_campo = '#' + e.currentTarget.id;
            var valor = $(id_campo).val();
            if (code != 9) {
                e.preventDefault();
                e.stopPropagation();
            }
        }
        if (code == 9 || e.type == "change" || e == "x") {
            if (valor != 0) {
                <?= $oSelects->ListaSelectsJs(); ?>
            }
        }
    }

    fnjs_cerrar = function () {
        $('#div_modificar').html('');
        $('#div_modificar').width('0');
        $('#div_modificar').height('0');
        $('#div_modificar').removeClass('ventana');
        document.getElementById("overlay").style.display = "none";
    }

    fnjs_modificar = function (id_activ) {
        $('#div_modificar').addClass('ventana');
        $('#div_modificar').width('auto');
        $('#div_modificar').height('auto');
        document.getElementById("overlay").style.display = "block";

        var url = '<?= $url_ajax ?>';
        if (id_activ) {
            var parametros = 'que=form_ingreso&id_activ=' + id_activ;
        } else {
            id_ubi = $('#id_ctr').val();
            var parametros = 'que=nuevo&id_ubi=' + id_ubi;
        }
        fnjs_update_div('#div_modificar', url + '?' + parametros);
    }

    fnjs_ver = function () {
        pata = $('#seleccion').serialize();
        // obtener el listado de periodos
        var url = '<?= $url ?>';
        var parametros = <?= $parametros ?>;
        $.ajax({
            url: url,
            type: 'post',
            data: parametros,
            success: function (rta_txt) {
                //rta_txt=rta.responseText;
                //alert ('respuesta: '+rta_txt);
                if (rta_txt) {
                    $('#exportar').html(rta_txt);
                }
            }
        });
    }

    fnjs_guardar = function (formulario, que) {
        var err = 0;
        if (que == "eliminar") {
            seguro = confirm("<?= _("¿Está seguro de borrar los datos económicos de esta actividad?") ?>");
            if (seguro) {
                err = 0;
            } else {
                err = 1;
            }
        }
        if (err != 1) {
            $(formulario + ' input[name="que"]').val(que);
            $(formulario).attr('action', 'programas/centro_ajax.php');
            $(formulario).one("submit", function () {
                $.ajax({
                    data: $(this).serialize(),
                    url: $(this).attr('action'),
                    type: 'post',
                    complete: function (rta) {
                        rta_txt = rta.responseText;
                        if (rta_txt != '' && rta_txt != '\n') {
                            alert(rta_txt);
                        } else {
                            $('#div_modificar').html('');
                            $('#div_modificar').width('0');
                            $('#div_modificar').height('0');
                            $('#div_modificar').removeClass('ventana');
                        }
                    }
                });
                return false;
            });
            $(formulario).trigger("submit");
            $(formulario).off();
            fnjs_ver();
        }
    }
    <?= $oSelects->ComprobarSelectJs(); ?>
</script>
<form id=seleccion name=seleccion action="">
    <?php
    echo $oHashNuevo->getCamposHtml();

    if ($Qperiodo == 'no') {
        echo $oForm->getHtmlTabla2();
    } else {
        echo $oFormP->getHtml();
    }
    ?>
</form>
<div id='exportar'></div>
<div id='div_modificar'></div>
<div id='overlay'></div>