<script type="text/javascript" src="<?= 'apps/actividades/controller/actividades.js?'.rand(); ?>"></script>
<script>
fnjs_borrar=function(formulario,que_val){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= _("¿Está seguro que desea borrar esta actividad?");?>") ) {
			$('#mod').val(que_val);
			$(formulario).attr('action',"apps/actividades/controller/actividad_update.php");
			$(formulario).one("submit", function() {
				$.ajax({
					url: $(this).attr('action'),
					type: 'post',
					data: $(this).serialize()
				})
				.done(function (rta_txt) {
					if (rta_txt != '' && rta_txt != '\n') {
						alert (rta_txt);
					}
					$(formulario+' input.sel').each(function(i){
						if($(this).prop('checked') === true){
							$(this).parent().siblings().addClass('tachado');
							$(this).prop('checked',false);
						}
					});
				});
				return false;
			});
			$(formulario).trigger("submit");
			$(formulario).off();
		}
	}
};
fnjs_buscar=function(){
	$('#modifica').attr('action','apps/actividades/controller/actividad_que.php');
	$('#b_que').val("buscar");
	fnjs_enviar_formulario('#modifica','#main');
}
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<div id="condiciones" class="no_print">
	<form id="modifica" name="modifica" action="">
	<?= $oHash->getCamposHtml(); ?>
	<table><tr><td class="derecha">
		<input id="b_buscar" name="b_buscar" TYPE="button" VALUE="<?= _("realizar otra búsqueda"); ?>" onclick="fnjs_buscar()" >
	</td></tr>
	</table>
	</form>
</div>
<div id="resultados" >
<h3><?= $resultado ?></h3>
<form id='seleccionados' name='seleccionados' action='' method='post'>
	<?= $oHashSel->getCamposHtml(); ?>
	<input type='hidden' id='queSel' name='queSel' value='' >
	<input type='hidden' id='id_dossier' name='id_dossier' value="">
	<input type='hidden' id='mod' name='mod' value="<?= $mod ?>">
<?= $oTabla->mostrar_tabla(); ?>
</form>
<div class="no_print">
<br>
<?php
if ($perm_nueva) { //casa o centroSf
    echo '<table><tr>';
    foreach ($aTiposActiv as $txt_id => $idTipoActiv) {
    ?>
	<td><span class="link titulo" onclick="fnjs_update_div('#main','<?= web\Hash::link('apps/actividades/controller/actividad_ver.php?'.http_build_query(array('id_tipo_activ'=>$idTipoActiv))) ?>')" >
		<?= _("nueva actividad $txt_id") ?></span></td>     
<?php }
    echo '</tr></table>';
}
?>
</div>
</div>
