<?= $oPosicion->mostrar_left_slide(1); ?>
<script>
$(function() {
	$( "#f_ini" ).datepicker( {
		numberOfMonths: 3,
		showButtonPanel: true
		});

});
$(function() {
	$( "#f_fin" ).datepicker( {
		numberOfMonths: 3,
		showButtonPanel: true
		});

});
/*
 * Para enviar los parametros por POST
 * @type jQuery
 */
fnjs_cambiar_ubi=function(){
	var dl_org=$('#dl_org').val();
	var ssfsv=$('#ssfsv').val();
	var array_org=dl_org.split('#');
	var winPrefs="dependent=yes,width=950,height=700,screenX=200,screenY=200,titlebar=yes,scrollbars=yes";
	url = "<?= core\ConfigGlobal::getWeb() ?>/apps/actividades/controller/actividad_select_ubi.php";
	param_json = { dl_org : array_org[0], ssfsv: ssfsv };
	var h_param = "<?= $h ?>";
	var params = h_param.split('&');
	for (var i = 0; i < params.length; i++) {       
		var sParameterName = params[i].split('=');      
		param_json[sParameterName[0]] = sParameterName[1];
	}
	$.post(url,param_json, function(result){
		WinId = window.open('', 'sele', winPrefs);
        WinId.document.open();
        WinId.document.write(result);
        WinId.document.close();
        WinId.focus();
	});
};
fnjs_guardar=function(tipo=''){
	var err = 0;
	if (!fnjs_comprobar_fecha('#f_ini')) { err=1; }
	if (!fnjs_comprobar_fecha('#f_fin')) { err=1; }
	if (!fnjs_comprobar_hora('#h_ini')) { err=1; }
	if (!fnjs_comprobar_hora('#h_fin')) { err=1; }
	var dl_org=$('#dl_org').val();
	var estado = $('#status').val();

	/* comprobar si el id_tipo_actividad está completo */
	var id_sfsv_val=$('#isfsv_val').val();
	var id_asistentes_val=$('#iasistentes_val').val();
	var id_actividad_val=$('#iactividad_val').val();
	var id_nom_tipo_val=$('#inom_tipo_val').val();

	if (id_sfsv_val == '.') { alert("<?= _("Debe concretar la sección en el tipo de Actividad") ?>"); err=1; }
	if (id_asistentes_val == '.') { alert("<?= _("Debe concretar los asistentes en el tipo de Actividad") ?>"); err=1; }
	if (id_actividad_val == '.') { alert("<?= _("Debe concretar la actividad en el tipo de Actividad") ?>"); err=1; }
	if (id_nom_tipo_val == '...') { alert("<?= _("Debe concretar el tipo de Actividad") ?>"); err=1; }
	/* fin de tipo */
	
	if (!dl_org) { 
		alert("<?= _("Debe llenar el campo de Organiza") ?>"); err=1;
	}

	var rr=fnjs_comprobar_campos('#modifica','<?= addslashes($obj) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok' && err==0) {
		$('#mod').val(tipo);
		$('#modifica').attr('action','apps/actividades/controller/actividad_update.php');
		$('#modifica').submit(function() {
			$.ajax({
				data: $(this).serialize(),
				url: $(this).attr('action'),
				type: 'post',
				complete: function (rta) {
					rta_txt=rta.responseText;
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('respuesta: '+rta_txt);
					} else {
						<?= $oPosicion->js_atras(1); ?>
					}
				}
			});
			return false;
		});
		$('#modifica').submit();
		$('#modifica').off();
	}
};

fnjs_actualizar_sacd=function(){
	$('#modifica').attr('action','programas/actividad_update.php');
	$('#mod').val('actualizar_sacd');
	fnjs_enviar_formulario('#modifica');
};
fnjs_actualizar_ctr=function(){
	$('#modifica').attr('action','programas/actividad_update.php');
	$('#mod').val('actualizar_ctr');
	fnjs_enviar_formulario('#modifica');
};

fnjs_tipo_actividad=function(){
	$('#modifica').attr('action','programas/actividad_nueva.php');
	$('#mod').val('cambiar_tipo');
	fnjs_enviar_formulario('#modifica');
};
</script>
<!-- ============================== cabecera ============================= -->
<form id="modifica" name="modifica" action="" method="POST" >
<?= $oHash->getCamposHtml(); ?>
<input type='hidden' id='mod' name='mod' value='<?= $mod ?>'>
<?php if ($mod == 'nuevo' OR $accion=="cambiar_tipo") { ?>
	<!--<input type='hidden' id='id_tipo_activ' name='id_tipo_activ' value='<?= $id_tipo_activ ?>'>-->
	<table><tr><th class=titulo_inv><?= ucfirst(_("nueva actividad")); ?>
	</th></tr>
	<tr><td class=subtitulo><?= ucfirst(_("escoger el tipo de actividad")); ?>
	</td></tr>
	<tr>
		<?= $oActividadTipo->getHtml() ?>
	</tr>
	</table>
	<table><tr>
<?php } else { ?>
	<table><tr>
	<td>
	<span class="link" onclick="fnjs_update_div('#main','<?= $godossiers ?>')" ><img src=<?= core\ConfigGlobal::$web_icons ?>/dossiers.gif border=0 width=40 height=40 alt='<?= $alt ?>'>(<?= $dos ?>)</span>
	</td>
	<td class=titulo><?= $nom_activ ?></td>
	</table>
	<table>
	<tr><th colspan='8' class=titulo_inv><?= $titulo=strtoupper(_("datos actividad")); ?></th>
	<?php
	if(core\ConfigGlobal::is_app_installed('procesos') && $oPermActiv->only_perm('ver')) {
		echo "<tr><td colspan=8 class='alerta'>"._('no tiene permisos para modificar los datos')."</td></tr>";
	}
	if(core\ConfigGlobal::is_app_installed('procesos') && $oPermActiv->only_perm('borrar')) { ?>
	<td><input type="Button" value="<?= ucfirst(_("cambiar el tipo")); ?>" onclick="fnjs_tipo_actividad()"></td>
	<?php } ?>
	<tr>
		<td class=etiqueta><?= ucfirst(_("tipo de actividad")); ?>: </td>
		<?php if (($_SESSION['oPerm']->have_perm("vcsd")) or ($_SESSION['oPerm']->have_perm("des"))) { ?>
		<td><?= _("sf/sv"); ?>:
			<span class=contenido><?= "$ssfsv"?></span></td>
		<?php } ?>
		<td class=etiqueta><?= ucfirst(_("asistentes")); ?>: 
			<span class=contenido><?= $sasistentes ?>
			<input type='Hidden' id='sasistentes' name='sasistentes' value='<?= $sasistentes ?>'></span></td>
		<td class=etiqueta><?= ucfirst(_("actividad")); ?>: 
			<span class=contenido><?= $sactividad ?></span>
			<input type='Hidden' id='sactividad' name='sactividad' value='<?= $sactividad ?>'></span></td>
		<td class=etiqueta><?= ucfirst(_("tipo actividad")); ?>: 
		<!--para no hacerse un lio con el generar actividad válido para otros formularios,--> 
			<span class=contenido><?= "$snom_tipo"?>
				<input type='Hidden' id='snom_tipo' name='snom_tipo' value='<?= $snom_tipo ?>'></span></td>
	</tr>
<?php } ?>
<tr>
	<td class=etiqueta><?= ucfirst(_("estado")); ?>:</td>
	<?php if (!core\ConfigGlobal::is_app_installed('procesos')) { ?>
		<td><input type="Radio" id="status_1" name="status" value="1" <?php if ($status==1) { echo "checked";} ?>><?= _("proyecto"); ?></td>
		<td><input type="Radio" id="status_2" name="status" value="2" <?php if ($status==2) { echo "checked";} ?>><?= _("actual"); ?></td>
		<td><input type="radio" id="status_3" name="status" value="3" <?php if ($status==3) { echo "checked";} ?>><?= _("terminada"); ?></td>
		<td><input type="radio" id="status_4" name="status" value="4" <?php if ($status==4) { echo "checked";} ?>><?= _("borrable"); ?></td>
	<?php } else { ?>
		<!-- Ara faig que no es pugui canviar. S'ha d'anar per les fases.  -->
		<td><?= $a_status[$status] ?>
		<input type='hidden' id='status' name='status' value='<?= $status ?>'>
		</td>
	<?php } ?>
</tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("nombre actividad")); ?>:
	  </td><td colspan=8><input class=contenido size='60' id='nom_activ' name='nom_activ' value="<?= htmlspecialchars($nom_activ) ?>">
	  <span class=link onclick="fnjs_generarNomActiv('#modifica');" ><?= _("generar") ?></span></td>
</td></tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("fecha inicio")); ?>: </td><td><input class=fecha size="11" id="f_ini" name="f_ini" value="<?= $f_ini ?>">
	  <td class=etiqueta><?= ucfirst(_("hora inicio")); ?>: </td><td><input class=contenido size="6" id="h_ini" name="h_ini" value="<?= $h_ini ?>" title="<?= _('formato [hh:mm]') ?>">
</td></tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("fecha fin")); ?>: </td><td><input class=fecha size="11" id="f_fin" name="f_fin" value="<?= $f_fin ?>">
	  <td class=etiqueta><?= ucfirst(_("hora fin")); ?>: </td><td><input class=contenido size="6" id="h_fin" name="h_fin" value="<?= $h_fin ?>" title="<?= _('formato [hh:mm]') ?>">
</td></tr>
<?php
?>
<tr><td class=etiqueta><?= _("dl/r que organiza") ?>:</td>
<td colspan=2>
	<?= $oDesplDelegacionesOrg->desplegable(); ?>
	</td>
<td class=etiqueta><?= ucfirst(_("plazas totales")); ?>:</td>
<td><input class=contenido size="6" id="plazas" name="plazas" value="<?= $plazas ?>" ></td>
</tr>
<tr>
	<td class=etiqueta>
	    <?= ucfirst(_("lugar")); ?>: 
	 </td><td colspan=2 class=contenido ><span class="link" onclick="fnjs_cambiar_ubi();" id="span_nom_ubi"><?= $nombre_ubi ?></span>
	 <input type=hidden id="nombre_ubi" name="nombre_ubi" value="<?= $nombre_ubi ?>">
	 <input type=hidden id="id_ubi" name="id_ubi" value="<?= $id_ubi ?>">
	 <input type=hidden id="lugar_esp" name="lugar_esp" value="<?= $lugar_esp ?>">
	 </td>
</tr>
<tr>
	<td class=etiqueta><?= ucfirst(_("tarifa")); ?>: </td>
<td><?= $oDesplPosiblesTipoTarifas->desplegable(); ?></td>
<td class=etiqueta><?= ucfirst(_("precio")); ?>: </td>
  <td>
  <input type=text class="contenido derecha" id="precio" name="precio" value='<?= $precio ?>' size="8" > <?= _('€') ?>
</td></tr>
<tr><td class=etiqueta>
<?= ucfirst(_("observaciones")); ?>:</td><td colspan=2><input class=contenido size="30" id="observ" name="observ" value="<?= htmlspecialchars($observ) ?>">
</td></tr>
<tr>
	<td class=etiqueta><?= ucfirst(_(" repetición anual por")); ?>:</td>
<td colspan=2>
<?= $oDesplRepeticion->desplegable(); ?>
</td>
<td class=etiqueta><?= ucfirst(_(" nivel de stgr")); ?>:</td>
<td colspan=2>
<?= $oDesplNivelStgr->desplegable(); ?>
</td>
</tr><tr>
	<td class=etiqueta><?= _("publicado") ?>:</td>
<td><input type="Radio" id="pub_1" name="publicado" value="t" <?php if ($publicado == true) { echo "checked";} ?>><?= _("si"); ?>
<input type="Radio" id="pub_2" name="publicado" value="f" <?php if ($publicado == false) { echo "checked";} ?>><?= _("no"); ?></td>
</tr>
</table>
<br>
<!--======================== botón guardar ==================-->
<?php
switch ($mod) {
	case 'nuevo':
		echo "<input TYPE=\"button\" VALUE=\"".ucfirst(_("crear ficha"))."\" onclick=\"javascript:fnjs_guardar('nuevo')\"> ";
		break;
	case 'cambiar_tipo':
		echo "<input TYPE=\"button\" VALUE=\"".ucfirst(_("guardar ficha"))."\" onclick=\"javascript:fnjs_guardar('cmb_tipo')\"> ";
	case 'editar':
		if ($oPermActiv->have_perm('modificar') && $mod != 'importar') {
			echo "<input TYPE='button' VALUE='".ucfirst(_("guardar cambios"))."'  onclick=\"fnjs_guardar('editar')\">";
		}
	break;
}
?>
</form>
