<script>
fnjs_cerrar=function(){
	$('#div_modificar').html('');
	$('#div_modificar').width('0');
	$('#div_modificar').height('0');
	$('#div_modificar').removeClass('ventana');
	document.getElementById("overlay").style.display = "none";
}

fnjs_ver=function(){
	/* obtener el listado */
	var url='<?= core\ConfigGlobal::getWeb() ?>/apps/actividades/controller/actividad_tarifa_tipo_ajax.php';
	var parametros='que=get<?= $h_ver ?>';
		 
	$.ajax({
		url: url,
		type: 'post',
		data: parametros,
		success: function (rta_html) {
			//rta_txt=rta.responseText;
			//alert ('respuesta: '+rta_txt);
			if (rta_html) { 
				$('#ficha').html(rta_html);
			}
		}
	});
	document.getElementById("overlay").style.display = "none";
}

fnjs_modificar=function(id_item){
	$('#div_modificar').addClass('ventana');
	//$('#div_modificar').width('700');
	//$('#div_modificar').height('150');
	$('#div_modificar').width('auto');
	$('#div_modificar').height('auto');
	document.getElementById("overlay").style.display = "block";

	var url='<?= core\ConfigGlobal::getWeb() ?>/apps/actividades/controller/actividad_tarifa_tipo_form.php';
	var parametros='id_item='+id_item+'<?= $h_modificar ?>';
	fnjs_update_div('#div_modificar',url+'?'+parametros);
}

$(document).ready(fnjs_ver());
</script>
<div id='ficha'></div>
<div id='div_modificar'></div>
<div id='overlay'></div>