<script>
fnjs_asistentes=function(){
	var isfsv=$('#isfsv_val').val();
	if (isfsv==3) {
		$('#iasistentes_val').hide();
		$('#iactividad_val').hide();
		fnjs_nom_tipo();
	} else {
		var url='<?= core\ConfigGlobal::getWeb().'/apps/actividades/controller/actividad_tipo_get.php' ?>';
		var parametros='salida=asistentes&entrada='+isfsv+'<?= $h ?>';

		$.ajax({
			data: parametros,
			url: url,
			type: 'post',
			dataType: 'html',
			complete: function (rta) {
				rta_txt=rta.responseText;
				$('#lst_asistentes').html(rta_txt);
			}
		});
		// borrar el resto.
		$('#iasistentes_val').val(".");
		$('#iactividad_val').val(".");
		$('#inom_tipo_val').val("...");
	}
}
fnjs_actividad=function(){
	var isfsv=$('#isfsv_val').val();
	var iasistentes=$('#iasistentes_val').val();
	var url='<?= core\ConfigGlobal::getWeb().'/apps/actividades/controller/actividad_tipo_get.php' ?>';
	var parametros='salida=actividad&entrada='+isfsv+iasistentes+'<?= $h ?>';
	$.ajax({
		data: parametros,
		url: url,
		type: 'post',
		dataType: 'html',
		complete: function (rta) {
			rta_txt=rta.responseText;
			$('#lst_actividad').html(rta_txt);
		}
	});
}
fnjs_nom_tipo=function(){
	var isfsv=$('#isfsv_val').val();
	var iasistentes=$('#iasistentes_val').val();
	var iactividad=$('#iactividad_val').val();
	var url='<?= core\ConfigGlobal::getWeb().'/apps/actividades/controller/actividad_tipo_get.php' ?>';
	var parametros='salida=nom_tipo&entrada='+isfsv+iasistentes+iactividad+'<?= $h ?>';
	$.ajax({
		data: parametros,
		url: url,
		type: 'post',
		dataType: 'html',
		complete: function (rta) {
			rta_txt=rta.responseText;
			$('#lst_nom_tipo').html(rta_txt);
		}
	});
}
fnjs_act_id_activ=function(){
	var que=$('#que').val();
	var isfsv=$('#isfsv_val').val();
	var iasistentes=$('#iasistentes_val').val();
	var iactividad=$('#iactividad_val').val();
	var inom_tipo=$('#inom_tipo_val').val();
	var id_tipo_activ=isfsv+iasistentes+iactividad+inom_tipo;

	$('#id_tipo_activ').val(id_tipo_activ);
	if (que == 'proceso') {
		fnjs_ver();
	} else {
		// buscar la tarifa para este tipo de actividad
		var url='<?= core\ConfigGlobal::getWeb().'/apps/actividades/controller/actividad_tipo_get.php' ?>';
		var parametros='salida=tarifa&entrada='+id_tipo_activ+'<?= $h ?>';
		$.ajax({
			url: url,
			type: 'post',
			data: parametros,
			success: function (rta) {
					rta_txt=rta.responseText;
					//alert ('<?= _("respuesta") ?>: '+rta_txt);
					$('#tarifa').val(rta_txt);			
				}
		});
	}
	if ( que=="cambiar_tipo" && confirm ("<?= _("¿Quiere cambiar el nombre de la actividad?") ?>") ) {
		fnjs_generarNomActiv('#modifica');
	}
}
</script>
<table><tr>
<?php
if (core\ConfigGlobal::is_jefeCalendario()
	   	or (($_SESSION['oPerm']->have_perm("des") or $_SESSION['oPerm']->have_perm("vcsd")) && $isfsv == 1)
  		or (!empty($pag_usuarios) && $pag_usuarios=='perm')
   ) { 
	?>
	<td class="etiqueta"><?= _("sf/sv") ?></td>
		<td>
			<?= $oDesplSfsv->desplegable(); ?>
		</td>
	<?php
} else {
	?>
	<input type="hidden" id="isfsv_val" name="isfsv_val" value="<?= $isfsv; ?>" >
	<?php
}
?>
<td class="etiqueta"><?= _("asistentes") ?></td>
	<td id="lst_asistentes">
		<?= $oDesplAsistentes->desplegable(); ?>
	</td>
<td class="etiqueta"><?= _("actividad") ?></td>
	<td id="lst_actividad">
		<?= $oDesplActividad->desplegable(); ?>
	</td>
<td class="etiqueta"><?= _("tipo de actividad") ?></td>
	<td id="lst_nom_tipo">
		<?= $oDesplNomTipo->desplegable(); ?>
	</td>
</tr>
</table>