<script>
    fnjs_ver_planning = function (formulario, n) {
        var err = 0;
        var cdc_sel = $('input[name="cdc_sel"]:checked').val();

        // comprobar selección periodo
        var f = $('#periodo').val();
        if (f == 'otro') {
            if (!fnjs_comprobar_fecha('#empiezamin',<?= $locale_us ?>)) {
                err = 1;
                alert("<?= _("debe inrtoducir la fecha inicio del periodo") ?>");
            }
            if (!fnjs_comprobar_fecha('#empiezamax',<?= $locale_us ?>)) {
                err = 1;
                alert("<?= _("debe introducir la fecha fin del periodo") ?>");
            }
        } else {
            if (f == 0) {
                err = 1;
                alert("<?= _("debe introducir el periodo") ?>");
            }
        }
        // comprobar selección casa
        if (!cdc_sel) {
            alert("<?= _("Debe seleccionar una casa") ?>");
            err = 1;
        } else {
            if (cdc_sel == 9) {
                sum = 0;
                $('select[name^="id_cdc"]').each(function () {
                    c = $(this).val();
                    sum = sum + c;
                });
                //alert ("sum c: "+sum);
                if (sum == 0) {
                    alert("<?= _("Debe seleccionar una casa") ?>");
                    err = 1;
                }
            }
        }

        if (err == 0) {
            $('#modelo').val(n);
            fnjs_enviar_formulario(formulario);
        }
    }
</script>
<form name="que" id="que" target="print" action="apps/actividades/controller/calendario_planning.php" method="post"
      onkeypress="fnjs_enviar(event,this);">
    <?= $oHash->getCamposHtml(); ?>
    <?= $oForm->getHtmlTabla(); ?>
    <?= $oFormP->getHtml(); ?>
    <br>
    <table>
        <tfoot>
        <tr class=botones>
            <td><input TYPE="button" onclick="fnjs_ver_planning(this.form,1)" id="ok" name="ok"
                       value="<?= ucfirst(_("ver planning")); ?>" class="btn_ok"></td>
            <td><input TYPE="button" onclick="fnjs_ver_planning(this.form,3)" value="<?= ucfirst(_("v3")); ?>"></td>
            <td colspan=2><input TYPE="button" onclick="fnjs_ver_planning(this.form,2)"
                                 VALUE="<?= _("Vista para imprimir"); ?>"></td>
        </tr>
        </tfoot>
    </table>
</form>
