<script>
fnjs_mod_cambio=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		$('#salida').val('modificar');
        $(formulario).attr('action','apps/cambios/controller/usuario_avisos_pref.php');
		fnjs_enviar_formulario(formulario);
	}
}
fnjs_del_cambio=function(formulario,que_val){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
        if (confirm("<?= _("¿Está seguro que desea borrar este aviso?");?>") ) {
            $('#salida').val('eliminar');
	        $(formulario).attr('action','apps/cambios/controller/usuario_avisos_pref_ajax.php');
            $(formulario).one("submit", function() {
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'post',
                    data: $(this).serialize()
                })
                .done(function (rta_txt) { 
                	if (rta_txt != '' && rta_txt != '\\n') {
                        alert ('<?= _("respuesta") ?>: '+rta_txt);
                    } else {
                        <?= $oPosicion->js_atras(0); ?>
                    }
                });
                return false;
            });
            $(formulario).trigger("submit");
            $(formulario).off();
        }
	}
}
fnjs_add_cambio=function(){
    $('#salida').val('nuevo');
	$('#avisos').attr('action',"apps/cambios/controller/usuario_avisos_pref.php");
	fnjs_enviar_formulario('#avisos');
}
</script>
<br>
<b><?= _("avisos de cambios") ?>:</b>
<form id="avisos" name="avisos" action=''>
<?= $oHashAvisos->getCamposHtml(); ?>
<?= $oTablaAvisos->mostrar_tabla(); ?>
<input type=button onclick="fnjs_add_cambio();" value="<?= _("añadir aviso") ?>">
</form>
