<script>
fnjs_imprimir=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
  		$(formulario).attr('action',"apps/notas/controller/acta_imprimir.php");
  		fnjs_enviar_formulario(formulario);
  	}
}
fnjs_nuevo=function(formulario){
	$('#mod').val("nueva");
	$(formulario).attr('action',"apps/notas/controller/acta_ver.php");
  	fnjs_enviar_formulario(formulario,'#main');
}
fnjs_modificar=function(formulario){
	$('#mod').val("modificar");
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
  		$(formulario).attr('action',"apps/notas/controller/acta_ver.php");
  		fnjs_enviar_formulario(formulario);
  	}
}
fnjs_eliminar=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= $txt_eliminar ?>") ) {
			$('#mod').val("eliminar");
  			$(formulario).attr('action',"apps/notas/controller/acta_update.php");
			$(formulario).one("submit", function() {
				$.ajax({
					url: $(this).attr('action'),
					type: 'post',
					data: $(this).serialize()
				})
				.done(function (rta_txt) {
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					} else {
						fnjs_actualizar(formulario);
				   	}
				});
				return false;
			});
			$(formulario).trigger("submit");
			$(formulario).off();
		}
	}
}
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$(formulario).attr('action',"apps/notas/controller/acta_select.php");
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}
fnjs_left_side_hide();
</script>
<form id="frm_sin_nombre" name="frm_sin_nombre" action="apps/notas/controller/acta_select.php" method="post" onkeypress="fnjs_enviar(event,this);" >
<?= $oHash->getCamposHtml(); ?>
<table>
<th class=titulo_inv colspan=4><?= ucfirst(_("buscar un acta")); ?>
&nbsp;&nbsp;&nbsp;<input class=contenido id="acta" name="acta" size="30">
<div class="help-tip">
	<p><?= _("ejemplos") ?>:<br>
		 - <?= _("23/15 (sólo número) => busca en las actas de la r/dl.") ?><br>
		 - <?= _("crX .* | dlx .* => todas las actas de crX o dlx. Hay que dejar espacio") ?><br>
		 - <?= _("crX .*/15 | dlx .*/15 => todas las actas de crX o dlx del año 15") ?><br>
	</p>
</div>
</th>
<th colspan=4><input type="button" id="btn_ok" name="btn_ok" onclick="fnjs_enviar_formulario('#frm_sin_nombre');" value="<?= ucfirst(_("buscar")); ?>" class="btn_ok">
</th>
</table>
</form>

<h3 class=subtitulo><?= $titulo ?></h3>
<form id='seleccionados' id='seleccionados' name='seleccionados' action='' method='post'>
<?= $oHash1->getCamposHtml(); ?>
<input type='Hidden' id='mod' name='mod' value=''>
<?= $oTabla->mostrar_tabla(); ?>
</form>
<?php
// -----------------------------------  Botones  ----------------------
if (!empty($botones)) {
	echo "<table><tr class=botones>";
	$txt_g=ucwords(_("añadir acta"));
	echo "<th class='link_inv' onclick='fnjs_nuevo(\"#seleccionados\")'>$txt_g</th>"; 
	echo "</tr></table><br>";
}
// fin ----------------------------  Botones  ----------------------
?>
