<script>
$(function() { $( "#f_acta" ).datepicker(); });

fnjs_cmb_preceptor=function(){
	if($('#preceptor').prop('checked')) {
		var id_nom=$('#id_pau').val();
		//alert ('nom: '+id_nom);
		var url='<?= $url_ajax ?>';
		var parametros='que=posibles_preceptores<?= $h2 ?>';
			 
		$.ajax({
			url: url,
			type: 'post',
			data: parametros,
			success: function (rta_txt) {
				//rta_txt=rta.responseText;
				//alert ('respuesta: '+rta_txt);
				$('#lst_preceptores').html(rta_txt);
			}
		});
	} else { // al cambiar a NO preceptor
		var rta = '';
		$('#lst_preceptores').html(rta);
	}
}
/**
 * se ejecuta al cambiar el desplegable $oDesplegaAsignaturas
 * @returns desplegable de posibles asignaturas opcionales
 */
fnjs_cmb_opcional=function(){
	var id=$('#id_nivel').val();
	if (<?= $condicion_js; ?>) { //solo si es opcional
		var id_nom=$('#id_pau').val();
		//alert ('nom: '+id_nom);
		var url='<?= $url_ajax ?>';
		var parametros='que=posibles_opcionales&id_nom='+id_nom+'<?= $h1 ?>';
			 
		$.ajax({
			url: url,
			type: 'post',
			data: parametros,
			success: function (rta_txt) {
				//rta_txt=rta.responseText;
				//alert ('respuesta: '+rta_txt);
				$('#lst_opcionales').html(rta_txt);
			}
		});
	} else { // al cambiar a NO opcional
		var rta = '<input type="hidden" id="id_asignatura" name="id_asignatura" value="1">';
		$('#lst_opcionales').html(rta);
	}
}
fnjs_nota=function(){
	var num;
	var max;
	var sit;
	
	num = $('#nota_num').val();
	max = $('#nota_max').val();
	sit = $('#id_situacion').val();
	if (!num)  $('#id_situacion').val('0');
	num = parseFloat(num);
	if (typeof num == 'number' && num > 1) {
 		$('#id_situacion').val(10);
	}
	max_default = <?= core\ConfigGlobal::nota_max(); ?>;
	if (!max)  $('#nota_max').val(max_default);
}
fnjs_guardar=function(formulario){
	var err=0;
	var mod=$('#mod').val();
	var acta=$('#acta').val();
	var f_acta=$('#f_acta').val();
	var situacion=$('#id_situacion').val();
	var id_nivel=$('#id_nivel').val();
	
	if (id_nivel < 9990) { // No comprobar en caso "Fin bienio, cuadrienio".
		if (situacion == 10) { // comprobar la nota numérica
			var num = $('#nota_num').val();
			var max = $('#nota_max').val();
			num = parseFloat(num);
			max = parseFloat(max);
			if (isNaN(num)) { alert ('<?= _("valor de nota no válido") ?>'); err=1; } 
			if (num < 0 || num > max) { alert ('<?= _("nota fuera de rango") ?>'); err=1; } 
		}
		
		// situacion = 2 es para cursada
		if (!acta && situacion != 2) {
			alert("Debe llenar el campo del acta");
			$('#acta').focus();
			err=1;
		}
	}
	if (f_acta) {
		if (!fnjs_comprobar_fecha('#f_acta')) { err=1; }
	}
	
	var rr=fnjs_comprobar_campos(formulario,'<?= addslashes($obj) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok' && err!=1) {
		$(formulario).attr('action',"apps/notas/controller/update_1011.php");
		$(formulario).submit(function() {
			$.ajax({
				data: $(this).serialize(),
				url: $(this).attr('action'),
				type: 'post',
				complete: function (rta) {
					rta_txt=rta.responseText;
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('respuesta: '+rta_txt);
					} else {
						<?= $oPosicion->js_atras(1); ?>
					}
				}
			});
			return false;
		});
		$(formulario).submit();
		$(formulario).off();
	}
}
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<form id="form_1011" name="form_1011" action="" method="POST">
<?= $oHash->getCamposHtml(); ?>
<table>
<thead><tr><th colspan=4><?= _("asignaturas aprobadas") ?></th></tr></thead>
<tbody>
<?php
if (!empty($Qid_asignatura_real)) { //caso de modificar
	?>
	<tr><td><?= ucfirst(_("asignatura")) ?>:</td><td class=contenido><?= $nombre_corto ?></td></tr>
	<?php
} else { ?>
	<tr><td><?= ucfirst(_("asignatura")) ?>:</td>
	<td><?= $oDesplNiveles->desplegable(); ?></td>
	<td colspan="2">
		<div id='lst_opcionales'>
			<input type="hidden" id="id_asignatura" name="id_asignatura" value="1">
		</div
	</td>
	</tr>
<?php } ?>

<tr><td><?= _("nota") ?></td><td>
<input type="text" id="nota_num" name="nota_num" value="<?= $nota_num ?>" size="2" onchange="fnjs_nota()">
<?= _("sobre") ?>
<input type="text" id="nota_max" name="nota_max" value="<?= $nota_max ?>" size="2">
<td><?= _("situación") ?></td><td>
	<?= $oDesplNotas->desplegable(); ?>
</td></tr>
<tr>
<td>
	<input type="radio" id="tipo_acta_a" name="tipo_acta" value="<?= notas\model\entity\PersonaNota::FORMATO_ACTA ?>" <?= $chk_acta ?> >
		<?= _("acta") ?>
	<input type="radio" id="tipo_acta_c" name="tipo_acta" value="<?= notas\model\entity\PersonaNota::FORMATO_CERTIFICADO ?>" <?= $chk_certificado ?> >
	<?= _("certificado") ?>
</td>
<td colspan=1><input type="text" id="acta" name="acta" value="<?= $acta ?>" size="20">
</td>
<td colspan=2>
("?": <?= _("significa inventado") ?>   <?= _("Formato") ?>: "dlx nn/aa" o "dlx" o "region" o "?"</td>
</tr>

<tr><td><?= _("fecha acta") ?></td>
	<td><input type="text" id="f_acta" name="f_acta" value="<?= $f_acta ?>" size="12"></td>
</tr>
<tr><td><?= _("preceptor") ?></td>
	<td><input type="Checkbox" id="preceptor" name="preceptor" value="true" <?= $chk_preceptor ?> onclick='fnjs_cmb_preceptor()'></td>
	<td colspan="2">
		<div id='lst_preceptores'>
			<?php if (!empty($id_preceptor)) { 
				echo $oDesplProfesores->desplegable();		
			} ?>
		</div
	</td>
</tr>

<tr><td><?= _("epoca") ?></td>
	<td colspan="2"><input type="radio" id="epoca3" name="epoca" value="<?= notas\model\entity\PersonaNota::EPOCA_OTRO ?>" <?= $chk_epoca_otro ?> >
		<?= _("sin especificar") ?>
	<input type="radio" id="epoca1" name="epoca" value="<?= notas\model\entity\PersonaNota::EPOCA_CA ?>" <?= $chk_epoca_ca ?> >
		<?= _("ca") ?>
	<input type="radio" id="epoca2" name="epoca" value="<?= notas\model\entity\PersonaNota::EPOCA_INVIERNO ?>" <?= $chk_epoca_inv ?> >
	<?= _("semestre invierno") ?>
	</td>
</tr>
<tr><td><?= _("cursada en") ?></td>
<td class=contenido colspan=3>
	<?= $oDesplActividades->desplegable(); ?>
</td>
<tr><td><?= _("detalle") ?></td><td><input type="text" id="detalle" name="detalle" value="<?= $detalle ?>" ></td></tr>
</tbody></table>
<br><input type="button" value="<?= ucfirst(_("guardar")); ?>" onclick="fnjs_guardar(this.form)">
</form>
