<script>
$(function() { $( "#f_acta" ).datepicker(); });

fnjs_buscar_acta=function() {
	var tipo_acta=$('input[name=tipo_acta]:checked').val();
	if (tipo_acta == <?= notas\model\entity\PersonaNota::FORMATO_ACTA ?>) {
        var acta=$('#acta').val();

        var url='<?= $url_ajax ?>';
        var parametros='que=buscar_acta&acta='+acta+'<?= $h_acta ?>';
        $.ajax({
            url: url,
            type: 'post',
            data: parametros,
            dataType: 'json'
        })
        .done(function (rta_json) {
            id_asignatura = rta_json.id_asignatura;
            if (id_asignatura == 'no') {
                //borrar
                $('#id_nivel').val('');
                $('#f_acta').val('');
                $('#id_activ').val('');
                $('#nom_activ').text('');
                $("#epoca1").prop( "checked", true );
                
                fnjs_cmb_opcional();
            } else {
                fecha = rta_json.f_acta;
                id_activ = rta_json.id_activ;
                nom_activ = rta_json.nom_activ;
                acta = rta_json.acta;
                epoca = rta_json.epoca;
				id_epoca = '#epoca'+epoca;
                $('#acta').val(acta);
                $('#f_acta').val(fecha);
                $('#id_activ').val(id_activ);
                $('#nom_activ').text(nom_activ);
                $(id_epoca).prop( "checked", true );
                if (id_asignatura > 3000) {
                    // opcionales posibles
                    op_todas = <?= $op_genericas ?>;
                    // asig no aprobadas
                    niveles = $('#id_nivel option');
                    niveles.each( function( index, element ){
                        idNivel = $( this ).val();
                        if(op_todas.includes(idNivel)) {
                            //alert (idNivel);
                            //seleccionarla y finalizar bucle
                            $('#id_nivel').val(idNivel);
                            fnjs_cmb_opcional(id_asignatura);
                            return false; // breaks
                        }
                    });
                } else {
                    $('#id_nivel').val(id_asignatura);
                }
            }
        });

	}
	
}

fnjs_cerrar=function(){
	$('#div_modificar').html('');
	$('#div_modificar').width('0');
	$('#div_modificar').height('0');
	$('#div_modificar').removeClass('ventana');
	document.getElementById("overlay").style.display = "none";
}

fnjs_modificar=function(id_item){
	$('#div_modificar').addClass('ventana');
	$('#div_modificar').width('auto');
	$('#div_modificar').height('auto');
	document.getElementById("overlay").style.display = "block";

    var url='<?= $url_ajax ?>';
	var parametros='dl_org=&que=frm_buscar&f_acta_iso=<?= $f_acta_iso ?><?= $h_modificar ?>';
	fnjs_update_div('#div_modificar',url+'?'+parametros);
}

fnjs_buscar_ca=function(){
	var dl_org = $('#dl_org').val();
    var url='<?= $url_ajax ?>';
	var parametros='que=frm_buscar&f_acta_iso=<?= $f_acta_iso ?>&dl_org='+dl_org+'<?= $h_modificar ?>';
    $.ajax({
        url: url,
        type: 'post',
        data: parametros
    })
    .done(function (rta_txt) {
        $('#div_modificar').html(rta_txt);
    });
}

fnjs_update_activ=function() {
	id_activ = $("#id_activ_sel option:selected").val();
	nom_activ = $("#id_activ_sel option:selected").text();

	$('#id_activ').val(id_activ);
	$('#nom_activ').text(nom_activ);

	fnjs_cerrar();
}

fnjs_cmb_preceptor=function(){
	if($('#preceptor').prop('checked')) {
		var id_nom=$('#id_pau').val();
		//alert ('nom: '+id_nom);
		var url='<?= $url_ajax ?>';
		var parametros='que=posibles_preceptores<?= $h2 ?>';
			 
		$.ajax({
			url: url,
			type: 'post',
			data: parametros
		})
		.done(function (rta_txt) {
			$('#lst_preceptores').html(rta_txt);
		});
	} else { // al cambiar a NO preceptor
		var rta_txt = '';
		$('#lst_preceptores').html(rta_txt);
	}
}
/**
 * se ejecuta al cambiar el desplegable $oDesplegaAsignaturas
 * @returns desplegable de posibles asignaturas opcionales
 */
fnjs_cmb_opcional=function(id_asignatura=''){
	var id=$('#id_nivel').val();
	if (<?= $condicion_js; ?>) { //solo si es opcional
		var id_nom=$('#id_pau').val();
		//alert ('nom: '+id_nom);
		var url='<?= $url_ajax ?>';
		var parametros='que=posibles_opcionales&id_nom='+id_nom+'<?= $h1 ?>';
			 
		$.ajax({
			url: url,
			type: 'post',
			data: parametros
		})
		.done(function (rta_txt) {
			$('#lst_opcionales').html(rta_txt);
            $('#id_asignatura').val(id_asignatura);
		});
	} else { // al cambiar a NO opcional
		var rta_txt = '<input type="hidden" id="id_asignatura" name="id_asignatura" value="1">';
		$('#lst_opcionales').html(rta_txt);
	}
}
fnjs_nota=function(){
	var num;
	var max;
	var sit;
	
	num = $('#nota_num').val();
	max = $('#nota_max').val();
	sit = $('#id_situacion').val();
	if (!num)  $('#id_situacion').val('0');
	num = parseFloat(num);
	if (typeof num == 'number' && num > 1) {
 		$('#id_situacion').val(10);
	}
	max_default = <?= core\ConfigGlobal::nota_max(); ?>;
	if (!max)  $('#nota_max').val(max_default);
}
fnjs_guardar=function(formulario){
	var err=0;
	var mod=$('#mod').val();
	var acta=$('#acta').val();
	var f_acta=$('#f_acta').val();
	var situacion=$('#id_situacion').val();
	var id_nivel=$('#id_nivel').val();
	
	if (id_nivel < 9990) { // No comprobar en caso "Fin bienio, cuadrienio".
		if (situacion == 10) { // comprobar la nota numérica
			var num = $('#nota_num').val();
			var max = $('#nota_max').val();
			num = parseFloat(num);
			max = parseFloat(max);
			if (isNaN(num)) { alert ('<?= _("valor de nota no válido") ?>'); err=1; } 
			if (num < 0 || num > max) { alert ('<?= _("nota fuera de rango") ?>'); err=1; } 
		}
		/* El valor situacion lo toma como texto. Debo compara con texto */
		var arr_no_superadas = [<?= $lista_situacion_no_acta ?>];
		// situacion = 2 es para cursada, 11 exento
		if (!acta && !(jQuery.inArray(situacion, arr_no_superadas) !== -1)) { 
			alert("debe llenar el campo del acta");
			$('#acta').focus();
			err=1;
		}
	}
	if (f_acta) {
		if (!fnjs_comprobar_fecha('#f_acta')) { err=1; }
	}
	
	var rr=fnjs_comprobar_campos(formulario,'<?= addslashes($obj) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok' && err!=1) {
		$(formulario).attr('action',"apps/notas/controller/update_1011.php");
		$(formulario).submit(function() {
			$.ajax({
				url: $(this).attr('action'),
				type: 'post',
				data: $(this).serialize()
			})
			.done(function (rta_txt) {
				if (rta_txt != '' && rta_txt != '\\n') {
					alert ('<?= _("respuesta") ?>: '+rta_txt);
				} else {
					<?= $oPosicion->js_atras(1); ?>
				}
			});
			return false;
		});
		$(formulario).submit();
		$(formulario).off();
	}
}


</script>
<div id='div_modificar'></div>
<div id='overlay'></div>

<div id='ficha'>
<?= $oPosicion->mostrar_left_slide(1); ?>
<form id="form_1011" name="form_1011" action="" method="POST">
<?= $oHash->getCamposHtml(); ?>
<table>
<thead><tr><th colspan=4><?= _("asignaturas aprobadas") ?></th></tr></thead>
<tbody>
<?php
if (!empty($Qid_asignatura_real)) { //caso de modificar
	?>
	<tr><td><?= ucfirst(_("asignatura")) ?>:</td><td class=contenido><?= $nombre_corto ?></td></tr>
	<?php
} else { ?>
	<tr><td><?= ucfirst(_("asignatura")) ?>:</td>
	<td><?= $oDesplNiveles->desplegable(); ?></td>
	<td colspan="2">
		<div id='lst_opcionales'>
			<input type="hidden" id="id_asignatura" name="id_asignatura" value="1">
		</div>
	</td>
	</tr>
<?php } ?>

<tr><td><?= _("nota") ?></td><td>
<input type="text" id="nota_num" name="nota_num" value="<?= $nota_num ?>" size="2" onchange="fnjs_nota()">
<?= _("sobre") ?>
<input type="text" id="nota_max" name="nota_max" value="<?= $nota_max ?>" size="2">
<td><?= _("situación") ?></td><td>
	<?= $oDesplNotas->desplegable(); ?>
</td></tr>
<tr>
<td>
	<input type="radio" id="tipo_acta_a" name="tipo_acta" value="<?= notas\model\entity\PersonaNota::FORMATO_ACTA ?>" <?= $chk_acta ?> >
		<?= _("acta") ?>
	<input type="radio" id="tipo_acta_c" name="tipo_acta" value="<?= notas\model\entity\PersonaNota::FORMATO_CERTIFICADO ?>" <?= $chk_certificado ?> >
	<?= _("certificado") ?>
</td>
<td colspan=1><input type="text" id="acta" name="acta" value="<?= $acta ?>" size="20" onChange="fnjs_buscar_acta();">
</td>
<td colspan=2>
("?": <?= _("significa inventado") ?>   <?= _("formato") ?>: "dlx nn/aa" o "dlx" o "region" o "?"</td>
</tr>

<tr><td><?= _("fecha acta") ?></td>
	<td><input type="text" id="f_acta" name="f_acta" value="<?= $f_acta ?>" size="12"></td>
</tr>
<tr><td><?= _("preceptor") ?></td>
	<td><input type="Checkbox" id="preceptor" name="preceptor" value="true" <?= $chk_preceptor ?> onclick='fnjs_cmb_preceptor()'></td>
	<td colspan="2">
		<div id='lst_preceptores'>
			<?php if (!empty($id_preceptor)) { 
				echo $oDesplProfesores->desplegable();		
			} ?>
		</div>
	</td>
</tr>

<tr><td><?= _("época") ?></td>
	<td colspan="2"><input type="radio" id="epoca3" name="epoca" value="<?= notas\model\entity\PersonaNota::EPOCA_OTRO ?>" <?= $chk_epoca_otro ?> >
		<?= _("sin especificar") ?>
	<input type="radio" id="epoca1" name="epoca" value="<?= notas\model\entity\PersonaNota::EPOCA_CA ?>" <?= $chk_epoca_ca ?> >
		<?= _("ca") ?>
	<input type="radio" id="epoca2" name="epoca" value="<?= notas\model\entity\PersonaNota::EPOCA_INVIERNO ?>" <?= $chk_epoca_inv ?> >
	<?= _("semestre invierno") ?>
	</td>
</tr>
<tr><td><?= _("cursada en") ?></td>
<td colspan=2><span id="nom_activ"><?= $nom_activ ?></span>
    <span class="link" onclick="fnjs_modificar('nuevo');"><?= _("añadir ca") ?></span>
</td>
</tr>
<tr><td><?= _("detalle") ?></td><td><input type="text" id="detalle" name="detalle" value="<?= $detalle ?>" ></td></tr>
</tbody></table>
<br><input type="button" value="<?= ucfirst(_("guardar")); ?>" onclick="fnjs_guardar(this.form)">
</form>
</div>