<script>
    fnjs_guardar = function (formulario) {
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: 'src/usuarios/grupo_guardar',
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->jsNavAtras(1); ?>
            }
        });
    }
</script>
<?= $oPosicion->mostrarNavAtras(1); ?>
<h3><?= _("grupo") ?>: <?= $usuario ?></h3>
<form id="frm_usuario" name="frm_usuario" action="" method="post">
    <?= $oHashG->getCamposHtml(); ?>
    <input type=hidden id=user_que name=que value="">
    <br>
    <?= ucfirst(_("nombre")) ?>:<input type=text name=usuario value="<?= $usuario ?>">
    <br>
    <input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
    <br>
</form>
