<script>
    fnjs_guardar = function (formulario) {
        let rr = fnjs_comprobar_campos(formulario, '\\src\\usuarios\\domain\\entity\\Grupo');
        if (rr === 'ok') {
            let datos = $(formulario).serialize();
            let request = $.ajax({
                data: datos,
                url: 'src/usuarios/infrastructure/controllers/grupo_guardar.php',
                method: 'POST',
                dataType: 'json'
            });
            request.done(function (json) {
                if (json.success !== true) {
                    alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
                } else {
                    <?= $oPosicion->js_atras(1); ?>
                }
            });
        }
    }
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h3><?= _("grupo") ?>: <?= $usuario ?></h3>
<form id="frm_usuario" name="frm_usuario" action="" method="post">
    <?= $oHashG->getCamposHtml(); ?>
    <input type=hidden id=user_que name=que value="">
    <br>
    <?= ucfirst(_("nombre")) ?>:<input type=text name=usuario value="<?= $usuario ?>">
    <br>
    <input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
    <br>
</form>
