<?php

use core\ConfigGlobal;

?>
<script>
    fnjs_grabar = function (formulario) {
        var url = '<?= ConfigGlobal::getWeb() ?>/src/usuarios/infrastructure/controllers/perm_menu_guardar.php';
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: url,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->js_atras(1); ?>
            }
        });
    }
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h1><?= sprintf(_("Añadir nuevo permiso a %s"), $nombre) ?></h1>
<form id=pem_usuario name=perm_usuario action="" method="post">
    <?= $oHash->getCamposHtml(); ?>
    <br>
    <table>
        <tr>
            <td class=etiqueta><?= ucfirst(_("oficina o grupo")); ?>:</td>
            <td colspan=5>
                <?php
                echo $oCuadros->cuadros_radio('menu_perm', $menu_perm);
                ?>
            </td>
        </tr>
    </table>
    <br>
    <input type=button onclick="fnjs_grabar(this.form);" value=<?= _("guardar") ?>>
</form>
