<?php

use core\ConfigGlobal;
use web\Hash;

?>
    <script>
    fnjs_del_grupmenu = function (formulario) {
        let url = '<?= ConfigGlobal::getWeb() ?>/apps/usuarios/controller/role_grupmenu_del.php';
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: url,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
            } else {
                fnjs_actualizar(formulario);
            }
        });
    }

    fnjs_add_grupmenu = function (que) {
        go = '<?= Hash::link('frontend/usuarios/controller/role_grupmenu.php?' . http_build_query(array('id_role' => $Qid_role))) ?>';
        fnjs_update_div('#main', go);
    }

    fnjs_guardar = function (formulario) {
        let rr = fnjs_comprobar_campos(formulario, 'usuarios\\model\\entity\\Role');
        if (rr === 'ok') {
            var url = '<?= ConfigGlobal::getWeb() ?>/apps/usuarios/controller/role_guardar.php';
            let datos = $(formulario).serialize();
            let request = $.ajax({
                data: datos,
                url: url,
                method: 'POST',
                dataType: 'json'
            });
            request.done(function (json) {
                if (json.success !== true) {
                    alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
                } else {
                    <?= $oPosicion->js_atras(1) ?>
                }
            });
        }
    }
    fnjs_actualizar = function (formulario) {
        $("#que").val("grupmenu_del");
        $(formulario).attr('action', "frontend/usuarios/controller/role_form.php");
        fnjs_enviar_formulario(formulario, '#main');
    }
</script>
<?= $oPosicion->mostrar_left_slide(1) ?>
<h3><?= $role ?> <?= $txt_sfsv ?></h3>
<form id="frm_role" name="frm_role" action="" method="post">
    <?= $oHash->getCamposHtml(); ?>
    <input type="hidden" id="que_user" name="que" value"">
    <br>
    <?= ucfirst(_("nombre")) ?>:
    <input type="text" name="role" value="<?= $role ?>">
    <?= ucfirst(_("sf")) ?>:
    <input type="checkbox" name="sf" value="1"<?= $chk_sf ?> >
    <?= ucfirst(_("sv")) ?>:
    <input type="checkbox" name="sv" value="1"<?= $chk_sv ?> >
    <?= ucfirst(_("pau")) ?>:
    <?= $oDesplPau->desplegable(); ?>
    <?= ucfirst(_("dmz")) ?>:
    <input type="checkbox" name="dmz" value="1"<?= $chk_dmz ?> >
    <br>
    <?php
    if ($permiso === 1) {
        ?>
        <input type="button" onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
        <?php
    }
    ?>
    <br>
</form>

<?php
if (!empty($Qid_role)) { // si no hay role, no puedo poner permisos.
    ?>
    <h4><?= ucfirst(_("grupos de menús")) ?>:</h4>
    <p class="comentario">
        <?= _("Los roles son universales, pero los grupos de menus que se asignan a cada role son propios para cada dl (sv y sf distintos).") ?>
    </p>
    <br>
    <form id="form_grup_menu" name="form_grup_menu" action="">
        <?= $oHash1->getCamposHtml(); ?>
        <input type="hidden" id="que" name="que" value="">
        <?php
        echo $oTabla->mostrar_tabla();
        ?>
        <br>
        <input type="button" onclick="fnjs_add_grupmenu();" value="<?= _("añadir grup menu") ?>">
    </form>
    <?php
}
