<?php

use frontend\shared\config\AppUrlConfig;

?>
<script>
    fnjs_add_grupmenu = function (formulario) {
        var url = '<?= AppUrlConfig::getApiBaseUrl() ?>/src/usuarios/role_grupmenu_add';
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: url,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->jsNavAtras(1) ?>
            }
        });
    }
</script>
<?= $oPosicion->mostrarNavAtras(1) ?>
<h1><?= sprintf(_("añadir nuevo grupMenu a %s"), $role) ?></h1>
<form id="from_grupmenu" name="from_grupmenu" action="" method="post">
    <?= $oHash->getCamposHtml() ?>
    <h4><?= ucfirst(_("grupos de menús")) ?>:</h4>
    <?= $oTabla->mostrar_tabla() ?>
</form>
