<?php

use frontend\shared\config\AppUrlConfig;

?>
<script>
    fnjs_lst_add_grup = function () {
        var url = 'frontend/usuarios/controller/usuario_grupo_lst.php';
        var parametros = 'id_usuario=<?= $id_usuario ?><?= $h_lst ?>';

        fnjs_ajax_json_html({ url: url, data: parametros, target: '#lst_grupos' });
    }
    fnjs_lst_del_grup = function () {
        var url = 'frontend/usuarios/controller/usuario_grupo_del_lst.php';
        var parametros = 'id_usuario=<?= $id_usuario ?><?= $h_del_lst ?>';

        fnjs_ajax_json_html({ url: url, data: parametros, target: '#lst_grupos' });
    }
    fnjs_add_grup = function (param) {
        let url = '<?= AppUrlConfig::srcBrowserUrl('/src/usuarios/usuario_grupo_add') ?>';
        let request = $.ajax({
            data: param,
            url: url,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->jsNavAtras(0) ?>
            }
        });
    }
    fnjs_del_grup = function (param) {
        let url = '<?= AppUrlConfig::srcBrowserUrl('/src/usuarios/usuario_grupo_del') ?>';
        let request = $.ajax({
            data: param,
            url: url,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->jsNavAtras(0) ?>
            }
        });
    }
</script>
<br>
<b><?= _("grupos") ?>: </b>
<?php
//////////// Aclaración permisos ////////////
if (!empty($procesos_installed)) {
    ?>
    <p class="comentario"><?= _("OJO: los permisos en los grupos no tienen una preferencia definida.") ?></p>
    <p class="comentario"><?= _("Si hay más de uno, deberían ser independientes, sino no se sabe cual sobreescribirá a cual.") ?></p>
    <?php
} ?>
<br>
<p><?= $grupos_txt ?></p>
<br>
<input type=button onclick="fnjs_lst_add_grup();" value="<?= _("añadir un grupo de permisos") ?>">
<input type=button onclick="fnjs_lst_del_grup();" value="<?= _("quitar de un grupo de permisos") ?>">
<div id=lst_grupos></div>
<br>
<br>
