<script>
    fnjs_chk_passwd = function (formulario) {
        var password = encodeURIComponent($('#password').val());
        var url = 'apps/usuarios/controller/usuario_check_pwd.php';
        var parametros = 'id_usuario=<?= $id_usuario ?>&password=' + password + '<?= $h2 ?>';

        var request = $.ajax({
            data: parametros,
            url: url,
            type: 'post',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success != true) {
                alert("password error:\n" + json.mensaje);
                return false;
            } else {
                fnjs_guardar_datos(formulario);
            }
        });
    }

    fnjs_guardar = function (formulario) {
        // si es 0, no se cambia el password.
        var pwd = encodeURIComponent($("#password").val());
        var pwd1 = encodeURIComponent($("#password1").val());

        if (!pwd) {
            alert("<?= _("error: password no válido") ?>");
            return false;
        }
        if (!pwd1) {
            alert("<?= _("error: debes confirmar el password") ?>");
            return false;
        }
        if (pwd !== pwd1) {
            alert("<?= _("error: passwords no coincidentes") ?>");
            return false;
        }

        fnjs_chk_passwd(formulario);
    }

    fnjs_guardar_datos = function (formulario) {
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: 'apps/usuarios/controller/usuario_guardar_pwd.php',
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->js_atras(1); ?>
            }
        });
    }
</script>

<h3><?= $usuario ?></h3>
<?php if ($expire === 1) { ?>
    <?= _("deberías cambiar el password") ?>
<?php } ?>
<br>
<form id=frm_usuario name=frm_usuario action='' method="post">
    <?= $oHash->getCamposHtml() ?>
    <?= ucfirst(_("password")) ?>:<input type="password" id="password" name="password"><br>
    <?= ucfirst(_("confirma password")) ?>:<input type="password" id="password1" name="password1"><br>
    <br>
    <input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
    <br>
</form>
<br>
<?= _("Requerimientos del password") ?>:<br>
<ol>
    <li><?= _("Los passwords no pueden contener el valor del \"login\" o de qualquiera de las palabras del \"nombre\". (no tiene en cuenta mayúsculas/minúsculas)") ?>
        .
    </li>
    <li><?= _("El password ha de tener más de 8 caracteres") ?>.</li>
    <li><?= _("El password ha de tener como mínimo 3 de los sigientes grupos de caracteres") ?>:
        <ul>
            <li><?= _("Mayúsculas ('A' a 'Z')") ?></li>
            <li><?= _("Minúsculas ('a' a 'z')") ?></li>
            <li><?= _("Números ('0' a '9')") ?></li>
            <li><?= _("(No pueden ser comillas dobles!!) Caracteres: ~!@#$%^&*_-+=`|(){}[]:;<>,.?/") ?></li>
        </ul>
</ol>
