<script>
    /* Cuando se muestra al entrar, no tengo el jQuery */
    document.addEventListener('DOMContentLoaded', () => {
        if (typeof jQuery === 'undefined') {
            const script = document.createElement('script');
            script.src = '<?= $url_jquery ?>';
            document.head.appendChild(script);
            script.onload = () => {
                //console.log('jQuery cargado dinámicamente.');
            };

        } else if (typeof window.jQuery !== 'undefined') {
            // jQuery está cargado y accesible a través de jQuery
            //console.log('jQuery YA está cargado (acceso: jQuery). Versión:', jQuery.fn.jquery);
        } else if (typeof window.$ !== 'undefined' && typeof window.$.fn === 'object' && typeof window.$.fn.jquery === 'string') {
            // jQuery está cargado y accesible a través de $ (y confirmamos que es jQuery)
            //console.log('jQuery YA está cargado (acceso: $). Versión:', $.fn.jquery);
        } else {
            // $ está definido pero no parece ser jQuery (otra librería lo está usando)
            //console.log('Una librería diferente está usando el alias $. jQuery NO está cargado.');
        }
    });

    fnjs_chk_passwd = function (formulario) {
        var password = encodeURIComponent($('#password').val());
        var url = '<?= $url_usuario_chk ?>';
        var parametros = 'id_usuario=<?= $id_usuario ?>&password=' + password + '<?= $h2 ?>';

        var request = $.ajax({
            data: parametros,
            url: url,
            type: 'post',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("password error:\n" + json.mensaje);
                return false;
            } else {
                fnjs_guardar_datos(formulario);
            }
        });
    }

    fnjs_guardar = function (event,formulario) {
        event.preventDefault();
        // si es 0, no se cambia el password.
        var pwd = encodeURIComponent($("#password").val());
        var pwd1 = encodeURIComponent($("#password1").val());

        if (!pwd) {
            alert("<?= _("error: password no válido") ?>");
            return false;
        }
        if (!pwd1) {
            alert("<?= _("error: debes confirmar el password") ?>");
            return false;
        }
        if (pwd !== pwd1) {
            alert("<?= _("error: passwords no coincidentes") ?>");
            return false;
        }

        fnjs_chk_passwd(formulario);
    }

    fnjs_guardar_datos = function (formulario) {
        var url = '<?= $url_usuario_guardar ?>';
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: url,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
            } else {
                alert("<?= _("paswword guardado") ?>");
                fnjs_logout();
            }
        });
    }

    function fnjs_logout() {
        var parametros = 'logout=si&PHPSESSID=<?= session_id() ?>';
        top.location.href = '<?= $url_index ?>?' + parametros;
    }

</script>

<h3><?= $usuario ?></h3>
<?php if ($expire === 1) { ?>
    <?= _("deberías cambiar el password") ?>
    <br>
<?php } ?>
<br>
<form id="frm_usuario" name="frm_usuario" action="" method="post" onsubmit="fnjs_guardar(event,this);">
    <?= $oHash->getCamposHtml() ?>
    <?= ucfirst(_("password")) ?>:<input type="password" id="password" name="password"><br>
    <?= ucfirst(_("confirma password")) ?>:<input type="password" id="password1" name="password1"><br>
    <br>
    <input type="submit" value="<?= $txt_guardar ?>">
    <?= _("deberá volver a entrar") ?>
    <br>
</form>
<br>
<?= _("Requerimientos del password") ?>:<br>
<ol>
    <li><?= _("Los passwords no pueden contener el valor del \"login\" o de cualquiera de las palabras del \"nombre\". (no tiene en cuenta mayúsculas/minúsculas)") ?>
        .
    </li>
    <li><?= _("El password ha de tener más de 8 caracteres") ?>.</li>
    <li><?= _("El password ha de tener como mínimo 3 de los sigientes grupos de caracteres") ?>:
        <ul>
            <li><?= _("Mayúsculas ('A' a 'Z')") ?></li>
            <li><?= _("Minúsculas ('a' a 'z')") ?></li>
            <li><?= _("Números ('0' a '9')") ?></li>
            <li><?= _("Caracteres especiales válidos (no pueden ser comillas dobles):") ?>
                ~!@#$%^&*_-+=`|(){}[]:;<>,.?/
            </li>
        </ul>
</ol>
