<script>
    fnjs_guardar = function (formulario) {
        let datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: 'src/usuarios/infrastructure/controllers/usuario_guardar_mail.php',
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
            } else {
                <?= $oPosicion->js_atras(1); ?>
            }
        });
    }
</script>

<h3><?= $usuario ?></h3>
<form id=frm_usuario name=frm_usuario action='' method="post">
    <?= $oHash->getCamposHtml() ?>
    <?= ucfirst(_("email")) ?>:<input type=text name=email size="50px" value="<?= $email ?>"><br>
    <br>
    <input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
    <br>
</form>