<script>
    fnjs_trasladar = function (formulario) {
        $(formulario).attr('action', "apps/ubis/controller/trasladar_ubis.php");
        fnjs_enviar_formulario(formulario);
    }
    fnjs_modificar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $(formulario).attr('action', "apps/ubis/controller/home_ubis.php");
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_borrar = function (formulario) {
        var seguro;
        seguro = confirm("<?= _("¿Está seguro que desea borrar este ubi?");?>");
        if (seguro) {
            $(formulario).one("submit", function () {
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'post',
                    data: $(this).serialize()
                })
                    .done(function (rta_txt) {
                        if (rta_txt != '' && rta_txt != '\n') {
                            alert(rta_txt);
                        }
                    });
                return false;
            });
            $(formulario).trigger("submit");
            $(formulario).off();
        }
    }

</script>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHash->getCamposHtml(); ?>
    <h2 class=titulo><?= $titulo; ?></h2>
    <?= $oTabla->mostrar_tabla(); ?>
</form>
<?php
switch ($nueva_ficha) {
    case 'especificar':
        ?>
        <span style="font-size:large">
		<?= _("no existe este centro o casa"); ?>.<br>
		<br>
		<?= _("OJO!: para crear un centro/casa debe especificar el tipo de centro/casa") ?>.
		<br>
		<?= _("Para ello debe buscar a través de 'ver más opciones' definiendo el tipo y la localización distinto a 'todos'."); ?>
		<br>
	    </span>
        <br>
        <input id="b_mas" name="b_mas" TYPE="button" VALUE="<?= _("buscar otras opciones"); ?>"
               onclick="fnjs_update_div('#main','<?= $pagina_link ?>')">
        <?php
        break;
    case 'aviso':
        ?>
        <span style="font-size:large">
        <?= _("no existe este nombre de centro o casa. Puede crear una nueva ficha"); ?>.
        </span>
    <?php
    case 'nueva':
        ?>
        <br>
        <input id="b_mas" name="b_mas" TYPE="button" VALUE="<?= _("nuevo centro o casa"); ?>"
               onclick="fnjs_update_div('#main','<?= $pagina_link ?>')">
        <?php
        break;
    default:
        ?>
    <?php
}
