<?php
/**
 * @var string $tipo_persona
 * @var array $a_persona_listas
 * @var string $url_sincro_trasladar_a
 * @var string $h
 */

$txt_alert = _("se va a poner la fecha de hoy como fecha de traslado. Para cambiarlo ir al a ficha de la persona y al dossier de traslados");
?>
<script>
    fnjs_trasladar = function (id_orbix, dl, fila) {
        var url = '<?= $url_sincro_trasladar_a ?>';
        var parametros = 'dl=' + dl + '&id_nom_orbix=' + id_orbix + '&tipo_persona=<?= $tipo_persona ?><?= $h ?>';

        alert(<?= json_encode((string)$txt_alert) ?>);

        var request = $.ajax({
            url: url,
            data: parametros,
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
            if (json.success !== true) {
                alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
            } else {
                $("#fila" + fila).addClass('tachado');
            }
        });
    }
</script>

<h3><?= _("personas en otras dl en la BDU") ?></h3>
<table>
    <tr>
        <th><?= _("ape_nom") ?></th>
        <th><?= _("dl actual") ?></th>
        <th></th>
    </tr>
    <?php
    $i = 0;
    foreach ($a_persona_listas as $persona_listas) {
        $i++;
        $id_orbix = $persona_listas['id_nom_orbix'];
        $dl_actual = $persona_listas['dl'];
        echo "<tr id=fila$i>";
        echo "<td class='titulo'>" . htmlspecialchars($persona_listas['ape_nom']) . '</td>';
        echo "<td>" . htmlspecialchars($dl_actual) . '</td>';
        echo "<td><span class=link onClick='fnjs_trasladar($id_orbix,\"$dl_actual\",$i)'>" . _("trasladar") . '</span><td>';
        echo '</tr>';
    }
    ?>
</table>
