<script>
    fnjs_mas_actividades = function (evt) {
        if (evt == "x") {
            var valor = 1;
        } else {
            var id_campo = evt.currentTarget.id;
            var valor = $(id_campo).val();
            evt.preventDefault();
            evt.stopPropagation();
        }
        if (evt.keyCode == 9 || evt.type == "change" || evt == "x") {
            if (valor != 0) {
                <?php echo $oSelects->ListaSelectsJs(); ?>
            }
        }
    }
    fnjs_guardar = function (formulario) {
        $.ajax({
            type: 'post',
            url: <?= json_encode($url_guardar) ?>,
            data: $(formulario).serialize(),
            dataType: 'json'
        }).done(function (json) {
            if (json && json.success === true) {
                fnjs_nav_atras(1);
            } else {
                alert(json && json.mensaje ? json.mensaje : '<?= _("error al guardar") ?>');
            }
        });
    }
    fnjs_borrar = function (formulario) {
        $.ajax({
            type: 'post',
            url: <?= json_encode($url_eliminar) ?>,
            data: $(formulario).serialize(),
            dataType: 'json'
        }).done(function (json) {
            if (json && json.success === true) {
                fnjs_actualizar();
            } else {
                alert(json && json.mensaje ? json.mensaje : '<?= _("error al borrar") ?>');
            }
        });
    }

    fnjs_actualizar = function () {
        $('#frm_peticiones').attr('action', 'frontend/actividadplazas/controller/peticiones_activ.php');
        fnjs_enviar_formulario('#frm_peticiones');
    }
    <?= $oSelects->ComprobarSelectJs(); ?>
</script>
<?= $oPosicion->mostrarNavAtras(1); ?>
<h3><?= $ap_nom ?></h3>
<form id=frm_peticiones name=frm_peticiones action='' method="post">
    <?= $oHash->getCamposHtml(); ?>
    <table>
        <tr>
            <td class=etiqueta width="30%"><?= _("actividades"); ?>:</td>
            <td id="col_actividades"> <?= $oSelects->ListaSelects(); ?></td>
        </tr>
    </table>
    <input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
    <input type=button onclick="fnjs_borrar(this.form);" value="<?= _("borrar") ?>">
</form>
