#!/usr/bin/env python3
"""
Render a compact, fix-oriented list from vo_db_validation_report.json.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Show only actionable VO validation errors.")
    parser.add_argument(
        "--input",
        default="docs/dev/reports/vo_db_validation_report.json",
        help="Path to JSON report generated by check_vo_db_constraints.php",
    )
    parser.add_argument(
        "--show-entity-errors",
        action="store_true",
        help="Include _entity hydration errors in output.",
    )
    parser.add_argument(
        "--dedupe",
        action="store_true",
        help="Collapse exact duplicate incidents.",
    )
    return parser.parse_args()


def normalize_value(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, str):
        return value
    return str(value)


def main() -> int:
    args = parse_args()
    input_path = Path(args.input).resolve()
    if not input_path.exists():
        print(f"ERROR: file not found: {input_path}")
        return 2

    report = json.loads(input_path.read_text(encoding="utf-8"))
    incidents = report.get("incidents", [])
    execution = report.get("execution", {})
    schemas = execution.get("schemas", [])
    if not schemas and isinstance(execution.get("esquema"), str):
        schemas = [execution.get("esquema")]

    if not isinstance(incidents, list):
        print("ERROR: report does not contain a valid 'incidents' list")
        return 2

    schema_index: dict[tuple, str] = {}
    by_module = report.get("by_module", {})
    if isinstance(by_module, dict):
        for module_data in by_module.values():
            if not isinstance(module_data, dict):
                continue
            by_schema = module_data.get("by_schema", {})
            if not isinstance(by_schema, dict):
                continue
            for schema_name, schema_data in by_schema.items():
                if not isinstance(schema_data, dict):
                    continue
                schema_incidents = schema_data.get("incidents", [])
                if not isinstance(schema_incidents, list):
                    continue
                for inc in schema_incidents:
                    if not isinstance(inc, dict):
                        continue
                    key = (
                        inc.get("module"),
                        inc.get("tabla"),
                        inc.get("primary_key"),
                        inc.get("campo"),
                        inc.get("valor_actual"),
                        inc.get("motivo"),
                    )
                    schema_index[key] = str(schema_name)

    filtered = []
    for item in incidents:
        if not isinstance(item, dict):
            continue
        if not args.show_entity_errors and item.get("campo") == "_entity":
            continue
        filtered.append(item)

    if args.dedupe:
        deduped = []
        seen = set()
        for item in filtered:
            key = (
                item.get("module"),
                item.get("tabla"),
                item.get("primary_key"),
                item.get("campo"),
                item.get("valor_actual"),
                item.get("motivo"),
                item.get("sql_sugerido"),
            )
            if key in seen:
                continue
            seen.add(key)
            deduped.append(item)
        filtered = deduped

    print(f"errors_found={len(filtered)}")
    if isinstance(schemas, list) and schemas:
        print(f"schemas={','.join(str(s) for s in schemas)}")
    else:
        print("schemas=unknown")
    print(f"source={input_path}")
    print("")

    if not filtered:
        print("No errors to show with current filters.")
        return 0

    for idx, item in enumerate(filtered, start=1):
        module = item.get("module", "?")
        table = item.get("tabla", "?")
        primary_key = item.get("primary_key", "?")
        field = item.get("campo", "?")
        key = (
            item.get("module"),
            item.get("tabla"),
            item.get("primary_key"),
            item.get("campo"),
            item.get("valor_actual"),
            item.get("motivo"),
        )
        schema_name = schema_index.get(key, "?")
        value = normalize_value(item.get("valor_actual"))
        reason = normalize_value(item.get("motivo"))
        sql = normalize_value(item.get("sql_sugerido"))
        entity = item.get("entity", "?")

        print(f"{idx}. {schema_name}, {module}.{table} | pk={primary_key} | campo={field}")
        print(f"   valor={value}")
        print(f"   motivo={reason}")
        print(f"   sql_sugerido={sql}")
        print(f"   entity={entity}")
        print("")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
