<?= $oPosicion->mostrarNavAtras(1) ?>
<script>
<?= $script ?>
</script>

<!-- <div id="exportar"> -->
    <h3 class=subtitulo><?= $titulo ?></h3>
    <p class=comentario><?= $explicacion ?></p>
    <form id='seleccionados' name='seleccionados' action='' method='post'>
        <?= $oHashSelect->getCamposHtml() ?>
        <input type='hidden' id='mod' name='mod' value=''>
            <?= $oTabla->mostrar_tabla() ?>

            <?php if ($permiso === 3) { ?>
            <br>
                <table class=botones>
                    <tr class=botones>
                        <td class=botones>
                            <input name="btn_new" type="button" value="<?= _("nuevo") ?>"
                                   onclick="fnjs_nuevo('#seleccionados');">
                        </td>
                    </tr>
                </table>
        <?php } ?>
    </form>
<!-- </div> -->
