<?php
/** @var \web\Hash $oHash */
/** @var string $txt */
/** @var string $txt_lento */
/** @var int $any0 */
/** @var int $any1 */
/** @var int $any2 */
/** @var int $year1 */
/** @var int $year2 */
/** @var int $year3 */
/** @var string $url_ejecutar */
?>
<script>
    fnjs_generar_nuevo_curso = function () {
        fnjs_guardar_estado();
        fnjs_borrar_posibles_atras();
        fnjs_ajax_json_html({
            url: <?= json_encode($url_ejecutar, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP) ?>,
            data: $('#frm_sin_nombre').serialize(),
            target: '#main'
        });
    };
</script>
<?= $txt ?>
<br>
<br>
<?= $txt_lento ?>
<br>
<br>
<form id="frm_sin_nombre" name="frm_sin_nombre" action="#">
    <?= $oHash->getCamposHtml(); ?>
    <?= _("año origen:") ?>
    <select name="year_ref">
        <option value="<?= $any2 ?>"><?= $any2 ?></option>
        <option value="<?= $any1 ?>"><?= $any1 ?></option>
        <option value="<?= $any0 ?>" selected><?= $any0 ?></option>
    </select>
    <?= _("año destino:") ?>
    <select name="year">
        <option value="<?= $year1 ?>" selected><?= $year1 ?></option>
        <option value="<?= $year2 ?>"><?= $year2 ?></option>
        <option value="<?= $year3 ?>"><?= $year3 ?></option>
    </select>
    <br>
    <input type="checkbox" name="ver_lista" value="t"><?= _("Ver listado") ?>
    <br>
    <input type="button" onclick="fnjs_generar_nuevo_curso();" value="<?= _("generar nuevo curso") ?>">
</form>
