<script>
fnjs_nota=function(n){
	var num;
	var max;
	var sit;
	
	num = $('#nota_num'+n).val();
	max = $('#nota_max'+n).val();
	max_default = <?= core\ConfigGlobal::nota_max(); ?>;
	if (!max)  $('#nota_max'+n).val(max_default);
	fnjs_guardar_nota();
}

fnjs_imprimir=function(form_acta){
	mod=$('#mod').val();
	if (mod=='nueva') {
		alert("<?= $txt_alert_acta ?>");
	} else {
		fnjs_left_side_hide();
		$(form_acta).attr('action',"apps/notas/controller/acta_imprimir.php");
		fnjs_enviar_formulario(form_acta);
	}
}

//paso las matrículas a notas definitivas
fnjs_guardar_tessera=function(form_acta){
	// comporbar que se ha guardado el acta
	mod=$('#mod').val();
	if (mod=='nueva') {
		alert("<?= $txt_alert_acta ?>");
	} else {
		$('#que').val("3");
		$('#f_1303').attr('action',"apps/actividadestudios/controller/acta_notas_update.php");
		$('#f_1303').submit(function() {
			$.ajax({
				data: $(this).serialize(),
				url: $(this).attr('action'),
				type: 'post',
				complete: function (rta) {
					rta_txt=rta.responseText;
					if (rta_txt != '' && rta_txt != '\n') {
						alert (rta_txt);
					}
				}
			});
			return false;
		});
		$('#f_1303').submit();
		$('#f_1303').off();
	}
}

// Grabar las notas en la matricula
fnjs_guardar_nota=function(){
	// comporbar que se ha guardado el acta
	mod=$('#mod').val();
	if (mod=='nueva') {
		alert("<?= $txt_alert_acta ?>");
	} else {
		$('#que').val("1");
		$('#f_1303').attr('action',"apps/actividadestudios/controller/acta_notas_update.php");
		$('#f_1303').submit(function() {
			$.ajax({
				data: $(this).serialize(),
				url: $(this).attr('action'),
				type: 'post',
				complete: function (rta) {
					rta_txt=rta.responseText;
					if (rta_txt != '' && rta_txt != '\n') {
						alert (rta_txt);
					}
				}
			});
			return false;
		});
		$('#f_1303').submit();
		$('#f_1303').off();
	}
}
</script>
<form id="f_1303" name="f_1303" action="" method="POST">
<?= $oHashNotas->getCamposHtml(); ?>
<input type="Hidden" id="que" name="que" value="<?= $Qque ?>">
<table>
<thead><tr><th class=titulo_inv colspan=6><?= strtoupper(_("notas del acta")); ?></th></tr>
<tr><th><?= _("alumno"); ?></th><th><?= _("preceptor"); ?></th><th><?= _("nota"); ?></th><th><?= _("acta"); ?></th></tr>
</thead>
<tbody>
<?php
$i=0;
foreach ($aPersonasMatriculadas as $nom=>$oMatricula) {
	$i++;
	$id_nom=$oMatricula->getId_nom();
	$nota_num=$oMatricula->getNota_num();
	$nota_max=$oMatricula->getNota_max();
	$id_situacion=$oMatricula->getId_situacion();
	$preceptor=$oMatricula->getPreceptor();
	if ($preceptor=="t") { $chk_tipo="selected"; } else { $chk_tipo=""; }
	$acta=$oMatricula->getActa();
	$oDesplActas->setOpcion_sel($acta);
	$oDesplActas->setAction("fnjs_nota($i)");
	?>
	<input type="Hidden" id="id_nom[]" name="id_nom[]" value="<?= $id_nom ?>">
	<tr><td><?= $nom ?></td>
	<td><select id="form_preceptor[]" name="form_preceptor[]" onchange="javascript:fnjs_guardar_nota()">
			<option />
			<option value="p" <?= $chk_tipo ?> ><?= _("preceptor") ?></option>
		</select>
		</td>
	<td class=contenido>
		<input type="text" id="nota_num<?= $i ?>" name="nota_num[]" value="<?= $nota_num ?>" size="2" onchange="fnjs_nota(<?= $i ?>)">
		<?= _("sobre") ?>
		<input type="text" id="nota_max<?= $i ?>" name="nota_max[]" value="<?= $nota_max ?>" size="2" onchange="fnjs_nota(<?= $i ?>)">
	</td>
	<td><?= $oDesplActas->desplegable(); ?>
	</td></tr>
	<?php
}
?>	
</tbody></table>
</form>
<br><input type="button" value="<?= strtoupper(_("grabar notas en tessera")); ?>" onclick="fnjs_guardar_tessera('#frm_acta')">
<br><input type="button" value="<?= strtoupper(_("imprimir")); ?>" onclick="fnjs_imprimir('#frm_acta')">