<script>
fnjs_n_a=function(dd){
	$('#na').val(dd);
	if (dd=='agd') {
		$('#id_ctr_n').val('');
	} else {
		$('#id_ctr_agd').val('');
	}
}
</script>
<form id="modifica" name="modifica" action="apps/actividadestudios/controller/ca_posibles.php" method="POST">
<?= $oHash->getCamposHtml(); ?>
<input type="hidden" id="na" name="na" value="">
<!-- Selección de centros -->
<table>
	<tr>
		<th colspan=2><?= ucfirst(_("ver cuadro de posibles ca")); ?></th>
	</tr>
	<tr>
		<td colspan=2><?= _("Nota: Para que salgan los ca en el cuadro deben tener introducidas las asignaturas y el campo de nivel de stgr"); ?></td>
	</tr>
	<tr>
	<td>
		<table style="width:250px">
			<tr>
			<th colspan=2><?= ucfirst(_("numerarios")); ?></th>
			</tr>
			<tr>
			<td colspan=2 align=center>
			<br>
			</td></tr>
			<tr>
			<td><b><?= _("centro") ?></b></td>
			<td><?= $oDesplCtrN->desplegable(); ?></td></tr>
			</td></tr>
		</table>
	</td>
	<td>
		<table style="width:250px">
			<tr>
			<th colspan=2><?= ucfirst(_("agregados")); ?></th>
			</tr>
			<tr>
			<td colspan=2 align=center>
			<br>
			</td></tr>
			<tr>
			<td><b><?= _("centro") ?></b></td>
			<td><?= $oDesplCtrAgd->desplegable(); ?></td></tr>
		</table>
	</td></tr>
</table>
<?= $oFormP->getHtml(); ?>
<table>
<tr><td><br></td></tr>
<tr>
<th colspan=5><?= _("selección por delegaciones"); ?></th>
</tr>
<tr><td colspan=4><input type="radio" id="todos" name="todos" value=<?= $grupo_estudios?> checked><?= $mi_grupo ?>    <input type="radio" name="todos" value=1 ><?= _("todos") ?></td></tr>
<tr><td><br></td></tr>
<tr>
<th colspan=5><?= _("formato del cuadro"); ?></th>
</tr>
<tr><td><?= ucfirst(_("escrito de referencia")).":"; ?><input type=text name=ref></td></tr>
<tr><td><input type="Radio" name="texto" value="text"><?= ucfirst(_("texto cabecera horizontal (excel)")); ?></td>
<td colspan=4><input type="Radio" name="texto" value="image" checked><?= ucfirst(_("texto cabecera vertical (imprimir)")); ?></td></tr>
<tr><td>
	<input name='btn1' type=button onclick="fnjs_enviar_formulario(this.form)" value="<?= _("ver cuadro") ?>" >
</td></tr>
</table>
