<?= $oPosicion->mostrar_left_slide(1); ?>
<table>
<th class='ca_posibles_nom' colspan=2><?= $titulo ?></th>
<th>stgr: <?= $stgr ?></th>

<?php 
foreach($aActividades as $actividad) {
   $nom_activ=$actividad["nom_activ"];
   $creditos=$actividad["creditos"];

   echo "<tr><td style=\"text-align: left;\">  $nom_activ</td><td>$creditos</td></tr>";
}
?>
</table>
<h3><span class=link onclick="fnjs_update_div('#main','<?= $pagina ?>')" ><?=  _("ir a dossier de actividades") ?></span></h3>