<?= $oPosicion->mostrar_left_slide(1); ?>
<table>
    <th class='ca_posibles_nom' colspan=2><?= $titulo ?></th>
    <th>stgr: <?= $stgr ?></th>

    <?php
    foreach ($aActividades as $actividad) {
//	'nom_activ' => $nom_activ,
//	'creditos' => $creditos,
//	'aLista' => $aLista,
        $nom_activ = $actividad["nom_activ"];
        $creditos = $actividad["creditos"];
        $txt_creditos = sprintf(_("total: %s créditos"), $creditos);
        $aLista = $actividad["aLista"];
        $txt_asig = '';
        foreach ($aLista as $Lista) {
            $txt_asig .= !empty($txt_asig) ? "<br>" : '';
            $txt_asig .= $Lista['nombre_asignatura'];
            $txt_asig .= " (" . $Lista['creditos'] . ")";
        }

        echo "<tr><td style=\"text-align: left;\">$nom_activ</td><td>$txt_asig</td><td>$txt_creditos</td></tr>";
    }
    ?>
</table>
<h3><span class=link onclick="fnjs_update_div('#main','<?= $pagina ?>')"><?= _("ir a dossier de actividades") ?></span>
</h3>