<script>
	fnjs_left_side_hide(); 
</script>
<br>
<table class="no_print"><tr>
	<td align="left">
		<?= $oPosicion->mostrar_back_arrow(1); ?>
	</td>
	<td align="center"></td>
	<td align="center"><span class=link onclick='window.open("<?= core\ConfigGlobal::getWeb() ?>/apps/actividadestudios/controller/e43_2_mpdf.php?id_nom=<?= $id_nom ?>&id_activ=<?= $id_activ ?><?= $h ?>&PHPSESSID=<?= session_id(); ?>", "sele");' >
<?= _("PDF"); ?></span></td>
</tr></table>
<hr>

<br>
<div id="exportar">
<div class="A4">
<table><tr><td><?= $dl_destino ?></td><td class="derecha"><?= $dl_origen ?></td></tr></table>
<br><br>
<table style="width: 80%">
	<tr><td><?= _("Nombre y apellidos"); ?>:</td><td><?= $nom ?></td></tr>
	<tr><td><?= _("Lugar y fecha de nacimiento"); ?>:</td><td><?= $txt_nacimiento ?></td></tr>
	<tr><td><?= _("Fecha y lugar del sem, ca o cv"); ?>:</td><td><?= $txt_actividad ?></td></tr>
</table>
<br>
<table class="calif">
	<tr></tr>
	<tr><td class="calif"><?=	strtoupper(_("asignatura")) ?> (1)</td>
		<td class="calif"><?=	strtoupper(_("calificación")) ?></td>
		<td class="calif"><?=	strtoupper(_("fecha del acta")) ?></td>
		<td class="calif"><?=	strtoupper(_("nº del acta")) ?> (2)</td>
	</tr>
<?php
if ($matriculas > 0) {
	$i=0;
	foreach ($aAsignaturasMatriculadas as $key=>$aAsignaturas) {
		echo "<tr>";
		echo "<td class='calif'>".$aAsignaturas['nom_asignatura']."</td>";
		echo "<td class='calif'>".$aAsignaturas['nota']."</td>";
		echo "<td class='calif'>".$aAsignaturas['f_acta']."</td>";
		echo "<td class='calif'>".$aAsignaturas['acta']."</td>";
		echo "</tr>";
	}
}
?>	
</table>
<br>
<table><tr><td>
(1) Deben anotarse todas las asignaturas previstas, indicando en las observaciones los eventuales cambios en el plan de estudios.
</td></tr>
<tr><td>
(2) Rellenar después del ca, en la dl que organizó el ca, antes de enviar a la dl de procedencia del alumno.
</td></tr>
<tr><td class="centro">
(OBSERVACIONES AL DORSO)
</td></tr></table>
<div>
<div>