<?php

use core\ConfigGlobal;

?>
<script>
    $(function () {
        $("#f_ini").datepicker({
            numberOfMonths: 3,
            showButtonPanel: true
        });

    });
    $(function () {
        $("#f_fin").datepicker({
            numberOfMonths: 3,
            showButtonPanel: true
        });

    });
    fnjs_mas_profes = function (filtro) {
        var url = '<?= ConfigGlobal::getWeb() . '/apps/actividadestudios/controller/lista_profesores_ajax.php' ?>';
        switch (filtro) {
            case 'asignatura':
                id_asignatura = $("#id_asignatura").val();
                var parametros = 'salida=asignatura&id_asignatura=' + id_asignatura + '&id_activ=<?= $id_activ ?><?= $h2 ?>';
                break;
            case 'dl':
                var parametros = 'salida=dl&id_activ=<?= $id_activ ?><?= $h1 ?>';
                break;
            case 'all':
                var parametros = 'salida=todos<?= $h ?>';
                break;
        }
        $.ajax({
            url: url,
            type: 'post',
            data: parametros,
            dataType: 'html'
        })
            .done(function (rta_txt) {
                $('#lst_profes').html(rta_txt);
            });
    }

    fnjs_guardar = function (formulario) {
        var rr = fnjs_comprobar_campos(formulario, '<?= addslashes($obj) ?>');

        if (rr === 'ok') {
            $(formulario).attr('action', 'apps/actividadestudios/controller/update_3005.php');
            $(formulario).one("submit", function () {
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'post',
                    data: $(this).serialize()
                })
                    .done(function (rta_txt) {
                        if (rta_txt !== '' && rta_txt !== '\\n') {
                            alert('<?= _("respuesta") ?>: ' + rta_txt);
                        } else {
                            <?= $oPosicion->js_atras(1); ?>
                        }
                    });
                return false;
            });
            $(formulario).trigger("submit");
            $(formulario).off();
        }
    }
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<form id="frm_sin_nombre" name="frm_sin_nombre" action="" method="POST">
    <?= $oHash->getCamposHtml(); ?>
    <input type="Hidden" id="mod" name="mod" value="<?= $mod ?>">
    <table>
        <tr class=tab>
            <th class=titulo_inv colspan=5><?= ucfirst(_("asignatura de una actividad")); ?></th>
        </tr>
        <?php if (!empty($id_asignatura)) { ?>
            <tr>
            <td class=etiqueta><?= ucfirst(_("asignatura")) ?>:</td>
            <td class=contenido><?= $nombre_corto ?></td>
        <?php } else { ?>
            <tr>
                <td class=etiqueta><?= ucfirst(_("asignatura")) ?>:</td>
                <td>
                    <?= $oDesplAsignaturas->desplegable(); ?>
                </td>
            </tr>
        <?php } ?>
        <tr>
            <td class=etiqueta><?= ucfirst(_("profesor")) ?>:</td>
            <td id="lst_profes">
                <?= $oDesplProfesores->desplegable(); ?>
            </td>
            <td><input type=button onclick="fnjs_mas_profes('asignatura')" value="<?= _("corresponde") ?>"></td>
            <td><input type=button onclick="fnjs_mas_profes('dl')" value="<?= _("dl y asistentes") ?>"></td>
            <td><input type=button onclick="fnjs_mas_profes('all')" value="<?= _("otros de paso") ?>"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= _("tipo") ?></td>
            <td><select class=contenido id='tipo' name='tipo'>
                    <option></option>
                    <option value='p' <?= $chk_preceptor ?> > <?= _("preceptor") ?></option>
                </select></td>
        </tr>
        <tr>
            <td class=etiqueta><?= _("¿Profesor avisado?") ?></td>
            <td><select class=contenido id='avis_profesor' name='avis_profesor'>
                    <option></option>
                    <option value='a' <?= $chk_avisado ?> ><?= _("avisado") ?></option>
                    <option value='c' <?= $chk_confirmado ?> ><?= _("confirmado") ?></option>
                </select></td>
        </tr>
        <tr>
            <td class=etiqueta><?= _("inicio clases") ?></td>
            <td>
                <input id='f_ini' name='f_ini' type="text" class="fecha" size="11" value="<?= $f_ini_iso ?>"
                       onchange="fnjs_comprobar_fecha('#f_ini',<?= $locale_us ?>)">
            </td>
        </tr>
        <tr>
            <td class=etiqueta><?= _("fin clases") ?></td>
            <td>
                <input id='f_fin' name='f_fin' type="text" class="fecha" size="11" value="<?= $f_fin_iso ?>"
                       onchange="fnjs_comprobar_fecha('#f_ini',<?= $locale_us ?>)">
            </td>
        </tr>
    </table>
    <br>
    <input type="button" id="guardar" name="guardar" onclick="fnjs_guardar(this.form);"
           value="<?= ucfirst(_("guardar")); ?>" align="MIDDLE">
