<script>
    fnjs_buscar = function () {
        var campo = '<input type="hidden" name="refresh" value=1>';
        $('#periodo_form').attr('action', "apps/actividadestudios/controller/matriculas_lista_otras_r.php");
        $('#periodo_form').append(campo);
        fnjs_enviar_formulario('#periodo_form', '#main');
    }

    fnjs_imp_certificado = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            $(formulario).attr('action', "apps/notas/controller/certificado_imprimir.php");
            $(formulario).target = "print";
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_left_side_hide();
</script>
<form id='periodo_form' action=''>
    <?= $oHashPeriodo->getCamposHtml() ?>
    <?= $oFormP->getHtml() ?>
</form>
<h2 class=titulo><?= $titulo ?></h2>
<h3><?= $aviso; ?></h3>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHash->getCamposHtml() ?>
    <input type="hidden" id="pau" name="pau" value="p">
    <input type="hidden" id="mod" name="mod" value="">
    <?= $oTabla->mostrar_tabla() ?>
</form>