<script>
    fnjs_modificar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $(nuevo).val(2);
            $(formulario).attr('action', "apps/actividadestudios/controller/form_1303.php");
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_borrar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            if (confirm("<?= $txt_eliminar ?>")) {
                $('#mod').val("eliminar");
                $(formulario).attr('action', "apps/actividadestudios/controller/update_3103.php");
                $(formulario).one("submit", function () {
                    $.ajax({
                        url: $(this).attr('action'),
                        type: 'post',
                        data: $(this).serialize()
                    })
                        .done(function (rta_txt) {
                            if (rta_txt !== '' && rta_txt !== '\\n') {
                                alert('<?= _("respuesta") ?>: ' + rta_txt);
                            } else {
                                fnjs_actualizar(formulario);
                            }
                        });
                    return false;
                });
                $(formulario).trigger("submit");
                $(formulario).off();
            }
        }
    }
    fnjs_actualizar = function (formulario) {
        var campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "apps/dossiers/controller/dossiers_ver.php");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#main');
    }
</script>
<h2 class=titulo><?= ucfirst($nom_activ) ?></h2>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHashSelect->getCamposHtml(); ?>
    <input type='hidden' id='mod' name='mod' value=''>
    <?= $oTabla->listaPaginada(); ?>
</form>
