<?php

use src\shared\config\ConfigGlobal;

?>
<html>
<head>
    <style>
        @page { margin: 1cm; }
        div.salta_pag { page-break-after: always; }
        h1 { text-transform: uppercase; }
        table { width: 680px; font-size: 12pt; }
        td.cabecera { text-align: left; font-weight: bold; }
        table.lst, table.lst td { border: 1px solid #000; border-collapse: collapse; margin: 0; padding: 6px; }
        table.lst td.cabecera { text-align: center; font-weight: bold; text-transform: capitalize; }
        td.derecha { text-align: right; }
        p { margin-left: 0; font-weight: bold; }
    </style>
</head>
<body>
<h1>profesor de stgr</h1>
<table>
    <col width="15%"><col width="60%"><col width="10%"><col width="15%">
    <tr><td><?= ucfirst(_("nombre")) ?>:</td><td><?= $nom_ap ?></td><td class=derecha><?= _("ctr") ?>:</td><td><?= $nombre_ubi ?></td></tr>
    <tr><td></td><td></td><td class=derecha><?= _("dl") ?>:</td><td><?= ConfigGlobal::mi_delef() ?></td></tr>
    <tr><td><?= ucfirst(_("departamento")) ?>:</td><td><?= $dep ?></td><td class=derecha><?= _("n") ?>:</td><td><?= $num_txt ?></td></tr>
    <tr><td></td><td></td><td class=derecha><?= _("agd") ?>:</td><td><?= $agd_txt ?></td></tr>
    <tr><td></td><td></td><td class=derecha><?= _("sacd") ?>:</td><td><?= $sacd_txt ?></td></tr>
</table>
<br>
<?php if ($aPerm['curriculum'] > 1) { ?>
    <h3><?= ucfirst(_("curriculum")) ?></h3>
    <table class=lst>
        <?php foreach ($a_curriculum as $row) { echo "<tr><td>{$row['titulo']}</td><td>{$row['centro_dnt']}</td><td>{$row['year']}</td></tr>"; } ?>
    </table>
<?php } ?>
<?php if ($aPerm['nombramientos'] > 1) { ?>
    <h3><?= ucfirst(_("nombramientos")) ?></h3>
    <table class=lst>
        <tr><td class=cabecera><?= _("categoría") ?></td><td class=cabecera><?= _("fecha") ?></td><td class=cabecera><?= _("aviso") ?></td></tr>
        <?php foreach ($a_nombramientos as $row) { echo "<tr><td>{$row['tipo_profesor']}</td><td>{$row['f_nombramiento']}</td><td>{$row['escrito_nombramiento']}</td></tr>"; } ?>
    </table>
<?php } ?>
<?php if ($aPerm['ampliacion'] > 1) { ?>
    <h3><?= ucfirst(_("ampliación de docencia")) ?></h3>
    <table class=lst>
        <tr><td class=cabecera><?= _("asignaturas") ?></td><td class=cabecera><?= _("aviso") ?></td><td class=cabecera><?= _("fecha") ?></td></tr>
        <?php foreach ($a_ampliacion as $row) { echo "<tr><td>{$row['nombre_corto']}</td><td>{$row['escrito_nombramiento']}</td><td>{$row['f_nombramiento']}</td></tr>"; } ?>
    </table>
<?php } ?>
<br>
<?php if ($aPerm['latin'] > 1) { ?><p><?= ucfirst(_("profesor de latín")) ?>: <?= $latin_txt ?></p><?php } ?>
<?php if ($aPerm['congresos'] > 1) { ?>
    <h3><?= ucfirst(_("convivencias y congresos")) ?></h3>
    <table class=lst>
        <tr><td class=cabecera><?= _("tema") ?></td><td class=cabecera><?= _("lugar") ?></td><td class=cabecera><?= _("inicio") ?></td><td class=cabecera><?= _("fin") ?></td></tr>
        <?php foreach ($a_congresos as $row) { echo "<tr><td>{$row['congreso']}</td><td>{$row['lugar']}</td><td>{$row['f_ini']}</td><td>{$row['f_fin']}</td></tr>"; } ?>
    </table>
<?php } ?>
<?php if ($aPerm['docencia'] > 1) { ?>
    <h3><?= ucfirst(_("actividad docente")) ?></h3>
    <table class=lst>
        <tr><td class=cabecera><?= _("curso") ?></td><td class=cabecera><?= _("asignatura") ?></td><td class=cabecera><?= _("modo") ?></td></tr>
        <?php foreach ($a_docencias as $row) { echo "<tr><td>{$row['curso_inicio']} - {$row['curso_fin']}</td><td>{$row['nombre_corto']}</td><td>{$row['modo']}</td></tr>"; } ?>
    </table>
<?php } ?>
</body>
</html>
