<script>
    fnjs_profes = function () {
        id_asignatura = $("#id_asignatura").val();
        var parametros = 'id_asignatura=' + id_asignatura + '<?= $h ?>';
        fnjs_ajax_json_html({ url: '<?= $url_ajax ?>', data: parametros, target: '#resultados' });
    };
    fnjs_left_side_hide();
</script>
<table>
    <tr class=tab>
        <th class=titulo_inv colspan=5><?= ucfirst(_("profesores que pueden impartir una asignatura")) ?></th>
    </tr>
    <tr>
        <td class=etiqueta><?= ucfirst(_("asignatura")) ?></td>
        <td><?= $oDesplAsignaturas->desplegable() ?></td>
    </tr>
    </tbody>
</table>
<div id="resultados"></div>
