<?php
use asignaturas\model\entity as asignaturas;
?>
<html>
<head>
<style>
	@page {  margin: 1cm;
		}
	div.salta_pag { page-break-after:always;}
	h1 { text-transform : uppercase; }
	table { width: 680; font-size: 12pt; 
		}
	td.cabecera { text-align: left;
	    font-weight : bold;
	 }
	table.lst, table.lst td{
		border:1px solid #000;
		border-collapse:collapse;
		margin:0;
		padding:6px;
	}
	table.lst td.cabecera { text-align: center;
	    font-weight : bold;
		text-transform : capitalize;
	 }
	td.derecha { text-align: right; }
	 p { margin-left: 0;
	    font-weight : bold;
		}
</style>
</head>
<body>

<h1>profesor de stgr</h1>
<table><col width="15%"><col width="60%"><col width="10%"><col width="15%">
<tr><td><?= ucfirst(_("nombre")) ?>:</td><td><?= $nom_ap ?></td><td class=derecha><?= _("ctr") ?>: </td><td><?= $nombre_ubi ?></td></tr>
<tr><td></td><td></td><td class=derecha><?= _("dl") ?>: </td><td><?= core\ConfigGlobal::mi_dele() ?></td></tr>
<tr><td><?= ucfirst(_("departamento")) ?>:</td><td><?= $dep ?></td><td class=derecha><?= _("n") ?>: </td><td><?= $num_txt ?></td></tr>
<tr><td></td><td></td><td class=derecha><?= _("agd") ?>: </td><td><?= $agd_txt ?></td></tr>
<tr><td></td><td></td><td class=derecha><?= _("sacd") ?>: </td><td><?= $sacd_txt ?></td></tr>
</table>
<br>
<h3><?= ucfirst(_("curriculum")) ?></h3>
<table class=lst>
<?php
if (!empty($a_curriculum) && is_array($a_curriculum)) {
	foreach ($a_curriculum as $n => $row) {
		echo "<tr><td>${row['titulo']}</td><td>${row['centro_dnt']}</td><td>${row['year']}</td></tr>";
	}
}
?>
</table>
<h3><?= ucfirst(_("nombramientos")) ?></h3>
<table class=lst>
<tr><td class=cabecera><?= _("categoría") ?></td><td class=cabecera><?= _("fecha") ?></td><td class=cabecera><?= _("aviso") ?></td></tr>
<?php
if (!empty($a_nombramientos) && is_array($a_nombramientos)) {
	foreach ($a_nombramientos as $n => $row) {
		echo "<tr><td>${row['tipo_profesor']}</td><td>${row['f_nombramiento']}</td><td>${row['escrito_nombramiento']}</td></tr>";
	}
}
?>
</table>
<h3><?= ucfirst(_("ampliación de docencia")) ?></h3>
<table class=lst>
<tr><td class=cabecera><?= _("asignaturas") ?></td><td class=cabecera><?= _("aviso") ?></td><td class=cabecera><?= _("fecha") ?></td></tr>
<?php
if (!empty($ampliacion) && is_array($ampliacion)) {
	foreach ($ampliacion as $n => $row) {
		echo "<tr><td>${row['nombre_corto']}</td><td>${row['escrito_nombramiento']}</td><td>${row['f_nombramiento']}</td></tr>";
	}
}
?>
</table>
<br>
<p><?= ucfirst(_("profesor de latín")) ?>: <?= $latin_txt ?></p>
<h3><?= ucfirst(_("convivencias y congresos")) ?></h3>
<table class=lst>
<tr><td class=cabecera><?= _("tema") ?></td><td class=cabecera><?= _("lugar") ?></td><td class=cabecera><?= _("inicio") ?></td><td class=cabecera><?= _("fin") ?></td></tr>
<?php
foreach($cProfesorCongresos as $oProfesorCongreso) {
	$row = $oProfesorCongreso->getTot();
	echo "<tr><td>${row['congreso']}</td><td>${row['lugar']}</td><td>${row['f_ini']}</td><td>${row['f_fin']}</td></tr>";
}
?>
</table>
<h3><?= ucfirst(_("actividad docente")) ?></h3>
<table class=lst>
<tr><td class=cabecera><?= _("curso") ?></td><td class=cabecera><?= _("asignatura") ?></td><td class=cabecera><?= _("modo") ?></td></tr>
<?php
foreach($cDocencias as $oDocencia) {
	$row = $oDocencia->getTot();
	$array_tipo = $oDocencia->getDatosTipo()->getLista();
	$oAsignatura = new asignaturas\Asignatura($row['id_asignatura']);
	$nombre_corto = $oAsignatura->getNombre_corto();
	$modo=$array_tipo[$row['tipo']];
	$curso_inicio = $row['curso_inicio'];
	$curso_fin = $curso_inicio +1;
	echo "<tr><td>$curso_inicio - $curso_fin</td><td>$nombre_corto</td><td>$modo</td></tr>";
}
?>
</table>
</body>
</html>
