<script>
fnjs_ver_ficha=function(id_menu){
	var filtro_grupo=$('#filtro_grupo').val();
	var url='<?= $url ?>';
	var parametros='id_menu='+id_menu+'&filtro_grupo='+filtro_grupo+'<?= $h2 ?>';
	$.ajax({
		url: url,
		type: 'post',
		data: parametros,
		dataType: 'html'
	})
	.done(function (rta_txt) {
		$('#ficha').html(rta_txt);
	});
}
</script>
<ul>
<?php
$txt = '';
$indice = 1;
$indice_old = 1;
$m = 0;
foreach ($oMenuDbs as $oMenuDb) {
	$m++;
	$id_menu = $oMenuDb->getId_menu();
	$orden = $oMenuDb->getOrden();
	$menu = $oMenuDb->getMenu();
	$parametros = $oMenuDb->getParametros();
	$id_metamenu = $oMenuDb->getId_metamenu();
	$menu_perm = $oMenuDb->getMenu_perm();
	$id_grupmenu = $oMenuDb->getId_grupmenu();
	$ok = $oMenuDb->getOk ();
	
	$txt_ok = empty($ok)? '' : '[ok]';
	//echo "m: $perm_menu,l: $perm_login, ";
	$perm_menu = $oCuadros->lista_txt2($menu_perm);
	// hago las rutas absolutas, en vez de relativas:
	if (!empty($url)) $url = core\ConfigGlobal::getWeb().'/$url';
	// quito las llaves "{}"
	$orden = substr($orden,1,-1);
	//$num_orden=
	$array_orden = preg_split('/,/',$orden);
	$indice = count($array_orden);
	// para poder hcer click si he borrado el monbre
	$menu = empty($menu)? '???'.strtoupper(_("borrado")).'???' : $menu;
	if ($indice == $indice_old) {
			$txt .= "<li>$orden <span class='link' onclick=fnjs_ver_ficha('$id_menu')  >$menu</span> $txt_ok ($perm_menu)";
	} elseif ($indice > $indice_old) {
			$txt .= "<ul><li>$orden <span class='link' onclick=fnjs_ver_ficha('$id_menu')  >$menu</span> $txt_ok ($perm_menu)";
	} else {
		for ($n = $indice; $n < $indice_old; $n++) {
			$txt .= "</li></ul>";
		}
			$txt .= "</li><li>$orden <span class='link' onclick=fnjs_ver_ficha('$id_menu')  >$menu</span> $txt_ok ($perm_menu)";
	}
	$indice_old = $indice;
}
echo $txt;
?>
</li></ul></li></ul>
<form id="frm_menus_3" action="apps/menus/controller/menus_get.php">
	<?= $oHash3->getCamposHtml(); ?>
	<input type="button" onclick="fnjs_enviar_formulario('#frm_menus_3','#ficha');" value="<?= _("nuevo") ?>">
</form>
