<script>
fnjs_lista_menus=function(){
	var filtro_grupo=$('#filtro_grupo').val();
	var url='<?= $url ?>';
	var parametros='filtro_grupo='+filtro_grupo+'<?= $h1 ?>';
	$.ajax({
		data: parametros,
		url: url,
		type: 'post',
		dataType: 'html',
		complete: function (rta) {
			rta_txt=rta.responseText;
			$('#ficha').html(rta_txt);
		}
	});
}
</script>
<table><tr>
<th class=titulo_inv colspan=3><?= _("grupo") ?>:&nbsp;&nbsp;&nbsp;
	<?= $oDespl->desplegable(); ?>
</th>
</tr>
</table>
<div id="ficha"></div>

<?= ucfirst(_("nota")) ?>:<br>
<li><?= _("debe selccionar un grupo de menu para poder añadir un menu.") ?>