<script>
    fnjs_modificar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $(formulario).attr('action', 'frontend/encargossacd/controller/horario_ver.php');
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_borrar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        var seguro;
        if (rta == 1) {
            seguro = confirm("<?= htmlspecialchars((string)$txt_eliminar, ENT_QUOTES, 'UTF-8') ?>");
            if (seguro) {
                $(formulario).attr('action', "frontend/encargossacd/controller/horario_update.php");
                fnjs_enviar_formulario(formulario);
            }
        }
    }
</script>
<table>
    <thead>
    <tr>
        <th class=titulo_inv colspan=5><?= _("horario de") ?>: <?= htmlspecialchars((string)$desc_enc, ENT_QUOTES, 'UTF-8') ?></th>
    <tr>
    </thead>
</table>

<h2 class=subtitulo><?= htmlspecialchars((string)$titulo, ENT_QUOTES, 'UTF-8') ?></h2>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <input type='Hidden' id='mod' name='mod' value=''>
    <input type='Hidden' id='origen' name='origen' value='<?= htmlspecialchars((string)$origen, ENT_QUOTES, 'UTF-8') ?>'>
    <input type='Hidden' id='desc_enc' name='desc_enc' value='<?= htmlspecialchars((string)$desc_enc, ENT_QUOTES, 'UTF-8') ?>'>
    <?= $oTabla->mostrar_tabla() ?>
</form>
<br>
<table class=botones>
    <tr class=botones>
        <td class=botones>
	<span class=cabecera class=link onclick="fnjs_update_div('#<?= htmlspecialchars((string)$div_para_nuevo, ENT_QUOTES, 'UTF-8') ?>','<?= $pagina_nuevo ?>')">
	    <?= _("añadir horario") ?>
	</span></td>
    </tr>
</table>
