<script type="text/javascript">
fnjs_comprobaciones=function(){
	var url='<?= $url ?>';
	var parametros='que=ctr<?= $h ?>';
	$.ajax({
		url: url,
		type: 'post',
		data: parametros,
		dataType: 'html'
	})
	.done(function (rta_txt) {
		alert (rta_txt);
	});
}
</script>
<p><?= _("comprobaciones") ?></p>

<ol>
<li><span class=link onclick="fnjs_comprobaciones()"><?= _("Eliminar encargos de centros inexistentes") ?></span></li>
</ol>

<p><?= _("listados de encargos para cr") ?></p>
<ol>
<!-- NO se puede por que hace referencia a los cargos, que no se tienen.
<li><span class=link onclick="fnjs_update_div('#main','frontend/encargossacd/controller/listas_cl.php')"><?= _("cl sss+ (cr 1/14, 10,c)") ?></span></li>
 -->
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_af ?>')"><?= _("atención ctr sf (cr 1/14, 10,a)") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_a ?>')"><?= _("atención ctr sv (cr 1/14, 10,a)") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_b ?>')"><?= _("atención iglesias, oc y lp (cr 1/14, 10,b)") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_bf ?>')"><?= _("oc y lp sf (cr 1/14, 10,b)") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_c ?>')"><?= _("por sacd (cr 1/14, 10,d)") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_d ?>')"><?= _("tabla por sacd (cr 9/20, 10)") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_df ?>')"><?= _("tabla por sacd sf (cr 9/20, 10)") ?></span></li>
</ol>

<p><?= _("listados comunicaciones") ?></p>
<ol>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_ctr ?>')"><?= _("exigencias ctr sv") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_ctrf ?>')"><?= _("exigencias ctr sf") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_igl ?>')"><?= _("exigencias igl, oc...") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_com_sacd_na ?>')"><?= _("comunicación a sacd Prelatura") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_com_sacd_sss ?>')"><?= _("comunicación a sacd sss+") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_com_ctr_sv ?>')"><?= _("comunicación a los centros sv") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_com_ctr_sf ?>')"><?= _("comunicación a los centros sf") ?></span></li>
<li><span class=link onclick="fnjs_update_div('#main','<?= $url_lista_com_txt ?>')"><?= _("modificar los textos de las comunicaciones") ?></span></li>
</ol>
