<script type="text/javascript">
fnjs_get_texto=function(){
	var clave = $('#clave').val();
	var idioma = $('#idioma').val();

	var url='<?= $url_get ?>';
	var parametros='clave='+clave+'&idioma='+idioma+'<?= $h_get ?>';
	$.ajax({
		url: url,
		type: 'post',
		data: parametros,
		dataType: 'html'
	})
	.done(function (rta_txt) {
		$('#comunicacion').val(rta_txt);
	});
}

fnjs_guardar=function(formulario){
	$(formulario).one("submit", function() {
		$.ajax({
			url: $(this).attr('action'),
			type: 'post',
			data: $(this).serialize()
		})
		.done(function (rta_txt) {
			if (rta_txt != '' && rta_txt != '\n') {
				alert (rta_txt);
			}
		});
		return false;
	});
	$(formulario).trigger("submit");
	$(formulario).off();
}

</script>
<h1><?= _("textos para las comunicaciones") ?></h1>
<form id=textos name=textos action="<?= $url_update ?>" >
<?= $oHash->getCamposHtml() ?>
<table>
<tr><td>
<?= $oDesplClaves->desplegable() ?>
</td><td>
<?= $oDesplIdiomas->desplegable() ?>
</td></tr>
<tr><td colspan=2>
<textarea id="comunicacion" name="comunicacion" cols=100 rows=5><?= htmlspecialchars((string)$comunicacion, ENT_QUOTES, 'UTF-8') ?></textarea>
</td></tr>
<tr><td>
<input type=button onclick="fnjs_guardar(this.form);" value="<?= _("guardar") ?>">
</td></tr>
</table>
</form>
