<script>
fnjs_ver_ficha=function(id_nom,historial){
	var filtro_sacd=$('#filtro_sacd').val();
	if (!id_nom ) { var id_nom=$('#lst_sacds').val(); }

	if (id_nom ) {
		var url='<?= $url_get ?>';
		var parametros='filtro_sacd='+filtro_sacd+'&id_nom='+id_nom+'&historial='+historial+'<?= $h_get ?>';
		$.ajax({
			url: url,
			type: 'post',
			data: parametros,
			dataType: 'html'
		})
		.done(function (rta_txt) {
			$('#ficha').html(rta_txt);
		});
	}
}

fnjs_lista_sacd=function(id_nom){
	var filtro_sacd=$('#filtro_sacd').val();

    var url='<?= $url_ajax ?>';
	var parametros='que=get_select&filtro_sacd='+filtro_sacd+'&id_nom='+id_nom+'<?= $h_lista ?>';
	$.ajax({
		url: url,
		type: 'post',
		data: parametros,
		dataType: 'html'
	})
	.done(function (rta_txt) {
		$('#sacds').html(rta_txt);
	});
}

fnjs_horario=function(id_enc){
	var filtro_sacd=$('#filtro_sacd').val();
	var id_nom=$('#lst_sacds').val();
    var url='<?= $url_horario ?>';
	var parametros='filtro_sacd='+filtro_sacd+'&id_enc='+id_enc+'&id_nom='+id_nom+'<?= $h_horario ?>';
    $.ajax({
        url: url,
        type: 'post',
        data: parametros,
        dataType: 'html'
    })
    .done(function (rta_txt) {
        $('#ficha').html(rta_txt);
    });
}
</script>

<table>
<thead>
<tr><th colspan=4><?= _("otros encargos y ausencias") ?></th></tr>
<tr>
<th><?= _("tipo") ?>:&nbsp;&nbsp;&nbsp;
<?= $oDesplFiltroSacd->desplegable() ?>
</th>
<th colspan=3 id="sacds"><?= _("sacd") ?>:&nbsp;&nbsp;&nbsp;
	<select class=contenido id="lst_sacds" onchange="fnjs_ver_ficha();">
	</select>
</th></tr>
</thead>
</table>
<div class=contenido id="ficha" ></div>
