<style>
    div.salta_pag {
        clear: both;
        display: block;
        width: 17cm;
        page-break-after: always;
        font-family: 'Arial', serif;
        font-size: 12pt;
    }

    table {
        width: 17cm;
    }

    table {
        border: 1px solid #000;
        border-collapse: collapse;
        margin: 0;
        margin-bottom: 1em;
        padding: 6px;
    }

    td {
        border-collapse: collapse;
    }

    td.cabecera {
        text-align: center;
        font-weight: bold;
    }

    td.cabecera_izq {
        text-align: left;
        font-weight: bold;
    }

    td.centro {
        text-align: center;
    }

    p {
        margin: 0;
    }

    otros {
        font-weight: bold;
        margin-left: 0;
    }

    comunicacion {
        display: block;
        padding-left: 15mm;
        padding-right: 10mm;
        padding-top: 10mm;
        padding-bottom: 10mm;
    }

    izquierda {
        display: block;
        float: left;
        text-align: left;
    }

    derecha {
        display: block;
        float: right;
        text-align: right;
    }

    cabecera {
        display: block;
    }

    pie {
        display: block;
    }

</style>
<div id='exportar' refe='encargossacd/view/lista_com_sacd.phtml'>
    <span id="span_exportar" title="comunicacion_encargos_sacd"></span>
    <?php
    // sacd
    use core\ConfigGlobal;

    $s = 0;
    foreach ($array_modo as $array_modo_sacd) {
        $s++;
        ?>
        <div class="salta_pag" id="<?= $s ?>">
            <br/>
            <cabecera>
                <izquierda><?= $array_modo[$s]['nom_ap'] ?></izquierda>
                <?php if ($Qsel == "nagd") { ?>
                    <derecha>vc-<?= ConfigGlobal::mi_delef() ?></derecha>
                <?php } ?>
            </cabecera>
            <comunicacion>
                <?php echo $array_modo[$s]['txt']['com_sacd']; ?>
            </comunicacion>
            <?php
            //  Encargos
            if (is_array($array_modo_sacd)) {
            ksort($array_modo_sacd);
            if (!empty($array_modo_sacd['grupo'])) {
            foreach ($array_modo_sacd['grupo'] as $grupo => $vector) {
            switch ($grupo) {
            case 1:
                $modo_txt = _("coordinador");
                break;
            case 2:
            // Html: se pone el estilo inLine, porque al copiar y pegar no pilla el css.
            ?>
            <table class=titular border=1 style="border-collapse:collapse;">
                <tr>
                    <td class=cabecera_izq><?= $array_modo[$s]['txt']["t_titular"] ?></td>
                    <td class=cabecera><?= $array_modo[$s]['txt']["t_secc"] ?></td>
                    <td class=cabecera><?= $array_modo[$s]['txt']["t_mañanas"] ?></td>
                    <td class=cabecera><?= $array_modo[$s]['txt']["t_tardes1"] ?></td>
                    <td class=cabecera><?= $array_modo[$s]['txt']["t_tardes2"] ?></td>
                    <td class=cabecera_izq><?= $array_modo[$s]['txt']["t_suplente"] ?></td>
                </tr>
                <?php
                break;
                case 3:
                /* cambio 13.8.07 */
                /*
                <table class=colaborador>
                <tr><td class=cabecera_izq><?= $array_modo[$s]['txt']["t_colaborador"] ?></td>
                    <td class=cabecera><?= $array_modo[$s]['txt']["t_secc"] ?></td>
                </tr>
                */
                ?>
                <table class=colaborador border=1 style="border-collapse:collapse;">
                    <tr>
                        <td class=cabecera_izq><?= $array_modo[$s]['txt']["t_colaborador"] ?></td>
                        <td class=cabecera><?= $array_modo[$s]['txt']["t_secc"] ?></td>
                        <td class=cabecera><?= $array_modo[$s]['txt']["t_mañanas"] ?></td>
                        <td class=cabecera><?= $array_modo[$s]['txt']["t_tardes1"] ?></td>
                        <td class=cabecera><?= $array_modo[$s]['txt']["t_tardes2"] ?></td>
                    </tr>
                    <?php
                    break;
                    case 4:
                    ?>
                    <table class=suplente border=1 style="border-collapse:collapse;">
                        <tr>
                            <td class=cabecera_izq><?= $array_modo[$s]['txt']["t_suplente"] ?></td>
                            <td class=cabecera><?= $array_modo[$s]['txt']["t_secc"] ?></td>
                            <td class=cabecera_izq><?= $array_modo[$s]['txt']["t_titular"] ?></td>
                        </tr>
                        <?php
                        break;
                        case 6:
                            ?>
                            <otros><?= $array_modo[$s]['txt']["t_otros"] ?></otros>
                            <?php
                            break;
                        }
                        if (is_array($vector)) {
                            foreach ($vector as $enc) {
                                switch ($grupo) {
                                    case 6:
                                        echo "<p>{$enc['desc_enc']}: {$enc['dedic_m']}.</p>";
                                        break;
                                    case 7:
                                        if ($observ = $enc['desc_enc']) {
                                            echo "<otros>" . $array_modo[$s]['txt']["t_observ"] . "</otros>";
                                            echo "<p>$observ</p>";
                                        }
                                        break;
                                    default:
                                        ?>
                                        <tr>
                                            <td><?= $enc['nombre_ubi'] ?></td>
                                            <td class=centro><?= $enc['seccion'] ?></td>
                                            <?php if ($grupo == 2 || $grupo == 3) { ?>
                                                <td class=centro><?= $enc['dedic_m'] ?></td>
                                                <td class=centro><?= $enc['dedic_t'] ?></td>
                                                <td class=centro><?= $enc['dedic_v'] ?></td>
                                            <?php } ?>
                                            <td width=50%><?= $enc['sup_tit'] ?></td>
                                        </tr>
                                    <?php
                                }
                            }
                        }
                        ?>
                    </table>
                    <?php
                    }
                    }
                    }
                    ?>
                    <pie>
                        <derecha><?= $lugar_fecha ?></derecha>
                    </pie>
        </div>
        <?php
    }
    ?>
</div>
