<script>
fnjs_busca_ctrs=function(){
    var id_zona=$('#lst_zonas').val();
    if (id_zona) {
        var url='<?= $url_ajax_lista ?>';
        var parametros='id_zona='+id_zona+'<?= $h_ctr ?>';
        fnjs_ajax_json_html({ url: url, data: parametros, target: '#lst_ctrs' });
    }
}
fnjs_guardar=function(formulario){
    let datos = $(formulario).serialize();
    $.ajax({ url: '<?= $url_ajax_update ?>', type: 'post', data: datos, dataType: 'json' })
        .done(function (json) {
            if (!json || json.success !== true) {
                alert(<?= json_encode(_("respuesta") . ": ") ?> + (json ? json.mensaje : ''));
            }
            fnjs_busca_ctrs();
        });
}
fnjs_left_side_hide();
</script>
<form id="frm_zona_ctr" name="frm_zona_ctr" action="" method="post">
<?= $oHash->getCamposHtml() ?>
<table>
<thead>
<th class=titulo_inv colspan=4><?= ucfirst(_("lista de centros de la zona")) ?>:&nbsp;&nbsp;&nbsp;
<select class=contenido id="lst_zonas" onchange="fnjs_busca_ctrs()">
    <option></option>
    <option value="no"><?= _("sin asignar zona") ?></option>
    <?php if ($perm_des) { ?><option value="no_sf"><?= _("sin asignar zona sf") ?></option><?php } ?>
    <?= $oDesplZonas->options() ?>
</select></th></tr>
</thead>
<tbody>
<tr><td colspan=4><div class=contenido id="lst_ctrs"></div></td></tr>
<?php if ($perm_des) { ?>
    <tr>
    <th class=titulo_inv colspan=3><?= _("asignar los centros marcados a la zona") ?>:&nbsp;&nbsp;&nbsp;
    <select class=contenido id="id_zona_new" name="id_zona_new" >
    <option></option>
    <?= $oDesplZonas->options() ?>
    <option value="no"><?= _("sin asignar zona") ?></option>
    </th>
    <th><input type="button" id="ok" name="ok" onclick="fnjs_guardar(this.form);" value="<?= _("asignar") ?>"></th>
    </tr>
<?php } ?>
</tbody>
</table>
</form>
