<script>
    fnjs_actas = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $(formulario).attr('action', "frontend/actividadestudios/controller/acta_notas.php");
            fnjs_enviar_formulario(formulario, '<?= $bloque ?>');
        }
    }
    fnjs_modificar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#seleccionados' + ' input.sel').each(function () {
                if ($(this).prop('checked') === true) {
                    var array_dir = $(this).val().split('#');
                    permiso = array_dir[2];
                }
            });
            if (permiso === 'false') {
                alert(<?= json_encode((string)$txt_no_permiso) ?>);
            } else {
                $('#mod').val("editar");
                $(formulario).attr('action', "<?= $url_form ?>");
                fnjs_enviar_formulario(formulario, '<?= $bloque ?>');
            }
        }
    }
    fnjs_borrar_asignatura = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#seleccionados' + ' input.sel').each(function () {
                if ($(this).prop('checked') === true) {
                    var array_dir = $(this).val().split('#');
                    permiso = array_dir[2];
                }
            });
            if (permiso === 'false') {
                alert(<?= json_encode((string)$txt_no_permiso) ?>);
            } else {
                if (confirm(<?= json_encode((string)$txt_eliminar) ?>)) {
                    $('#mod').val("eliminar");
                    var datos = $(formulario).serialize();
                    $.ajax({
                        data: datos,
                        url: '<?= $url_actividad_asignatura_eliminar ?>',
                        method: 'POST',
                        dataType: 'json'
                    }).done(function (json) {
                        if (json.success !== true) {
                            alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
                        } else {
                            fnjs_actualizar(formulario);
                        }
                    });
                }
            }
        }
    }
    fnjs_actualizar = function (formulario) {
        var campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "frontend/dossiers/controller/dossiers_ver.php");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#main');
    }
    fnjs_left_side_show();
</script>
<h2 class=titulo><?= ucfirst(_("relación de asignaturas")) ?></h2>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHashSelect->getCamposHtml(); ?>
    <input type='hidden' id='mod' name='mod' value=''>
    <?= $oTabla->mostrar_tabla(); ?>
</form>
<?php if (!empty($link_insert)) { ?>
    <br>
    <table cellspacing=3 class=botones>
        <tr class=botones>
            <td class=botones><span class=link_inv onclick="fnjs_update_div('<?= $bloque ?>','<?= $link_insert ?>');">
                <?= sprintf(_("añadir asignatura")) ?></span></td>
        </tr>
    </table>
<?php } ?>
