<div id="div_select_zona" class="no_print">
    <table>
        <tr>
            <th class="titulo_inv" colspan="6">
                <?= _('plan de misas de un centro') ?>
            </th>
        </tr>
        <tr>
            <td>
                <?= ucfirst(_('Periodo')) ?>:&nbsp;&nbsp;&nbsp;
            </td>
            <?= $periodo_td_html ?>
        </tr>
    </table>
</div>

<br>
<div id="div_cuadricula">
</div>

<script>
    fnjs_buscar_plan_ctr = function () {
        let id_zona = $('#id_zona').val();
        let url = '<?= htmlspecialchars($url_buscar_plan_ctr, ENT_QUOTES, 'UTF-8') ?>';
        if (id_zona) {
            let parametros = 'id_zona=' + encodeURIComponent(id_zona) + '<?= $h_buscar_plan_ctr ?>';
            $.ajax({
                url: url,
                type: 'post',
                data: parametros,
                dataType: 'html'
            })
                .done(function (rta_txt) {
                    $('#main').html(rta_txt);
                });
        }
    };

    fnjs_ver_plan_ctr = function () {
        let id_ubi = '<?= htmlspecialchars($id_ubi_centro, ENT_QUOTES, 'UTF-8') ?>';
        if (id_ubi) {
            let url = '<?= htmlspecialchars($url_ver_plan_ctr, ENT_QUOTES, 'UTF-8') ?>';
            var periodo = $('#periodo').val();
            var empiezamax = $('#empiezamax').val();
            var empiezamin = $('#empiezamin').val();
            let parametros = 'id_zona=&id_ubi=' + encodeURIComponent(id_ubi)
                + '&periodo=' + encodeURIComponent(periodo)
                + '&empiezamin=' + encodeURIComponent(empiezamin)
                + '&empiezamax=' + encodeURIComponent(empiezamax)
                + '<?= $h_plan_ctr ?>';
            $.ajax({
                url: url,
                type: 'post',
                data: parametros,
                dataType: 'html'
            })
                .done(function (rta_txt) {
                    $('#div_cuadricula').html(rta_txt);
                });
        }
    };
    $(document).ready($('#periodo').change(function () {
        funjs_activar_fecha();
        fnjs_ver_plan_ctr();
    }));
    $(document).ready($('#empiezamin').change(function () {
        funjs_activar_fecha();
        fnjs_ver_plan_ctr();
    }));
    $(document).ready($('#empiezamax').change(function () {
        funjs_activar_fecha();
        fnjs_ver_plan_ctr();
    }));
    fnjs_ver_plan_ctr();
</script>
