<input type='button' value="<?= _('quitar el actual') ?>"
       onclick="fnjs_quitar_horario('<?= $param_quitar ?>');">
<hr>

<div class="input-group clockpicker">
    <label for="t_start"><?= _('Inicio') ?></label>
    <input id="t_start" type="text" class="form-control" size="3" value="<?= htmlspecialchars((string)$t_start, ENT_QUOTES, 'UTF-8') ?>" style="float: right;">
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-time"></span>
    </span>
</div>
<div class="input-group clockpicker" style="margin-top: 10px;">
    <label for="t_end"><?= _('Fin') ?></label>
    <input id="t_end" type="text" class="form-control" size="3" value="<?= htmlspecialchars((string)$t_end, ENT_QUOTES, 'UTF-8') ?>" style="float: right;">
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-time"></span>
    </span>
</div>
<hr>
<input type='button' value="<?= _('guardar') ?>" onclick="fnjs_guardar_horario('<?= $param_guardar ?>');">

<script type="text/javascript">
    $('.clockpicker').clockpicker({
            placement: 'bottom',
            align: 'right',
            donetext: 'Correcto!'
        }
    );
</script>
