<h2><?= _("Planing de Misas") ?></h2>
<ul>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goModificarPlantilla ?>')">
            <?= _("Modificar plantilla") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goPrepararPlanDeMisas ?>')">
            <?= _("Preparar nuevo plan de Misas y encargos") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goModificarPlanDeMisas ?>')">
            <?= _("Modificar el plan de Misas y encargos") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goVerPlanDeMisas ?>')">
            <?= _("Ver el plan de Misas y encargos de una zona") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goStatus ?>')">
            <?= _("Modificar estado del plan de Misas") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goBuscarPlanSacd ?>')">
            <?= _("Ver el plan de un sacerdote") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goBuscarPlanCtr ?>')">
            <?= _("Ver el plan de Misas y encargos de un centro") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goModificarEncargos ?>')">
            <?= _("Crear y modificar los encargos") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goModificarEncargosCtr ?>')">
            <?= _("Modificar los encargos visibles para un centro") ?>
        </span>
    </li>
    <li>
        <span class="link" onclick="fnjs_update_div('#main','<?= $goIniciales ?>')">
            <?= _("Modificar la tabla de iniciales de los sacerdotes") ?>
        </span>
    </li>
</ul>
