<div id="div_select_zona">
    <form id="frm_zona_ctr" name="frm_zona_ctr" action="" method="post">
        <table>
            <thead>
                <tr>
                    <th class="titulo_inv" colspan="4">
                        <?= ucfirst(_("Iniciales sacerdotes de la zona")) ?>:&nbsp;&nbsp;&nbsp;
                        <?= $oDesplZonas->desplegable() ?>
                    </th>
                </tr>
            </thead>
        </table>
    </form>
</div>

<br>
<div id="div_iniciales">
</div>

<script>
    fnjs_ver_iniciales_sacd_zona = function () {
        let id_zona = $('#id_zona').val();
        if (id_zona) {
            let url = '<?= $url_ver_iniciales_zona ?>';
            let parametros = 'id_zona=' + id_zona + '<?= $h_zona ?>';

            $.ajax({
                url: url,
                type: 'post',
                data: parametros,
                dataType: 'html'
            })
                .done(function (rta_txt) {
                    $('#div_iniciales').html(rta_txt);
                });
        }
    }
</script>
