<div id="div_select_zona">
    <form id="frm_zona_ctr" name="frm_zona_ctr" action="" method="post">
        <table>
            <thead>
            <tr>
                <th class=titulo_inv colspan=4><?= ucfirst(_('Encargos de la zona')) ?>:&nbsp;&nbsp;&nbsp;
                    <?= $oDesplZonas->desplegable() ?>
                </th>
            </tr>
            </thead>
        </table>
    </form>
</div>

<br>
<div id="div_encargos">
</div>

<script>
    fnjs_ver_encargos_centros = function () {
        let id_zona = $('#id_zona').val();
        if (id_zona) {
            let url = '<?= $url_ver_encargos_centros ?>';

            let parametros = 'id_zona=' + id_zona + '<?= $h_zona ?>';

            fnjs_ajax_json_html({ url: url, data: parametros, target: '#div_encargos' });
        }
    }
    fnjs_ver_encargos_centros();
</script>
