<div id="div_select_zona" class="no_print">
    <form id="frm_zona_ctr" name="frm_zona_ctr" action="" method="post">
        <?= $oHash->getCamposHtml() ?>
        <table>
            <thead>
            <tr>
                <th class="titulo_inv" colspan="12">
                    <?= ucfirst(_('Ver Plan de Misas')) ?>
                </th>
            </tr>
            <tr>
                <th class="titulo_inv" colspan="4"><?= ucfirst(_('Plan de Misas de la zona')) ?>:&nbsp;&nbsp;&nbsp;
                    <?= $oDesplZonas->desplegable() ?>
                </th>
                <th class="titulo_inv" colspan="4"><?= ucfirst(_('Orden')) ?>:&nbsp;&nbsp;&nbsp;
                    <?= $oDesplOrden->desplegable() ?>
                </th>
            </tr>
            <tr>
                <td>
                    <?= ucfirst(_('Periodo')) ?>:&nbsp;&nbsp;&nbsp;
                </td>
                <?= $periodo_td_html ?>
            </tr>
            </thead>
        </table>
    </form>
</div>

<br>
<div id="div_cuadricula">
</div>

<script>
    fnjs_ver_cuadricula_zona = function () {
        let id_zona = $('#id_zona').val();
        if (id_zona) {
            let url = '<?= htmlspecialchars($url_ver_cuadricula_zona, ENT_QUOTES, 'UTF-8') ?>';
            var periodo = $('#periodo').val();
            var empiezamax = $('#empiezamax').val();
            var empiezamin = $('#empiezamin').val();
            let orden = $('#orden').val();
            let parametros = 'id_zona=' + encodeURIComponent(id_zona) + '&periodo=' + encodeURIComponent(periodo)
                + '&empiezamin=' + encodeURIComponent(empiezamin) + '&empiezamax=' + encodeURIComponent(empiezamax)
                + '&orden=' + encodeURIComponent(orden) + '&tipo_plantilla=p<?= $h_zona_periodo ?>';
            $.ajax({
                url: url,
                type: 'post',
                data: parametros,
                dataType: 'html'
            })
                .done(function (rta_txt) {
                    $('#div_cuadricula').html(rta_txt);
                });
        }
    };

    $(document).ready($('#periodo').change(function () {
        funjs_activar_fecha();
        fnjs_ver_cuadricula_zona();
    }));
    $(document).ready($('#empiezamin').change(function () {
        funjs_activar_fecha();
        fnjs_ver_cuadricula_zona();
    }));
    $(document).ready($('#empiezamax').change(function () {
        funjs_activar_fecha();
        fnjs_ver_cuadricula_zona();
    }));
    fnjs_ver_cuadricula_zona();
</script>
