<script>
    fnjs_mod_cargo = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#mod').val("editar");
            $(formulario).attr('action', "apps/actividadcargos/controller/form_3102.php");
            fnjs_enviar_formulario(formulario, '<?= $bloque ?>');
        }
    }
    fnjs_borrar_cargo = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            if (confirm("<?= $txt_eliminar ?>")) {
                $('#mod').val("eliminar");
                $(formulario).attr('action', "apps/actividadcargos/controller/update_3102.php");
                $(formulario).one("submit", function () {
                    $.ajax({
                        url: $(this).attr('action'),
                        type: 'post',
                        data: $(this).serialize()
                    })
                        .done(function (rta_txt) {
                            if (rta_txt !== '' && rta_txt !== '\\n') {
                                alert('<?= _("respuesta") ?>: ' + rta_txt);
                            } else {
                                fnjs_actualizar(formulario);
                            }
                        });
                    return false;
                });
                $(formulario).trigger("submit");
                $(formulario).off();
            }
        }
    }
    fnjs_actualizar = function (formulario) {
        var campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "apps/dossiers/controller/dossiers_ver.php");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#main');
    }
</script>
<h2 class="titulo"><?= ucfirst(_("relación de cargos")) ?></h2>
<form id="frm_3102" name="frm_3102" action="" method="post">
    <?= $oHashSelect->getCamposHtml(); ?>
    <input type='hidden' id='mod' name='mod' value=''>

    <?= $oTabla->mostrar_tabla(); ?>
</form>

<!--  boton insert  -->
<br>
<table cellspacing=3 class="botones">
    <tr class="botones">
        <th width=25 align=RIGHT><?= _("dl") ?>:</th>
        <?php foreach ($aLinks_dl as $nom => $pagina) { ?>
            <td class="botones"><span class=link_inv
                                      onclick="fnjs_update_div('<?= $bloque ?>','<?= $pagina ?>');"><?= $nom ?></span>
            </td>
        <?php } ?>
    </tr>
</table>
