<?php use core\ConfigGlobal; ?>

<?= $oPosicion->mostrar_left_slide(1); ?>
<div id="top" name="top">
    <table>
        <tr>
            <td class=esquerra nowrap></td>
            <td>
                <span class=link onclick=fnjs_update_div('#main','<?= $godossiers ?>')><img
                            src=<?= ConfigGlobal::getWeb_icons() ?>/dossiers.gif border=0 width=40 height=40
                            alt='<?= _("ver dossiers") ?>'>(<?= _("dossiers") ?>)</span>
            <td class=titulo><span class=link onclick=fnjs_update_div('#main','<?= $gohome ?>')><?= $titulo ?></span>
            </td>
            <td class=contenido>(<?= $dl ?> - <?= $ctr ?>)</td>
        </tr>
    </table>
    <table border=1>
        <tr>
            <td class=etiqueta>nacimiento</td>
            <td class=contenido><?= $f_nacimiento ?></td>
            <td class=etiqueta>santo</td>
            <td class=contenido><?= $santo ?></td>
            <td class=etiqueta>celebra</td>
            <td class=contenido><?= $celebra ?></td>
        </tr>
        <tr>
            <td class=etiqueta>profesion</td>
            <td class=contenido colspan=3><?= $profesion ?></td>
            <td class=etiqueta>stgr</td>
            <td class=contenido><?= $stgr ?></td>
        </tr>
        <tr>
            <td colspan=2>telfs: <?= $telfs ?></td>
            <td colspan=4>e-mail: <?= $mails ?></td>
        </tr>
        <tr class=tab>
            <td colspan=6 onclick="fnjs_update_div('#main','<?= $go_ficha ?>');"><?= _("editar") ?></td>
        </tr>
    </table>
</div>
<div id="ficha_otra" style="margin-top: 1em">
    <?php
    include("apps/dossiers/controller/lista_dossiers.php");
    ?>
</div>