<?php

$campos_chk = 'permiso_lectura!permiso_escritura';

$oHash = new web\Hash();
$oHash->setcamposForm('id_tipo_dossier!id_tipo_dossier_rel!tabla_from!tabla_to!campo_to!descripcion!depende_modificar');
$oHash->setcamposNo('que!'.$campos_chk);
$a_camposHidden = array(
		'campos_chk'=>$campos_chk,
		);
$oHash->setArraycamposHidden($a_camposHidden);

?>
<form id='frm2' >
<?= $oHash->getCamposHtml(); ?>
<input type="Hidden" id="que"  name="que" value="">

<table>
<th align="left" colspan="5"><?php echo ucfirst(_("Permisos de acceso a dossier seleccionado")); ?></th>

<?php if ($_SESSION['oPerm']->have_perm("admin_sv") OR $_SESSION['oPerm']->have_perm("admin_sf")) { ?> 
<tr>
   	<td><font ><?php echo _("id_tipo_dossier"); ?></font><input name="id_tipo_dossier" value="<?php echo $id_tipo_dossier; ?>"size="10"> </td>
	<td><font ><?php echo _("id_tipo_dossier_rel"); ?></font><input name="id_tipo_dossier_rel"  value="<?php echo $id_tipo_dossier_rel ; ?>" size="10"></td>
</tr>

<tr>
	<td><font ><?php echo _("permiso_lectura"); ?></font><input name="permiso_lectura"  value="<?php echo $permiso_lectura; ?>" size="10"> </td>
	<td><font ><?php echo _("permiso_escritura"); ?></font><input name="permiso_escritura"  value="<?php echo $permiso_escritura; ?>" size="10"></td>
</tr>
<tr>
	<td><font ><?php echo _("tabla_from"); ?> </font><input name="tabla_from"  value="<?php echo $tabla_from; ?>" size="10"> </td>
	<td><font ><?php echo _("tabla_to"); ?> </font><input name="tabla_to"  value="<?php echo $tabla_to; ?>" size="15"> </td>
	<td><font ><?php echo _("campo_to"); ?> </font><input name="campo_to"  value="<?php echo $campo_to; ?>" size="10"> </td>
</TR>
<?php } 
?>
<tr>	
	<td colspan=3><font ><?php echo _("descripción"); ?> </font><input name="descripcion"  value="<?php echo $descripcion; ?>" size="40"> </td>
</TR>
<tr>
   	<td><font ><?php echo _("depende_modificar"); ?></font><input name="depende_modificar" value="<?php echo $depende_modificar; ?>"size="10"> </td>
</tr>
<tr>
<td colspan="2"><?php echo ucfirst(_("depende_modificar=t implica que sólo podrá modificar la oficina correspondiente: agd para los agd, sm para los n, sg para los s, en dossiers que afectan a varios tipos de personas")); ?></td>
</tr>
</table>
<?php
$nomcamp="permiso_lectura";
$bin=$permiso_lectura;
?>
<table>
<tr>
<?php
echo _("permisos de lectura");
echo "<br>";
//llamada a la función que genera los cuadros de permisos de lectura
cuadros_perm_doss($nomcamp,$bin);  
echo "<br>";
?>
</tr>
<tr>
<?php
$nomcamp="permiso_escritura";
$bin=$permiso_escritura;
echo _("permisos de escritura");
echo "<br>";
//llamada a la función que genera asimismo los cuadros de permiso de escritura
cuadros_perm_doss($nomcamp,$bin);  
?>
<br>
</tr>				
</table>
<?php
// -----------------------------------  Botones  ----------------------
if (!empty($botones)) {
	echo "<table><tr class=botones>";
	$b=strtok($botones,",");
	while ($b) {
		if ($b==1){
			$txt_g=ucwords(_("guardar cambios"));
			echo "<th class='link_inv' onclick='fnjs_guardar()'>$txt_g</th>"; }
		if ($b==2){
			$txt_e=ucwords(_("eliminar"));
			echo "<th class='link_inv' onclick='fnjs_eliminar()'>$txt_e</th>"; }
		$b=strtok(",");
	} 
	echo "</tr></table><br>";
}
// fin ----------------------------  Botones  ----------------------
?>
</form>
