<script>
fnjs_buscar=function(){
	$('#frm_buscar').attr('action',"apps/usuarios/controller/grupo_lista.php");
	fnjs_enviar_formulario('#frm_buscar');
}
fnjs_modificar=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
  		$(formulario).attr('action',"apps/usuarios/controller/grupo_form.php");
  		fnjs_enviar_formulario(formulario);
  	}
}
fnjs_eliminar=function(formulario){
	rta=fnjs_solo_uno('#seleccionados');
	if (rta==1) {
		if (confirm("<?= _("¿Esta seguro que desea borrar este grupo?");?>") ) {
			var url='<?= core\ConfigGlobal::getWeb() ?>/apps/usuarios/controller/usuario_ajax.php';
			$('#que').val('eliminar_grupo');
			$('#seleccionados').submit(function() {
				$.ajax({
					url: url,
					type: 'post',
					data: $(this).serialize(),
					complete: function (rta) {
						rta_txt=rta.responseText;
						if (rta_txt != '' && rta_txt != '\n') {
							alert ('respuesta: '+rta_txt);
						}
					},
					success: function() { fnjs_actualizar() }
				});
				return false;
			});
			$('#seleccionados').submit();
			$('#seleccionados').off();
		}
	}
}
fnjs_actualizar=function(){
	var url='<?= web\Hash::link(core\ConfigGlobal::getWeb().'/apps/usuarios/controller/grupo_lista.php'); ?>';
	fnjs_update_div('#main',url);
}
</script>
<h3>Buscar grupo</h3>
<form id=frm_buscar  name=frm_buscar action="" method="post" onkeypress="fnjs_enviar(event,this);" >
<?= $oHashBuscar->getCamposHtml(); ?>
<?= ucfirst(_("nombre")) ?>:<input type=text name=Qusername value="<?= $username ?>">
<input type="button" onclick="fnjs_buscar();" id="ok" name="ok" value="<?= ucfirst(_("buscar")); ?>" class="btn_ok">
</form>
<br>
<form id="seleccionados"  name="seleccionados" action="" method="post" >
	<?= $oHashSelect->getCamposHtml(); ?>
	<input type="hidden" id="que"  name="que" value="">
	<?= $oTabla->mostrar_tabla(); ?>
</form>
<br>
<?php if ($permiso == 1) { ?>
<table><tr><th class="no_print">
	<span class="link_inv" onclick="fnjs_update_div('#main','<?= $url_nuevo ?>');"><?= core\strtoupper_dlb(_("nuevo grupo")) ?></span>
</th></tr></table>
<?php } ?>