<script>
fnjs_guardar=function(formulario){
	var rr=fnjs_comprobar_campos(formulario,'<?= addslashes($obj) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok') {
		$('#user_que').val('<?= $user_que ?>');
		$(formulario).attr('action',"apps/usuarios/controller/usuario_update.php");
		$(formulario).one("submit", function() {
			$.ajax({
				url: $(this).attr('action'),
				type: 'post',
				data: $(this).serialize()
			})
			.done(function (rta_txt) {
				if (rta_txt != '' && rta_txt != '\\n') {
					alert ('<?= _("respuesta") ?>: '+rta_txt);
				} else {
					<?= $oPosicion->js_atras(1); ?>
				}
			});
			return false;
		});
		$(formulario).trigger("submit");
		$(formulario).off();
	}
}
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h3><?= _("grupo") ?>: <?= $usuario ?></h3>
<form id="frm_usuario"  name="frm_usuario" action="" method="post" >
<?= $oHashG->getCamposHtml(); ?>
<input type=hidden id=user_que  name=que value="">
<br>
<?= ucfirst(_("nombre")) ?>:<input type=text name=usuario value="<?= $usuario ?>">
<br>
<input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
<br>
</form>
