<script>
fnjs_add_perm=function(que){
	if (que=='menu'){
		$('#frm_usuario').attr('action',"apps/usuarios/controller/usuario_perm_menu.php");
	}
	if (que=='activ'){
		$('#frm_usuario').attr('action',"apps/usuarios/controller/usuario_perm_activ.php");
	}
	fnjs_enviar_formulario('#frm_usuario');
}
fnjs_del_perm_menu=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= _("¿Está seguro?") ?>")) {
			$('#que').val("perm_menu_eliminar");
			$(formulario).attr('action',"apps/usuarios/controller/usuario_update.php");
			$(formulario).submit(function() {
				$.ajax({
					data: $(this).serialize(),
					url: $(this).attr('action'),
					type: 'post',
					complete: function (rta) {
						rta_txt = rta.responseText;
						if (rta_txt != '' && rta_txt != '\\n') {
							alert ('<?= _("respuesta") ?>: '+rta_txt);
						}
					},
					success: function() { fnjs_actualizar(formulario) }
				});
				return false;
			});
			$(formulario).submit();
			$(formulario).off();
		}
	}
}
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$(formulario).attr('action',"apps/usuarios/controller/grupo_form.php");
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}
</script>
<br>
<h4><?= ucfirst(_("permisos de menús")) ?>:</h4>
<form id="permisos_menu" name="permisos_menu" action="">
<?= $oHashPermisos->getCamposHtml(); ?>
<input type="hidden" id="que" name="que" value="">
<?= $oTabla->mostrar_tabla(); ?>
<br>
<input type=button onclick="fnjs_add_perm('menu');" value="<?= _("añadir permiso") ?>">
</form>