<?php

use actividades\model\entity\GestorTipoDeActividad;
use procesos\model\PermAccion;
use procesos\model\entity\GestorActividadFase;

// propios
$i=0;
/**
 * Para la tabla slickGrid, el width debe ser en pixels
 * No hay que poner unidades, pues da un error de javascript.
 * Al final obligo a que la tabla sea html.
 * 
 * @var array $a_cabeceras
 */
$a_cabeceras = [ ['name' => _("dl propia"), 'width' => '5%'],
                 ['name' => _("tipo de actividad"), 'width' => '10%'],
                 ['name' => _("afecta a"), 'width' => '20%'],
                 ['name' => _("fase de referencia"), 'width' => '30%'],
                 ['name' => _("permiso off"), 'width' => '20%'],
                 ['name' => _("permiso on"), 'width' => '20%'],
               ];
                
$a_botones = [];
$a_botones[] = array('prefix' => 'perm', 'txt' => _("modificar"), 'click' =>"fnjs_mod_perm_activ(\"#permisos_activ\")" );
$a_botones[] = array('prefix' => 'perm', 'txt' => _("eliminar"), 'click' =>"fnjs_del_perm_activ(\"#permisos_activ\")" ); 

$oAcciones = new PermAccion();
$aOpcionesAction = $oAcciones->lista_array();
$a_valores=array();
$id_tipo_activ_anterior = '';
$dl_propia_anterior = '';
foreach ($cUsuarioPerm as $oUsuarioPerm) {
    $i++;
    $id_item=$oUsuarioPerm->getId_item();
    $id_tipo_activ_txt=$oUsuarioPerm->getId_tipo_activ_txt();
    $dl_propia=$oUsuarioPerm->getDl_propia();
    $fase_ref=$oUsuarioPerm->getFase_ref();
    $afecta_a=$oUsuarioPerm->getAfecta_a();
    $perm_on=$oUsuarioPerm->getPerm_on();
    $perm_off=$oUsuarioPerm->getPerm_off();
    
    if ($dl_propia=='t') {
        if (substr($id_tipo_activ_txt, 0, 1) == 1) { //sv
            $dl_propia_txt = core\ConfigGlobal::mi_dele();
        } else { //sf
            if (substr($id_tipo_activ_txt, 0, 1) == '.') { //sf y sv
                $dl_propia_txt = core\ConfigGlobal::mi_dele().' - '.core\ConfigGlobal::mi_dele().'f';
            } else {
                $dl_propia_txt = core\ConfigGlobal::mi_dele().'f';
            }
        }
    } else {
        $dl_propia_txt = _("otras");
    }

    $oTipoActividad = new web\TiposActividades($id_tipo_activ_txt);
    $id_tipo_activ = $oTipoActividad->getId_tipo_activ();
    
    $GesTiposActiv = new GestorTipoDeActividad();
    $aTiposDeProcesos = $GesTiposActiv->getTiposDeProcesos($id_tipo_activ,$dl_propia);
    
    $oGesFases= new GestorActividadFase();
    $aFases = $oGesFases->getArrayFasesProcesos($aTiposDeProcesos);
    $fase_ref_txt = array_search($fase_ref, $aFases);
    
    if ($dl_propia == $dl_propia_anterior && $id_tipo_activ == $id_tipo_activ_anterior) {
        $a_valores[$i]['sel'] = "";
        $a_valores[$i][1] = '';
        $a_valores[$i][2] = '';
    } else {
        $a_valores[$i]['sel']="$id_usuario#$id_item#$id_tipo_activ_txt#$dl_propia";
        $a_valores[$i][1]=$dl_propia_txt;
        $a_valores[$i][2]=$oTipoActividad->getNom();
    }
    $a_valores[$i][3]=$oCuadrosAfecta->lista_tiene_txt($afecta_a);
    
    $a_valores[$i][4]= $fase_ref_txt;
    $a_valores[$i][5]= empty($aOpcionesAction[$perm_off])? '?' : $aOpcionesAction[$perm_off];
    $a_valores[$i][6]= empty($aOpcionesAction[$perm_on])? '?' : $aOpcionesAction[$perm_on];
    
    $id_tipo_activ_anterior = $id_tipo_activ;
    $dl_propia_anterior = $dl_propia;
}
$oHash3 = new web\Hash();
$oHash3->setcamposForm('que!sel');
$oHash3->setcamposNo('refresh!scroll_id');
$a_camposHidden = array(
        'id_usuario' => $id_usuario,
        'quien' => $quien
        );
$oHash3->setArraycamposHidden($a_camposHidden);
$oHash3->setPrefix('perm'); // prefijo par el id.
?>
<script>
fnjs_add_perm_activ=function(){
    $('#frm_usuario').attr('action',"apps/procesos/controller/usuario_perm_activ.php");
	fnjs_enviar_formulario('#frm_usuario');
}

fnjs_mod_perm_activ=function(formulario){
    rta=fnjs_solo_uno(formulario);
    if (rta==1) {
        $(formulario).attr('action','apps/procesos/controller/usuario_perm_activ.php');
        fnjs_enviar_formulario(formulario);
    }
}

fnjs_del_perm_activ=function(formulario,que_val){
    rta=fnjs_solo_uno(formulario);
    if (rta==1) {
        if (confirm("<?php echo _("¿Esta seguro que desea borrar este permiso?");?>") ) {
            $('#perm_activ_que').val('perm_eliminar');
            id_usuario=$('#perm_id_usuario').val();
            $(formulario).attr('action','apps/usuarios/controller/usuario_update.php');
            $(formulario).one("submit", function() {
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'post',
                    data: $(this).serialize()
                })
                .done(function (rta_txt) {
                    if (rta_txt != '' && rta_txt != '\n') {
                        alert ('respuesta: '+rta_txt);
                    } else {
                        fnjs_actualizar3(formulario);
                       }
                });
                return false;
            });
            $(formulario).trigger("submit");
            $(formulario).off();
        }
    }
}
fnjs_actualizar3=function(formulario){
    var campo = '<input type="hidden" name="refresh" value=1>';
    quien = $("#perm_quien").val();
    if (quien == 'grupo') {
        $(formulario).attr('action',"apps/usuarios/controller/grupo_form.php");
    } else {
        $(formulario).attr('action',"apps/usuarios/controller/usuario_form.php");
    }
    $(formulario).append(campo);
    fnjs_enviar_formulario(formulario,'#main');
}
</script>
<br>
<h3><?= ucfirst(_("permisos en actividades")) ?>:</h3>
<b><?= _("propios") ?>:</b>
<p class="comentario"><?= _("manda el nivel más concreto: 'sv n crt' manda sobre 'sv n'") ?>.</p>
<p class="comentario"><?= _("para un mismo nivel, los permisos propios sobreescriben a los de los grupos") ?>.</p>
<br>
<form id="permisos_activ" name="permisos_activ" action=''>
<?= $oHash3->getCamposHtml(); ?>
<input type="hidden" id="perm_activ_que" name="que" value=''>
<?php
$oTabla = new web\Lista();
$oTabla->setId_tabla('form_perm_activ');
$oTabla->setCabeceras($a_cabeceras);
$oTabla->setBotones($a_botones);
$oTabla->setDatos($a_valores);
echo $oTabla->mostrar_tabla_html();
?>
<input type=button onclick="fnjs_add_perm_activ();" value="<?= _("añadir permiso") ?>">
</form>
