<script>
fnjs_add_perm=function(que){
	if (que=='menu'){
		$('#frm_usuario').attr('action',"apps/usuarios/controller/usuario_perm_menu.php");
	}
	if (que=='activ'){
		$('#frm_usuario').attr('action',"apps/usuarios/controller/usuario_perm_activ.php");
	}
	fnjs_enviar_formulario('#frm_usuario');
}
fnjs_del_perm_menu=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= _("está seguro?") ?>")) {
			$('#que').val("perm_menu_eliminar");
			$(formulario).attr('action',"apps/usuarios/controller/usuario_update.php");
			$(formulario).submit(function() {
				$.ajax({
					data: $(this).serialize(),
					url: $(this).attr('action'),
					type: 'post',
					complete: function (rta) {
						rta_txt = rta.responseText;
						if (rta_txt != '' && rta_txt != '\\n') {
							alert ('<?= _("respuesta") ?>: '+rta_txt);
						}
					},
					success: function() { fnjs_actualizar(formulario) }
				});
				return false;
			});
			$(formulario).submit();
			$(formulario).off();
		}
	}
}
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$(formulario).attr('action',"apps/usuarios/controller/grupo_form.php");
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}
</script>
<br>
<h4><?= ucfirst(_("permisos de menús")) ?>:</h4>
<form id="permisos_menu" name="permisos_menu" action="">
<?= $oHashPermisos->getCamposHtml(); ?>
<input type="hidden" id="que" name="que" value="">
<?= $oTabla->mostrar_tabla(); ?>
<br>
<input type=button onclick="fnjs_add_perm('menu');" value="<?= _("añadir permiso") ?>">
</form>
<br>
<?php
/*
if ((core\ConfigGlobal::is_app_installed('procesos')) && !empty($id_usuario)) { // si no hay usuario, no puedo poner permisos.
	//grupo
	$oGesUsuarioGrupo = new usuarios\model\entity\GestorUsuarioGrupo();
	$oListaGrupos = $oGesUsuarioGrupo->getUsuariosGrupos(array('id_usuario'=>$id_usuario));
	$i=0;
	$txt='';
	foreach ($oListaGrupos as $oUsuarioGrupo) {
		$i++;
		$oGrupo = new usuarios\model\entity\Grupo($oUsuarioGrupo->getId_grupo());
		if ($i > 1) $txt.=", ";
		$txt.= $oGrupo->getUsuario();
	}	
	// propios
	$i=0;
	$a_cabeceras=array('tipo de actividad','fase inicial','fase final','permiso','dl propia',array('name'=>'afecta_a','width'=>'350'));
	$a_botones[] = array( 'txt' => _('modificar'), 'click' =>"fnjs_modificar(\"#permisos\")" );
	$a_botones[] = array( 'txt' => _('eliminar'), 'click' =>"fnjs_borrar(\"#permisos\")" ); 
	
	$a_valores=array();
	$oFase = new ActividadFase();
	foreach ($oUsuarioUsuarioPerm as $oUsuarioPerm) {
		$i++;
		
		$id_item=$oUsuarioPerm->getId_item();
		$id_tipo=$oUsuarioPerm->getId_tipo_activ_txt();
		$id_fase_ini=$oUsuarioPerm->getId_fase_ini();
		$id_fase_fin=$oUsuarioPerm->getId_fase_fin();
		$id_accion=$oUsuarioPerm->getAccion();
		$dl_propia=$oUsuarioPerm->getDl_propia();

		if ($dl_propia=='t') { $dl_propia_txt = core\ConfigGlobal::$dele; } else { $dl_propia_txt = _('otras'); }

		$oTipoActividad = new web\TiposActividades($oUsuarioPerm->getId_tipo_activ_txt());

		$a_valores[$i]['sel']="$id_usuario#$id_item";
		$a_valores[$i][1]=$oTipoActividad->getNom();
		$oFase->setId_fase($id_fase_ini);
		$oFase->DBCarregar();
		$a_valores[$i][2]= $oFase->getDesc_fase();
		$oFase->setId_fase($id_fase_fin);
		$oFase->DBCarregar();
		$a_valores[$i][3]= $oFase->getDesc_fase();
		$a_valores[$i][4]=$oPermAccion->lista_txt($oUsuarioPerm->getAccion());
		$a_valores[$i][5]=$dl_propia_txt;

		$a_valores[$i][6]=$oCuadros->lista_tiene_txt($oUsuarioPerm->getAfecta_a());
	}
	$oHash3 = new web\Hash();
	$oHash3->setcamposForm('que!sel');
	$a_camposHidden = array(
			'id_usuario' => $id_usuario,
			'quien' => $Qquien
			);
	$oHash3->setArraycamposHidden($a_camposHidden);
	?>
	<br>
	<h3><?= ucfirst(_("permisos en actividades")) ?>:</h3>
	<?php
	if ($Qquien == 'usuario') {  // de momento no dejo hacer grupos de grupos.
		?>
		<b><?= _('grupos') ?>: </b><?= $txt ?>
		<input type=button onclick="fnjs_add_grup();" value="<?= _("añadir un grupo de permisos") ?>">
		<input type=button onclick="fnjs_del_grup();" value="<?= _("quitar de un grupo de permisos") ?>">
		<div id=lst_grupos></div>
		<br>
		<?php
	}
	?>
	<b><?= _('propios') ?>:</b>
	<form id=permisos name=permisos action=''>
	<?= $oHash3->getCamposHtml(); ?>
	<input type=hidden id=que  name=que value=''>
	<?php
	$oTabla = new web\Lista();
	$oTabla->setId_tabla('usuario_form_permisos');
	$oTabla->setCabeceras($a_cabeceras);
	$oTabla->setBotones($a_botones);
	$oTabla->setDatos($a_valores);
	echo $oTabla->mostrar_tabla();
	?>
	<br>
	<input type=button onclick="fnjs_add_perm('activ');" value="<?= _("añadir permiso") ?>">
	</form>
	<?php
}
*/