<?php

use core\ConfigGlobal;

// propios
$i=0;
$a_cabeceras=array('tipo de actividad','fase inicial','fase final','permiso','dl propia',array('name'=>'afecta_a','width'=>'350'));
$a_botones = [];
$a_botones[] = array( 'txt' => _("modificar"), 'click' =>"fnjs_mod_perm_activ(\"#permisos_activ\")" );
$a_botones[] = array( 'txt' => _("eliminar"), 'click' =>"fnjs_del_perm_activ(\"#permisos_activ\")" ); 

$a_valores=array();
$oFase = new procesos\model\entity\ActividadFase();
foreach ($cUsuarioPerm as $oUsuarioPerm) {
    $i++;
    
    $id_item=$oUsuarioPerm->getId_item();
    $id_tipo=$oUsuarioPerm->getId_tipo_activ_txt();
    $id_fase_ini=$oUsuarioPerm->getId_fase_ini();
    $id_fase_fin=$oUsuarioPerm->getId_fase_fin();
    $id_accion=$oUsuarioPerm->getAccion();
    $dl_propia=$oUsuarioPerm->getDl_propia();

    if ($dl_propia=='t') {
        if (substr($id_tipo, 0, 1) == 1) { //sv
            $dl_propia_txt = core\ConfigGlobal::mi_dele();
        } else { //sf
            if (substr($id_tipo, 0, 1) == '.') { //sf y sv
                $dl_propia_txt = core\ConfigGlobal::mi_dele().' - '.core\ConfigGlobal::mi_dele().'f';
            } else {
                $dl_propia_txt = core\ConfigGlobal::mi_dele().'f';
            }
        }
    } else {
        $dl_propia_txt = _("otras");
    }

    $oTipoActividad = new web\TiposActividades($oUsuarioPerm->getId_tipo_activ_txt());

    $a_valores[$i]['sel']="$id_usuario#$id_item";
    $a_valores[$i][1]=$oTipoActividad->getNom();
    $oFase->setId_fase($id_fase_ini);
    $oFase->DBCarregar();
    $a_valores[$i][2]= $oFase->getDesc_fase();
    $oFase->setId_fase($id_fase_fin);
    $oFase->DBCarregar();
    $a_valores[$i][3]= $oFase->getDesc_fase();
    $a_valores[$i][4]=$oPermAccion->lista_txt($oUsuarioPerm->getAccion());
    $a_valores[$i][5]=$dl_propia_txt;

    $a_valores[$i][6]=$oCuadrosAfecta->lista_tiene_txt($oUsuarioPerm->getAfecta_a());
}
$oHash3 = new web\Hash();
$oHash3->setcamposForm('que!sel');
$oHash3->setcamposNo('refresh!scroll_id');
$a_camposHidden = array(
        'id_usuario' => $id_usuario,
        'quien' => $quien
        );
$oHash3->setArraycamposHidden($a_camposHidden);
?>
<script>
fnjs_add_perm_activ=function(){
    $('#frm_usuario').attr('action',"apps/procesos/controller/usuario_perm_activ.php");
	fnjs_enviar_formulario('#frm_usuario');
}

fnjs_mod_perm_activ=function(formulario){
    rta=fnjs_solo_uno(formulario);
    if (rta==1) {
        $(formulario).attr('action','apps/procesos/controller/usuario_perm_activ.php');
        fnjs_enviar_formulario(formulario);
    }
}

fnjs_del_perm_activ=function(formulario,que_val){
    rta=fnjs_solo_uno(formulario);
    if (rta==1) {
        if (confirm("<?php echo _("¿Esta seguro que desea borrar este permiso?");?>") ) {
            $('#perm_activ_que').val('perm_eliminar');
            id_usuario=$('#id_usuario').val();
            $(formulario).attr('action','apps/usuarios/controller/usuario_update.php');
            $(formulario).submit(function() {
                $.ajax({
                    url: $(this).attr('action'),
                    type: 'post',
                    data: $(this).serialize()
                })
                .done(function (rta_txt) {
                    if (rta_txt != '' && rta_txt != '\n') {
                        alert ('respuesta: '+rta_txt);
                    } else {
                        fnjs_actualizar3(formulario);
                       }
                });
                return false;
            });
            $(formulario).submit();
            $(formulario).off();
        }
    }
}
fnjs_actualizar3=function(formulario){
    var campo = '<input type="hidden" name="refresh" value=1>';
    quien = $("#quien").val();
    if (quien == 'grupo') {
        $(formulario).attr('action',"apps/usuarios/controller/grupo_form.php");
    } else {
        $(formulario).attr('action',"apps/usuarios/controller/usuario_form.php");
    }
    $(formulario).append(campo);
    fnjs_enviar_formulario(formulario,'#main');
}
</script>
<br>
<h3><?= ucfirst(_("permisos en actividades")) ?>:</h3>
<b><?= _("propios") ?>:</b>
<p class="comentario"><?= _("los permisos propios sobresecriben a los de los grupos") ?></p>
<br>
<form id="permisos_activ" name="permisos_activ" action=''>
<?= $oHash3->getCamposHtml(); ?>
<input type="hidden" id="perm_activ_que" name="que" value=''>
<?php
$oTabla = new web\Lista();
$oTabla->setId_tabla('form_perm_activ');
$oTabla->setCabeceras($a_cabeceras);
$oTabla->setBotones($a_botones);
$oTabla->setDatos($a_valores);
echo $oTabla->mostrar_tabla();
?>
<input type=button onclick="fnjs_add_perm_activ();" value="<?= _("añadir permiso") ?>">
</form>
