<script>
fnjs_del_grupmenu=function(formulario){
	$('#que').val('del_grupmenu');
	$(formulario).attr('action',"apps/usuarios/controller/role_update.php");
	$(formulario).submit(function() {
		$.ajax({
			data: $(this).serialize(),
			type: 'post',
			url: $(this).attr('action'),
			complete: function (rta) {
				rta_txt=rta.responseText;
				if (rta_txt != '' && rta_txt != '\\n') {
					alert ('<?= _("respuesta") ?>: '+rta_txt);
				}
			},
			success: function() { fnjs_actualizar(formulario) }
		});
		return false;
	});
	$(formulario).submit();
	$(formulario).off();
}

fnjs_add_grupmenu=function(que){
	go='<?= web\Hash::link('apps/usuarios/controller/role_grupmenu.php?'.http_build_query(array('id_role'=>$Qid_role))) ?>';
	fnjs_update_div('#main',go); 
}

fnjs_guardar=function(formulario){
	var rr=fnjs_comprobar_campos(formulario,'<?= addslashes($obj) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok') {
		$('#que_user').val('<?= $que_user ?>');
		$(formulario).attr('action',"apps/usuarios/controller/role_update.php");
		$(formulario).submit(function() {
			$.ajax({
				data: $(this).serialize(),
				type: 'post',
				url: $(this).attr('action'),
				complete: function (rta) {
					rta_txt = rta.responseText;
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					}
				},
				success: function() { 
					<?php if (empty($nuevo)) {
						echo "fnjs_actualizar(formulario);";
					} else { // si es nuevo voy a la lista de rols
						echo $oPosicion->js_atras(1);
					} ?>
				}
			});
			return false;
		});
		$(formulario).submit();
		$(formulario).off();
	}
}
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$(formulario).attr('action',"apps/usuarios/controller/role_form.php");
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h3><?= $role ?> <?= $txt_sfsv ?></h3>
<?php 
if ($permiso == 1) {
	?>
	<form id="frm_role" name="frm_role" action="" method="post" >
	<?= $oHash->getCamposHtml(); ?>
	<input type="hidden" id="que_user" name="que" value"">
	<br>
	<?= ucfirst(_("nombre")) ?>:<input type="text" name="role" value="<?= $role ?>">
	<?= ucfirst(_("sf")) ?>:<input type="checkbox" name="sf" value="1"<?= $chk_sf ?> >
	<?= ucfirst(_("sv")) ?>:<input type="checkbox" name="sv" value="1"<?= $chk_sv ?> >
	<?= ucfirst(_("pau")) ?>:<input type="text" name="pau" value="<?= $pau ?>">
	<br>
	<input type="button" onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
	<br>
	</form>
	<?php
}

if (!empty($Qid_role)) { // si no hay role, no puedo poner permisos.
	?>
	<h4><?= ucfirst(_("grupos de menús")) ?>:</h4>
	<form id="form_grup_menu" name="form_grup_menu" action="">
	<?= $oHash1->getCamposHtml(); ?>
	<input type="hidden" id="que"  name="que" value="">
	<?php
	echo $oTabla->mostrar_tabla();
	?>
	<br>
	<input type="button" onclick="fnjs_add_grupmenu();" value="<?= _("añadir grup menu") ?>">
	</form>
	<?php
}