<script>
    fnjs_add_grupmenu = function (formulario) {
        $(formulario).attr('action', "apps/usuarios/controller/role_update.php");
        $(formulario).one("submit", function () {
            $.ajax({
                url: $(this).attr('action'),
                type: 'post',
                data: $(this).serialize()
            })
                .done(function (rta_txt) {
                    if (rta_txt != '' && rta_txt != '\\n') {
                        alert('<?= _("respuesta") ?>: ' + rta_txt);
                    } else {
                        <?= $oPosicion->js_atras(1); ?>
                    }
                });
            return false;
        });
        $(formulario).trigger("submit");
        $(formulario).off();
    }
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h1><?= sprintf(_("añadir nuevo grupMenu a %s"), $role) ?></h1>
<form id="from_grupmenu" name="from_grupmenu" action="" method="post">
    <?= $oHash->getCamposHtml(); ?>
    <h4><?= ucfirst(_("grupos de menús")) ?>:</h4>
    <?= $oTabla->mostrar_tabla(); ?>
</form>
