<script>
fnjs_modificar=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		switch (formulario) {
			case '#permisos_menu':
				$(formulario).attr('action','apps/usuarios/controller/usuario_perm_menu.php');
				break;
			case '#permisos':
				$(formulario).attr('action','apps/usuarios/controller/usuario_perm_activ.php');
				break;
			case '#avisos':
				$(formulario).attr('action','apps/usuarios/controller/usuario_avisos_pref.php');
				break;
		}
		fnjs_enviar_formulario(formulario);
	}
}

fnjs_borrar=function(formulario,que_val){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		switch (formulario) {
			case '#permisos_menu':
			case '#permisos':
				if (confirm("<?= _("¿Está seguro que desea borrar este permiso?");?>") ) {
					id_usuario=$('#id_usuario').val();
					if (formulario == '#permisos_menu') {
						$('#que').val('perm_menu_eliminar');
						go='<?= web\Hash::link('apps/usuarios/controller/usuario_form.php?'.http_build_query(array('quien'=>'grupo','id_usuario'=>$id_usuario))) ?>';
					}	
					if (formulario == '#permisos') {
						$('#que').val('perm_eliminar');
						go='<?= web\Hash::link('apps/usuarios/controller/usuario_form.php?'.http_build_query(array('quien'=>'usuario','id_usuario'=>$id_usuario))) ?>';
					}	
					$(formulario).attr('action',"apps/usuarios/controller/usuario_update.php");
					$(formulario).submit(function() {
						$.ajax({
							data: $(this).serialize(),
							type: 'post',
							url: $(this).attr('action'),
							complete: function (rta) { 
								rta_txt=rta.responseText;
								if (rta_txt.indexOf('id="ir_a"') != -1) {
									fnjs_mostra_resposta(rta,'#main'); 
								} else {
									if (go) fnjs_update_div('#main',go); 
								}
							}
						});
						return false;
					});
					$(formulario).submit();
					$(formulario).off();
				}
				break;
			case '#avisos':
				if (confirm("<?= _("¿Está seguro que desea borrar este aviso?");?>") ) {
					$('#av_que').val('aviso_eliminar');
					go='<?= web\Hash::link('apps/usuarios/controller/usuario_form.php?'.http_build_query(array('quien'=>'usuario','id_usuario'=>$id_usuario))) ?>';
					$(formulario).attr('action',"apps/usuarios/controller/usuario_aviso_update.php");
					$(formulario).submit(function() {
						$.ajax({
							data: $(this).serialize(),
							type: 'post',
							url: $(this).attr('action'),
							complete: function (rta) { 
								rta_txt=rta.responseText;
								if (rta_txt.indexOf('id="ir_a"') != -1) {
									fnjs_mostra_resposta(rta,'#main'); 
								} else {
									if (go) fnjs_update_div('#main',go); 
								}
							}
						});
						return false;
					});
					$(formulario).submit();
					$(formulario).off();
				}
				break;
		}
	}
}
fnjs_add_alert=function(){
	$('#avisos').attr('action',"apps/usuarios/controller/usuario_avisos_pref.php");
	fnjs_enviar_formulario('#avisos');
}
</script>
<b><?= _("avisos") ?>:</b>
<form id="avisos" name="avisos" action=''>
<?= $oHash3->getCamposHtml(); ?>
<input type="hidden" id="av_que"  name="que" value="">
<?= $oTablaAvisos->mostrar_tabla(); ?>
<br>
<input type=button onclick="fnjs_add_alert();" value="<?= _("añadir aviso") ?>">
</form>