<style type="text/css">
input {
	border: 1px solid #999;
	margin: 0 5px;
	}
.password_strength {
	padding: 0 5px;
	display: inline-block;
	}
.password_strength_1 {
	background-color: #fcb6b1;
	}
.password_strength_2 {
	background-color: #fccab1;
	}
.password_strength_3 {
	background-color: #fcfbb1;
	}
.password_strength_4 {
	background-color: #dafcb1;
	}
.password_strength_5 {
	background-color: #bcfcb1;
	}
</style>
<script type='text/javascript' src='<?= core\ConfigGlobal::$web_scripts.'/jquery.password_strength.js'; ?>'></script>
<h3><?= $usuario ?></h3>
<?= _("deberías cambiar el password") ?>
<form id=frm_usuario  name=frm_usuario action='' method="post" >
<?= $oHash->getCamposHtml(); ?>
<input type=hidden id=que_user  name=que value=''>
<br>
<?= ucfirst(_("password")) ?>:<input type="password" id="password" name="password"><br>
<?= ucfirst(_("confirma password")) ?>:<input type="password" id="password1" name="password1"><br>
<?= ucfirst(_("email")) ?>:<input type=text name=email value="<?= $email ?>"><br>
<input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
<br>
</form>
<script>
var strong = 0;
algo=function(level) {
	strong = level;
}
var options = {	'texts' : {
		1 : "<?= _("demasiado débil")?>",
		2 : "<?= _("password débil")?>",
		3 : "<?= _("normal")?>",
		4 : "<?= _("strong password")?>",
		5 : "<?= _("very strong password")?>"
	},
	'onCheck': algo
}

$('input[type=password]').password_strength(options);

fnjs_guardar=function(formulario){
	// si es 0, no se cambia el password.
	if (strong != 0 && strong < 4) {
	  alert("<?= _("debe poner un password 'fuerte' o 'muy fuerte'") ?>");
	  return false;
	}
	var pwd=$("#password").val();
	var pwd1=$("#password1").val();
	
	if (!pwd) {
		alert ("<?= _("error: password no válido") ?>");
		return false;
	}
	if (!pwd1) {
		alert ("<?= _("error: debes confirmar el password") ?>");
		return false;
	}
	if (pwd!=pwd1) {
		alert ("<?= _("error: passwords no coincidentes") ?>");
		return false;
	}
	$('#que_user').val('<?= $que_user ?>');
	id_usuario=$('#id_usuario').val();
	go='apps/usuarios/controller/usuario_form.php?quien=usuario&id_usuario='+id_usuario;
	$(formulario).attr('action',"apps/usuarios/controller/usuario_update.php");
	$(formulario).submit(function() {
		$.ajax({
			data: $(this).serialize(),
			type: 'post',
			url: $(this).attr('action'),
			complete: function (rta) { 
				rta_txt=rta.responseText;
				if (rta_txt != '' && rta_txt != '\n') {
					alert (rta_txt);
				} else {
					$('#main').html('');
				}
			}
		});
		return false;
	});
	$(formulario).submit();
	$(formulario).off();
}
</script>
