<script>
fnjs_add_grup=function(){
	var url='<?= $url_usuario_ajax ?>';
	var parametros='que=grupo_lst&id_usuario=<?= $id_usuario ?><?= $h1 ?>';
		 
	$.ajax({
		url: url,
		type: 'post',
		data: parametros
	})
	.done(function (rta_txt) {
		$('#lst_grupos').html(rta_txt);
	});
}
fnjs_del_grup=function(){
	var url='<?= $url_usuario_ajax ?>';
	var parametros='que=grupo_del_lst&id_usuario=<?= $id_usuario ?><?= $h1 ?>';
		 
	$.ajax({
		url: url,
		type: 'post',
		data: parametros
	})
	.done(function (rta_txt) {
		$('#lst_grupos').html(rta_txt);
	});
}
fnjs_add_perm=function(que){
	if (que=='menu'){
		$('#frm_usuario').attr('action',"apps/usuarios/controller/usuario_perm_menu.php");
	}
	if (que=='activ'){
		$('#frm_usuario').attr('action',"apps/procesos/controller/usuario_perm_activ.php");
	}
	fnjs_enviar_formulario('#frm_usuario');
}
fnjs_del_perm=function(formulario){
	rta=fnjs_solo_uno(formulario);
	if (rta==1) {
		if (confirm("<?= $txt_eliminar ?>") ) {
			$('#mod').val("eliminar");
			$(formulario).attr('action',"apps/usuarios/controller/usuario_ajax.php");
			$(formulario).one("submit", function() {
				$.ajax({
					url: $(this).attr('action'),
					type: 'post',
					data: $(this).serialize()
				})
				.done(function (rta_txt) {
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					} else {
						fnjs_actualizar(formulario);
				   	}
				});
				return false;
			});
			$(formulario).trigger("submit");
			$(formulario).off();
		}
	}
}
fnjs_actualizar=function(formulario){
	var campo = '<input type="hidden" name="refresh" value=1>';
	$(formulario).attr('action',"apps/dossiers/controller/dossiers_ver.php");
	$(formulario).append(campo);
	fnjs_enviar_formulario(formulario,'#main');
}

fnjs_chk_passwd=function(formulario){
	var password=encodeURIComponent($('#password').val());
	var usuario=encodeURIComponent($('#usuario').val());
	var url = 'apps/usuarios/controller/usuario_update.php';
	debugger;
	var parametros='que=check_pwd&id_usuario=<?= $id_usuario ?>&usuario='+usuario+'&password='+password+'<?= $h2 ?>';
	
	var request=$.ajax({
        data: parametros,
        url: url,
        type: 'post',
        dataType: 'json'
    });
    request.done( function (json) {
        if (json.success != true) {
            alert ("password error:\n"+json.mensaje);
            return false;
        } else {
			fnjs_guardar_datos(formulario);
        }
    });
}
fnjs_guardar=function(formulario){
	var password=$('#password').val();
	// si es 0, no se cambia el password.
	if (password) {
		fnjs_chk_passwd(formulario);
    } else {
        fnjs_guardar_datos(formulario);
    }
}

fnjs_guardar_datos=function(formulario){
	var rr=fnjs_comprobar_campos(formulario,'<?= addslashes($obj) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok') {
		$('#que_user').val('<?= $que_user ?>');
		$(formulario).attr('action',"apps/usuarios/controller/usuario_update.php");
		$(formulario).one("submit", function() {
			$.ajax({
				url: $(this).attr('action'),
				type: 'post',
				data: $(this).serialize()
			})
			.done(function (rta_txt) {
				if (rta_txt != '' && rta_txt != '\\n') {
					alert ('<?= _("respuesta") ?>: '+rta_txt);
				} else {
					<?= $oPosicion->js_atras(1); ?>
				}
			});
			return false;
		});
		$(formulario).trigger("submit");
		$(formulario).off();
	}
}
<?php
if ($pau == 'cdc' && $quien == 'usuario') { //casa
	?>
	fnjs_mas_casas=function(evt){
		if(evt=="x") {
			var valor=1;
		} else {
			var id_campo=evt.currentTarget.id;
			var valor=$(id_campo).val();
			evt.preventDefault();
			evt.stopPropagation();
		}
		if (evt.keyCode==9 || evt.type=="change" || evt=="x") {
			if (valor!=0) {
				<?php
					echo $oSelects->ListaSelectsJs();
				?>
			} else {
				ir_a('f_entrada');
			}
		}
	}
	<?php
	echo $oSelects->ComprobarSelectJs();
}
?>
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h3><?= $usuario ?></h3>
<form id="frm_usuario"  name="frm_usuario" action="" method="post" >
<?= $oHash->getCamposHtml(); ?>
<input type=hidden id=pass  name=pass value='<?= $pass ?>'>
<input type=hidden id=que_user  name=que value=''>
<br>
<?= ucfirst(_("login")) ?>:<input type=text id=usuario name=usuario value="<?= $usuario ?>" size=60>
<?php if ($quien == 'usuario') { ?>
<br>
<?= ucfirst(_("nombre a mostrar")) ?>:<input type=text name=nom_usuario value="<?= $nom_usuario ?>">
<?php } ?>
<?= ucfirst(_("role")) ?>:
<?= $oDesplRoles->desplegable(); ?>
<br>
<?php 
if ($pau == 'nom') {
?>
    <!--  --------------- Sacd --------------- -->
    <tr>
        <td class=etiqueta><?= _("persona"); ?>:</td>	
    <td colspan=8 id="col_sacd">
    <?php
    echo $oSelects->desplegable();
    echo "</td></tr>";
}
if ($pau == 'sacd') {
?>
    <!--  --------------- Sacd --------------- -->
    <tr>
        <td class=etiqueta><?= _("sacd"); ?>:</td>	
    <td colspan=8 id="col_sacd">
    <?php
    echo $oSelects->desplegable();
    echo "</td></tr>";
}
if ($pau == 'ctr') {
?>
    <!--  --------------- CENTROS --------------- -->
    <tr>
        <td class=etiqueta><?= _("centro"); ?>:</td>	
    <td colspan=8 id="col_centros">
    <?php
    echo $oSelects->desplegable();
    echo "</td></tr>";
}
if ($pau == 'cdc') {
?>
    <!--  --------------- CASAS --------------- -->
    <tr>
        <td class=etiqueta><?= _("casas"); ?>:</td>	
    <td colspan=8 id="col_casas">
    <?php
    echo $oSelects->ListaSelects();
    echo "</td></tr>";
}
?>
<br>
<?= ucfirst(_("password")) ?>:<input type="password" id="password" name="password" size=30><br>
<?= ucfirst(_("email")) ?>:<input type=text name=email size=30 value="<?= $email ?>"><br>
<input type=button onclick="fnjs_guardar(this.form);" value="<?= $txt_guardar ?>">
<br>
</form>
