<?php
use personas\model as personas;
/**
* Esta es la página de presentación de la ficha de n, agd y sss+ de paso (copia de agd). 
*
* Esta presentación se incluye dentro del programa de visualización de
* las fichas.
* Existen 3 tipos de textos:
*		- titulos (<th>)
*		- etiquetas (<span class=etiqueta>) son links a helps
*		- datos (class=datos) varios tipos: links, inputs
*
* @author Daniel Serrabou
* @package fichas
* @subpackage agd
*/

?>
<table id="datospersonales">
<tr><td class=titulo colspan="5">
<?php print(strtoupper(_("datos personales"))); ?>
</td></tr>
<tr>
	<?php
	echo "<td>"._("delegación").":</td><td class=contenido>$dl</td>";
	echo "<td>"._("centro-sede").":</td><td class=contenido>$nom_ctr</td>";
	?>
</tr>
<tr>
<?php
echo web\dibujar_campo($obj,"trato",7,1,0);
echo web\dibujar_campo($obj,"nom",20,1,2);
echo "</tr><tr><td></td>";
echo web\dibujar_campo($obj,"apel_fam",20,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"nx1",7,1,0);
echo web\dibujar_campo($obj,"apellido1",25,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"nx2",7,1,0);
echo web\dibujar_campo($obj,"apellido2",25,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"f_nacimiento",11,1,1);

echo "</tr><tr>";
echo web\dibujar_campo($obj,"situacion",2,1,1);
echo web\dibujar_campo($obj,"f_situacion",11,1,1);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"lengua",3,1,1);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"profesion",30,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"sacd",9,1,1);
echo "</tr><tr>";
?>
</tr>
</table>
