<?php
use core\ConfigGlobal;

?>
<script>

fnjs_guardar=function(formulario){
	var rr=fnjs_comprobar_campos('#frm2','<?= addslashes($obj_txt) ?>');
	//alert ("EEE "+rr);
	if (rr=='ok') {
		$('#que').val('guardar');
		$(formulario).attr('action',"apps/personas/controller/personas_update.php");
		$(formulario).submit(function() {
			$.ajax({
				data: $(this).serialize(),
				type: 'post',
				url: $(this).attr('action'),
				complete: function (rta) {
					rta_txt=rta.responseText;
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					} else {
						<?= $oPosicion->js_atras(1); ?>
					}
				}
			});
			return false;
		});
		$(formulario).submit();
		$(formulario).off();
	}
}
fnjs_eliminar=function(formulario){
	if (confirm("<?= _("¿Está seguro que desea borrar esta persona? Sólo puedes borrar a los de tu dl.");?>") ) {
	   	$('#que').val('eliminar');
		$(formulario).attr('action',"apps/personas/controller/personas_update.php");
		$(formulario).submit(function() {
			$.ajax({
				data: $(this).serialize(),
				url: $(this).attr('action'),
				type: 'post',
				complete: function (rta) {
					rta_txt = rta.responseText;
					if (rta_txt != '' && rta_txt != '\\n') {
						alert ('<?= _("respuesta") ?>: '+rta_txt);
					} else {
						<?= $oPosicion->js_atras(1); ?>
					}
				}
			});
			return false;
		});
		$(formulario).submit();
		$(formulario).off();
	}
}
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<?php 
if (!$nuevo) {
	?>
	<!-- ============================== cabecera ============================= -->
	<table><tr>
	<td class=esquerra nowrap>
	</td>
	<td>
	<span class=link onclick="fnjs_update_div('#main','<?= $godossiers ?>')" ><img src=<?= core\ConfigGlobal::$web_icons ?>/dossiers.gif border=0 width=40 height=40 alt='<?= _("ver dossiers") ?>'>(<?= _("dossiers") ?>)</span>

	<td class=titulo><span class=link onclick="fnjs_update_div('#main','<?= $gohome ?>')" ><?= $titulo ?></span></td>
	</table>
	<?php 
	}
?>


<!-- ============================== Ficha ============================= -->
<form id='frm2' >
<?= $oHash->getCamposHtml(); ?>
<input type="Hidden" id="que"  name="que" value="">
<table id="datospersonales">
<tr><td class=titulo colspan="5">
<?php print(strtoupper(_("datos personales"))); ?>
</td></tr>
<tr>
	<td colspan=2><span class=etiqueta ondblclick="fnjs_help('<?php //echo $id_tabla_help_ref; ?>')" >n, agd o sss+:</span>
	<select class=datos name="id_tabla">
			<option value="pn" <?php if ($id_tabla=="pn") { echo "selected"; } ?> ><?= _("numerario") ?></option>
			<option value="pa" <?php if ($id_tabla=="pa") { echo "selected"; } ?> ><?= _("agregado") ?></option>
			<?php 
			if (core\ConfigGlobal::mi_sfsv() == 2) {
				$selected = ($id_tabla=="px")? 'selected': '';
				echo "<option value=\"px\" $selected >". _("numeraria auxiliar") ."</option>";
			} else {
				$selected = ($id_tabla=="psssc")? 'selected': '';
				echo "<option value=\"psssc\" $selected >". _("sss+") ."</option>";
			}
			?>
	</select></td>
	<td><span class=etiqueta ondblclick="fnjs_help('<?php //echo $dl_help_ref; ?>')" >Delegación</span></td>
	<td><input class=datos size="6" name="dl" value="<?= $dl ?>" title="<?php //echo $dl_help; ?>"></td>
	</tr>
<tr>
<?php
echo web\dibujar_campo($obj,"trato",7,1,0);
echo web\dibujar_campo($obj,"nom",20,1,2);
echo "</tr><tr><td></td>";
echo web\dibujar_campo($obj,"apel_fam",20,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"nx1",7,1,0);
echo web\dibujar_campo($obj,"apellido1",25,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"nx2",7,1,0);
echo web\dibujar_campo($obj,"apellido2",25,1,2);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"lugar_nacimiento",15,1,1);
echo web\dibujar_campo($obj,"f_nacimiento",11,1,0);
echo web\dibujar_campo($obj,"edad",4,1,1);
echo "</tr><tr>";
?>
	<td><span class=etiqueta ><?= ucfirst('situacion'); ?></span>
	</td>
	<td colspan=2><?= $oDesplSituacion->desplegable() ?></td>
<?php
echo web\dibujar_campo($obj,"f_situacion",11,1,1);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"lengua",3,1,1);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"profesion",30,1,2);
echo "</tr><tr>";
if (core\ConfigGlobal::mi_sfsv() == 1) {
	echo web\dibujar_campo($obj,"sacd",9,1,1);
}
echo web\dibujar_campo($obj,"profesor_stgr",9,1,1);
?>
<td><span class=etiqueta ondblclick="fnjs_help('<?php //echo $stgr_help_ref; ?>')" >Stgr&nbsp;</span>
	<?= $oDesplStgr->desplegable(); ?>
</td>
<?php
echo "</tr><tr>";
echo web\dibujar_campo($obj,"eap",20,2,0);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"inc",5,1,0);
echo web\dibujar_campo($obj,"f_inc",11,1,1);
echo "</tr><tr>";
echo web\dibujar_campo($obj,"observ",60,1,4);
echo "</tr><tr>";
// -----------------------------------  Botones  ----------------------
if (!empty($botones)) {
	echo "<table><tr class=botones>";
	$b=strtok($botones,",");
	while ($b) {
		if ($b==1){
			$txt_g=ucwords(_("guardar cambios"));
			echo "<th class='link_inv' onclick='fnjs_guardar(\"#frm2\")'>$txt_g</th>"; }
		if ($b==2){
			$txt_e=ucwords(_("eliminar"));
			echo "<th class='link_inv' onclick='fnjs_eliminar(\"#frm2\")'>$txt_e</th>"; }
		if ($b==3){
			$txt_e=ucwords(_("formato texto"));
			$pag="programas/ficha_texto.php?id_nom=$id_nom&obj_pau=$Qobj_pau";
			echo "<th class='link_inv' onclick='fnjs_update_div('#main','$pag')'>$txt_e</th>"; }
		$b=strtok(",");
	} 
	echo "</tr></table><br>";
}
// fin ----------------------------  Botones  ----------------------
?>
</tr></table>
</form>
