<?php

use web\Hash;

?>
<form id="frm_personas_que" action="<?= $action ?>" method="post" onkeydown="fnjs_enviar(event,this);">
    <?= $oHash->getCamposHtml(); ?>
    <table>
        <thead>
        <th class=titulo_inv colspan=4><?= ucfirst(_("búsqueda de personas")); ?> (<?= $nom_tabla ?>)</th>
        </thead>
        <tfoot>
        <tr>
            <td class=etiqueta colspan=2><?= _("realizar una búsqueda exacta:"); ?>
                <input type="Radio" name="exacto" value=0 <?= $chk_exacto_0 ?>><?= _("no"); ?>
                <input type="Radio" name="exacto" value=1 <?= $chk_exacto_1 ?>><?= _("sí"); ?></td>
            <td class=etiqueta colspan="2" align="RIGHT"><input type="checkbox"
                                                                name="cmb" <?= $chk_cmb ?>><?= _("buscar en fichero cmb"); ?>
            </td>
        </tr>
        <tr>
            <th colspan=4><input type="button" id="btn_ok" name="btn_ok"
                                 onclick="fnjs_enviar_formulario('#frm_personas_que')"
                                 value="<?= ucfirst(_("buscar")); ?>" class="btn_ok">
                <input TYPE="reset"
                       onclick="fnjs_update_div('#main','<?= Hash::link('apps/personas/controller/personas_que.php?' . http_build_query(array('tabla' => $tabla, 'tipo' => $tipo))) ?>')"
                       value="<?= ucfirst(_("borrar")); ?>"></th>
        </tr>
        </tfoot>
        <tbody>
        <tr>
            <td class=etiqueta><?= ucfirst(_("nombre")); ?></td>
            <td><input class=contenido id="nombre" name="nombre" size="30" value="<?= $nombre ?>"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("primer apellido")); ?></td>
            <td><input class=contenido id="apellido1" name="apellido1" size="40" value="<?= $apellido1 ?>"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("segundo apellido")); ?></td>
            <td><input class=contenido id="apellido2" name="apellido2" size="40" value="<?= $apellido2 ?>"></td>
        </tr>
        <tr>
            <td class=etiqueta><?= ucfirst(_("centro")); ?></td>
            <td><input class=contenido id="centro" name="centro" value="<?= $centro ?>"></td>
        </tr>
        </tbody>
    </table>
</form>