<script>
    fnjs_guardar_stgr = function (formulario) {
        var datos = $(formulario).serialize();
        let request = $.ajax({
            data: datos,
            url: 'apps/personas/controller/stgr_update.php',
            method: 'POST',
            dataType: 'json'
        });
        request.done(function (json) {
        if (json.success !== true) {
            alert("<?= _("respuesta") ?>: " + json.mensaje);
        } else {
            <?= $oPosicion->js_atras(1); ?>
        }
        });
    }
</script>
<?= $oPosicion->mostrar_left_slide(1); ?>
<h2 class="titulo" > <?= ucfirst(_("cambiar el stgr")) ?> </h2>
<form id="frm_sin_nombre" name="frm_sin_nombre" action="" method="POST">
    <?= $oHash->getCamposHtml(); ?>
    <table>
        <tr>
            <th class=etiqueta_inv><?= $nom; ?></th>
            <td class=datos>
                <?= $oDespl->desplegable(); ?>
            </td>
        </tr>
    </table>
    <input type="button" id="guardar" name="guardar" onclick="fnjs_guardar_stgr('#frm_sin_nombre');"
       value="<?php print(ucfirst(_("guardar"))) ?>">
</form>
