<?php

use core\ConfigGlobal;

?>
<table>
    <tr>
        <td class=esquerra nowrap>
        </td>
        <td>
            <span class=link onclick="fnjs_update_div('#main','<?= $godossiers ?>')"><img
                        src=<?= ConfigGlobal::getWeb_icons() ?>/dossiers.gif border=0 width=40 height=40
                        alt='<?= $alt ?>'>(<?= $dos ?>)</span>

        <td class=titulo><span class=link onclick="fnjs_update_div('#main','<?= $gohome ?>')"><?= $titulo ?></span></td>
</table>