<script>
     fnjs_upload_certificado = function (formulario) {
            $(formulario).attr('action', "apps/certificados/controller/certificado_pdf_upload.php");
            $(formulario).target = "print";
            fnjs_enviar_formulario(formulario);
    }
    fnjs_descargar_pdf = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            /* selecciono los elementos con class="sel" de las tablas del id=formulario */
            $(formulario + ' input.sel').each(function (i) {
                if ($(this).prop('checked') == true) {
                    key = $(this).prop('value');
                    url = "apps/certificados/controller/certificado_pdf_download.php";
                    url_download = url + '?key=' + key + '<?= $h_download ?>';
                    window.open(url_download);
                }
            });
        }
    }
</script>
<h3 class=subtitulo><?= ucfirst(_("relación de certificados")) ?></h3>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHashSelect->getCamposHtml() ?>
    <?= $oTabla->mostrar_tabla() ?>
</form>