<script>
    fnjs_mod_habitacion = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            let request = $.ajax({
                data: $(formulario).serialize(),
                url: 'frontend/ubiscamas/controller/habitacion_form.php',
                type: 'POST',
                dataType: 'json'
            });
            request.done(function (json) {
                if (json.success !== true) {
                    alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
                } else {
                    //fnjs_actualizar(formulario);
                }
            });
        }
    }
    fnjs_eliminar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            if (confirm("<?= _("¿seguro que desea borrar la habitación?") ?>")) {
                let request = $.ajax({
                    data: $(formulario).serialize(),
                    url: 'src/ubiscamas/infrastructure/controllers/habitacion_delete.php',
                    type: 'POST',
                    dataType: 'json'
                });
                request.done(function (json) {
                    if (json.success !== true) {
                        alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
                    } else {
                        fnjs_actualizar(formulario);
                    }
                });
            }
        }
    }

    fnjs_actualizar = function (formulario) {
        let campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "apps/dossiers/controller/dossiers_ver.php");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#main');
    }

</script>
<h3 class=subtitulo><?= ucfirst(_("relación de habitaciones")) ?></h3>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHashSelect->getCamposHtml() ?>
    <?= $oTabla->mostrar_tabla() ?>
</form>
<br>
<table class=botones>
    <tr class=botones>
        <td class=botones>
            <input name="btn_new" type="button" value="<?= _("crear una nueva habitación") ?>"
                   onclick="fnjs_update_div('#main','<?= $url_nuevo ?>');">
        </td>
    </tr>
</table>