<script>
    fnjs_mod_habitacion = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            $(formulario).attr('action', "frontend/ubiscamas/controller/habitacion_form.php");
            fnjs_enviar_formulario(formulario, '#ficha2006');
        }
    }
    fnjs_eliminar_habitacion = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            if (confirm(<?= json_encode(_("¿seguro que desea borrar la habitación?")) ?>)) {
                let request = $.ajax({
                    data: $(formulario).serialize(),
                    url: 'src/ubiscamas/habitacion_delete',
                    type: 'POST',
                    dataType: 'json'
                });
                request.done(function (json) {
                    if (json.success !== true) {
                        alert(<?= json_encode(_("respuesta")) ?> + ': ' + json.mensaje);
                    } else {
                        fnjs_actualizar(formulario);
                    }
                });
            }
        }
    }

    fnjs_actualizar = function (formulario) {
        let campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "frontend/dossiers/controller/dossiers_ver.php");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#main');
    }

</script>
<h3 class=subtitulo><?= ucfirst(_("relación de habitaciones")) ?></h3>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHashSelect->getCamposHtml() ?>
    <?= $oTabla->mostrar_tabla() ?>
</form>
<br>
<table class=botones>
    <tr class=botones>
        <td class=botones>
            <input name="btn_new" type="button" value="<?= _("crear una nueva habitación") ?>"
                   onclick="fnjs_update_div('#main','<?= $url_nuevo ?>');">
        </td>
    </tr>
</table>