<script>
fnjs_dl=function(){
	var filtro_region=$('#region').val();
	var url='<?= core\ConfigGlobal::getWeb().'/apps/devel/controller/db_ajax.php' ?>';
	var parametros='salida=lugar&entrada='+filtro_region+'<?= $h ?>';
	$.ajax({
		data: parametros,
		url: url,
		type: 'post',
		dataType: 'html',
		complete: function (rta) {
			rta_txt=rta.responseText;
			$('#lst_dl').html(rta_txt);
		}
	});
}
fnjs_db_crear=function(){
	$('#frm').attr('action','apps/devel/controller/db_crear_esquema.php');
	fnjs_enviar_formulario('#frm','#main');
}
fnjs_db_copiar=function(){
	$('#frm').attr('action','apps/devel/controller/db_copiar.php');
	fnjs_enviar_formulario('#frm','#main');
}
fnjs_db_eliminar=function(){
	$('#frm').attr('action','apps/devel/controller/db_eliminar.php');
	fnjs_enviar_formulario('#frm','#main');
}

</script>
<h1><?= _("nuevas dl") ?></h1>
<form id="frm" action="" method=post>
<?= $oHash->getCamposHtml(); ?>
<table>
 <tr valign=top align=left>
  <td><?= _("región") ?>:</td>
  <td><?= $oDesplRegiones->desplegable() ?>
  </td>
  <td><?= _("delegación") ?>:</td>
  <td id="lst_dl">
  </td>
 </tr>
 <tr>
 <td><?= _("sv") ?>:</td>
  <td><input type="checkbox" value="1" checked name="sv">
  </td>
  <td><?= _("sf") ?>:</td>
  <td><input type="checkbox" value="1" checked name="sf">
  </td>
 </tr>
 </table>
 <table>
 <tr>
  <td align=right><input type="button" name="bcrear" onclick="fnjs_db_crear()" value="<?= (" 1º crear Esquema") ?>"></td>
  <td align=right><input type="button" name="bimportar" onclick="fnjs_db_copiar()" value="<?= ("2º importar datos de resto") ?>"></td>
  <td align=right><input type="button" name="beliminar" onclick="fnjs_db_eliminar()" value="<?= ("passar datos a resto y eliminar esquema") ?>"></td>
 </tr>
</table>
<br><p><?= _("hay que hacer los dos pasos") ?></p>
