<script>
    fnjs_mod_cambio = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            $('#av_salida').val('modificar');
            $(formulario).attr('action', 'apps/cambios/controller/usuario_avisos_pref.php');
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_del_cambio = function (formulario, que_val) {
        rta = fnjs_solo_uno(formulario);
        if (rta == 1) {
            if (confirm(<?= json_encode(_("¿Está seguro que desea borrar este aviso?")) ?>)) {
                $('#av_salida').val('eliminar');
                $(formulario).attr('action', 'apps/cambios/controller/usuario_avisos_pref_ajax.php');
                $(formulario).one("submit", function () {
                    fnjs_ajax_json({
                        url: $(this).attr('action'),
                        data: $(this).serialize(),
                        onSuccess: function () {
                            fnjs_enviar_formulario('#avisos');
                        }
                    });
                    return false;
                });
                $(formulario).trigger("submit");
                $(formulario).off();
            }
        }
    }
    fnjs_add_cambio = function () {
        $('#av_salida').val('nuevo');
        $('#avisos').attr('action', "apps/cambios/controller/usuario_avisos_pref.php");
        fnjs_enviar_formulario('#avisos');
    }
</script>
<?= $oPosicion->mostrarNavAtras(1) ?>
<br>
<!-- <h3><?= $nombre_usuario ?></h3> -->
<h3><?= _("avisos de cambios") ?>:</h3>
<form id="avisos" name="avisos" action=''>
    <?= $oHashAvisos->getCamposHtml(); ?>
    <?= $oTablaAvisos->mostrar_tabla(); ?>
    <input type=button onclick="fnjs_add_cambio();" value="<?= _("añadir aviso") ?>">
</form>
