<?php

use core\ConfigGlobal;
use frontend\shared\web\Hash;

?>
<script>
    fnjs_modificar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            $(formulario).attr('action', "frontend/menus/controller/grupmenu_form.php");
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_eliminar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            if (confirm("<?= _("¿Está seguro que desea borrar este grupmenu?") ?>")) {
                let url = '<?= ConfigGlobal::getWeb() ?>/src/menus/infrastructure/controllers/grupmenu_eliminar.php';
                let datos = $(formulario).serialize();
                let request = $.ajax({
                    data: datos,
                    url: url,
                    method: 'POST',
                    dataType: 'json'
                });
                request.done(function (json) {
                    if (json.success !== true) {
                        alert("<?= _("respuesta") ?>" + ': ' + json.mensaje);
                    } else {
                        fnjs_actualizar();
                    }
                });
            }
        }
    }
    fnjs_actualizar = function () {
        let url = '<?= Hash::link(ConfigGlobal::getWeb() . '/frontend/menus/controller/grupmenu_lista.php') ?>';
        fnjs_update_div('#main', url);
    }
    fnjs_left_side_hide();
</script>
<h1><?= _("lista de grupmenús") ?></h1>
<p class="comentario">
    <?= _("mmmmmmmmmmmmmmmmm.") ?>
</p>
<br>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHashSelect->getCamposHtml() ?>
    <?= $oTabla->mostrar_tabla() ?>
</form>
<br>
<table>
    <tr>
        <th class="no_print">
                <span class="link_inv"
                      onclick="fnjs_update_div('#main','<?= $url_nuevo ?>');">
                    <?= core\strtoupper_dlb(_("nuevo grupmenu")) ?>
                </span>
        </th>
    </tr>
</table>
