<script>
    fnjs_lista_menus = function () {
        var filtro_grupo = $('#filtro_grupo').val();
        var url = '<?= $url ?>';
        var parametros = 'filtro_grupo=' + filtro_grupo + '<?= $h1 ?>';
        $.ajax({
            url: url,
            type: 'post',
            data: parametros,
            dataType: 'html'
        })
            .done(function (rta_txt) {
                $('#ficha').html(rta_txt);
            });
    }
</script>
<table>
    <tr>
        <th class=titulo_inv colspan=3><?= _("grupo") ?>:&nbsp;&nbsp;&nbsp;
            <?= $oDesplGM->desplegable(); ?>
        </th>
    </tr>
</table>
<div id="ficha"></div>

<?= ucfirst(_("nota")) ?>:<br>
<li><?= _("debe seleccionar un grupo de menu para poder añadir un menu.") ?>
