<?= $oPosicion->mostrarNavAtras(1) ?>
<script>
    fnjs_lista_menus = function () {
        var filtro_grupo = $('#filtro_grupo').val();
        var url = '<?= $url ?>';
        var parametros = 'filtro_grupo=' + filtro_grupo + '<?= $h1 ?>';
        fnjs_ajax_json_html({ url: url, data: parametros, target: '#ficha' });
    }
</script>
<table>
    <tr>
        <th class=titulo_inv colspan=3><?= _("grupo") ?>:&nbsp;&nbsp;&nbsp;
            <?= $oDesplGM->desplegable(); ?>
        </th>
    </tr>
</table>
<div id="ficha"></div>

<?= ucfirst(_("nota")) ?>:<br>
<li><?= _("debe seleccionar un grupo de menu para poder añadir un menu.") ?>
