<script>
    fnjs_buscar_por_apellidos = function () {
        $('#apellidos_form').attr('action', "apps/actividadestudios/controller/matriculas_lista_otras_r.php");
        fnjs_enviar_formulario('#apellidos_form', '#main');
    }

    fnjs_buscar = function () {
        var campo = '<input type="hidden" name="refresh" value=1>';
        $('#periodo_form').attr('action', "apps/actividadestudios/controller/matriculas_lista_otras_r.php");
        $('#periodo_form').append(campo);
        fnjs_enviar_formulario('#periodo_form', '#main');
    }

    fnjs_imp_certificado = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            $(formulario).attr('action', "frontend/certificados/controller/certificado_imprimir.php");
            $(formulario).target = "print";
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_left_side_hide();
</script>
<form id='apellidos_form' action=''>
    <?= $oHashApellidos->getCamposHtml() ?>
    <table>
        <tr>
            <td class=etiqueta>
                <h2 class=titulo><?= $titulo_busqueda_por_apellidos ?></h2>
            </td>
            <td  style="vertical-align: middle"><input class=contenido id="apellido1" name="apellido1" size="40" value="<?= $Qapellido1 ?>"></td>
            <td>
                <input type="button" id="btn_ok" name="btn"
                      onclick="fnjs_buscar_por_apellidos('#apellidos_form')"
                      value="<?= ucfirst(_("buscar")) ?>" class="btn">
            </td>
        </tr>
    </table>
</form>
<br>

<h2 class=titulo><?= $titulo ?></h2>
<h3><?= $aviso; ?></h3>
<form id="seleccionados" name="seleccionados" action="" method="post">
    <?= $oHash->getCamposHtml() ?>
    <input type="hidden" id="pau" name="pau" value="p">
    <input type="hidden" id="mod" name="mod" value="">
    <?= $oTabla->mostrar_tabla() ?>
</form>