<script>
    fnjs_enviar_certificado = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            let request = $.ajax({
                data: $(formulario).serialize(),
                url: 'src/certificados/infrastructure/controllers/certificado_enviar.php',
                method: 'POST',
                dataType: 'json'
            });
            request.done(function (json) {
                if (json.success !== true) {
                    alert("<?= _("respuesta") ?>: " + json.mensaje);
                } else {
                    fnjs_actualizar(formulario);
                }
            });
        }
    }
    fnjs_upload_certificado = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            $(formulario).attr('action', "frontend/certificados/controller/certificado_upload_firmado.php");
            $(formulario).target = "print";
            fnjs_enviar_formulario(formulario);
        }
    }

    fnjs_descargar_pdf = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            /* selecciono los elementos con class="sel" de las tablas con id = formulario */
            $(formulario + ' input.sel').each(function () {
                let url_download;
                let key;
                let url;
                if ($(this).prop('checked') === true) {
                    key = $(this).prop('value');
                    url = 'frontend/certificados/controller/certificado_pdf_download.php';
                    url_download = url + '?key=' + key + '&<?= $h_download ?>';
                    window.open(url_download);
                }
            });
        }
    }
    fnjs_nuevo = function (formulario) {
        $('#mod').val("nueva");
        $(formulario).attr('action', "frontend/certificados/controller/certificado_ver.php");
        fnjs_enviar_formulario(formulario, '#main');
    }
    fnjs_modificar = function (formulario) {
        $('#mod').val("modificar");
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            $(formulario).attr('action', "frontend/certificados/controller/certificado_ver.php");
            fnjs_enviar_formulario(formulario);
        }
    }
    fnjs_eliminar = function (formulario) {
        rta = fnjs_solo_uno(formulario);
        if (rta === 1) {
            if (confirm("<?= $txt_eliminar ?>")) {
                $('#mod').val("eliminar");
                let request = $.ajax({
                    data: $(formulario).serialize(),
                    url: 'src/certificados/infrastructure/controllers/certificado_delete.php',
                    method: 'POST',
                    dataType: 'json'
                });
                request.done(function (json) {
                    if (json.success !== true) {
                        alert("<?= _("respuesta") ?>: " + json.mensaje);
                    } else {
                        fnjs_actualizar(formulario);
                    }
                });
            }
        }
    }
    fnjs_actualizar = function (formulario) {
        let campo = '<input type="hidden" name="refresh" value=1>';
        $(formulario).attr('action', "frontend/certificados/controller/certificado_select.php");
        $(formulario).append(campo);
        fnjs_enviar_formulario(formulario, '#main');
    }
    fnjs_left_side_hide();
</script>
<form id="frm_sin_nombre" name="frm_sin_nombre" action="frontend/certificados/controller/certificado_lista.php"
      method="post"
      onkeydown="fnjs_enviar(event,this);">
    <?= $oHash->getCamposHtml() ?>

    <p class="comentario"><?= _("<b>Ayuda para búsquedas</b>") ?>:<br>
        <br>
        - <?= _("Si solo se utiliza el <b>formato nn/aa</b> (12/21, 7/19, etc.) buscará los certificados del ámbito con esa numeración.") ?>
        <br>
        - <?= _("Para buscar certificados se puede utilizar <b>comodines</b> de la siguiente forma:") ?><br>
        - <?= _("Un <b>punto</b> (.) significa cualquier carácter en esa posición.") ?><br>
        - <?= _("Un <b>asterisco</b> (*) significa que el carácter precedente puede repetirse de forma indefinida en la cadena.") ?>
        <br>
        - <?= _("Por lo tanto, punto y asterisco (.*) significa que puede haber un numero indeterminado de caracteres en esa posición.") ?>
        <br>
    </p>

    <table>
        <th class=titulo_inv colspan=4><?= ucfirst(_("buscar un certificado")) ?>
            &nbsp;&nbsp;&nbsp;<input class=contenido id="certificado" name="certificado" size="30">
            <div class="help-tip">
                <p><?= _("ejemplos") ?>:<br>
                    - <?= _("23/15 (sólo número) => busca en los certificados de la rstgr.") ?><br>
                    - <?= _("H .* | crEso .* => todos las certificados de H o Eso. Hay que dejar espacio") ?><br>
                    - <?= _("H .*/15 | crEso .*/15 => todos los certificados de H o crEso del año 15") ?><br>
                </p>
            </div>
        </th>
        <th colspan=4><input type="button" id="btn_ok" name="btn_ok"
                             onclick="fnjs_enviar_formulario('#frm_sin_nombre');" value="<?= ucfirst(_("buscar")) ?>"
                             class="btn_ok">
        </th>
    </table>
</form>

<h3 class=subtitulo><?= $titulo ?></h3>
<form id='seleccionados' name='seleccionados' action='' method='post'>
    <?= $oHash1->getCamposHtml() ?>
    <input type='Hidden' id='mod' name='mod' value=''>
    <?= $oTabla->mostrar_tabla() ?>
</form>